# Generated by Django 5.0.9 on 2026-05-13 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Šifra')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redosled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tip ugovora',
                'verbose_name_plural': 'Tipovi ugovora',
                'db_table': 'ugovori_contract_type',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MAIN', 'Glavni ugovor'), ('ANNEX', 'Aneks')], db_index=True, default='MAIN', max_length=10, verbose_name='Vrsta')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='Broj ugovora')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Predmet ugovora')),
                ('contract_date', models.DateField(verbose_name='Datum ugovora')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Važi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Važi do')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Vrednost')),
                ('currency', models.CharField(choices=[('RSD', 'RSD'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF')], default='RSD', max_length=10, verbose_name='Valuta')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('active', 'Aktivan'), ('expired', 'Istekao'), ('terminated', 'Raskinut'), ('archived', 'Arhiviran')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='ugovori/files/%Y/%m/', verbose_name='Fajl ugovora')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_kreirani', to=settings.AUTH_USER_MODEL)),
                ('parent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annexes', to='ugovori.contract', verbose_name='Glavni ugovor')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ugovori.contracttype', verbose_name='Tip ugovora')),
            ],
            options={
                'verbose_name': 'Ugovor',
                'verbose_name_plural': 'Ugovori',
                'db_table': 'ugovori_contract',
                'ordering': ['-contract_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv / Ime i prezime')),
                ('partner_type', models.CharField(choices=[('legal_entity', 'Pravno lice'), ('person', 'Fizičko lice')], db_index=True, default='legal_entity', max_length=20, verbose_name='Tip partnera')),
                ('residency', models.CharField(choices=[('domestic', 'Domaći'), ('foreign', 'Strani')], db_index=True, default='domestic', max_length=20, verbose_name='Rezidentnost')),
                ('external_sif_par', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Šifra (stari sistem)')),
                ('pib', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIB')),
                ('maticni_broj', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matični broj')),
                ('jmbg', models.CharField(blank=True, max_length=13, null=True, verbose_name='JMBG')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj pasoša')),
                ('foreign_tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Strani poreski ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zemlja')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grad / Mesto')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt osoba')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_partneri_kreirani', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partneri',
                'db_table': 'ugovori_partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('kupac', 'Kupac'), ('prodavac', 'Prodavac'), ('zakupodavac', 'Zakupodavac'), ('zakupac', 'Zakupac'), ('izvođač', 'Izvođač radova'), ('naručilac', 'Naručilac'), ('garant', 'Garant / Žirant'), ('ostalo', 'Ostalo')], max_length=30, verbose_name='Uloga')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='ugovori.contract', verbose_name='Ugovor')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_parties', to='ugovori.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Stranka ugovora',
                'verbose_name_plural': 'Stranke ugovora',
                'db_table': 'ugovori_contract_party',
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['kind', 'status'], name='ugovori_con_kind_48dfab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractparty',
            unique_together={('contract', 'partner', 'role')},
        ),
    ]
