# Generated by Django 5.0.9 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugovori', '0003_partner_apr_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Jedinica'),
        ),
        migrations.AddField(
            model_name='contract',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cena po jedinici'),
        ),
        migrations.AddField(
            model_name='contract',
            name='value_type',
            field=models.CharField(choices=[('fixed', 'Fiksna vrednost'), ('hourly', 'Po radnom satu'), ('unit', 'Po jedinici'), ('undefined', 'Bez definisane vrednosti')], db_index=True, default='fixed', max_length=20, verbose_name='Tip vrednosti'),
        ),
    ]
