# Generated by Django 5.0.9 on 2026-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugovori', '0004_contract_unit_label_contract_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value_type',
            field=models.CharField(choices=[('fixed', 'Fiksna vrednost'), ('hourly', 'Po radnom satu'), ('monthly', 'Mesečno'), ('man_month', 'Čovek mesec'), ('unit', 'Po jedinici'), ('undefined', 'Bez definisane vrednosti')], db_index=True, default='fixed', max_length=20, verbose_name='Tip vrednosti'),
        ),
    ]
