# Generated by Django 5.0.9 on 2026-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugovori', '0005_alter_contract_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='party_contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj ugovora kod stranke'),
        ),
    ]
