# Generated by Django 5.0.9 on 2026-05-26 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menice', '__first__'),
        ('ugovori', '0006_contractparty_party_contract_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='has_guarantees',
            field=models.BooleanField(default=False, verbose_name='Ima garancije'),
        ),
        migrations.AddField(
            model_name='contract',
            name='has_incoming_menice',
            field=models.BooleanField(default=False, verbose_name='Ima ulazne menice'),
        ),
        migrations.AddField(
            model_name='contract',
            name='has_outgoing_menice',
            field=models.BooleanField(default=False, verbose_name='Ima izlazne menice'),
        ),
        migrations.CreateModel(
            name='ContractGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_number', models.CharField(max_length=100, verbose_name='Broj garancije')),
                ('issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izdavalac / banka')),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Korisnik garancije')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Iznos')),
                ('currency', models.CharField(choices=[('RSD', 'RSD'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF')], default='RSD', max_length=10, verbose_name='Valuta')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vazi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vazi do')),
                ('status', models.CharField(choices=[('active', 'Aktivna'), ('returned', 'Vracena'), ('expired', 'Istekla'), ('cancelled', 'Stornirana')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='ugovori.contract', verbose_name='Ugovor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_garancije_kreirane', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garancija uz ugovor',
                'verbose_name_plural': 'Garancije uz ugovore',
                'db_table': 'ugovori_contract_guarantee',
                'ordering': ['-valid_to', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMenicaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menica_links', to='ugovori.contract', verbose_name='Ugovor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_menica_linkovi_kreirani', to=settings.AUTH_USER_MODEL)),
                ('menica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='menice.menica', verbose_name='Menica')),
                ('ulazna_menica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='menice.ulaznamenica', verbose_name='Ulazna menica')),
            ],
            options={
                'verbose_name': 'Veza ugovora i menice',
                'verbose_name_plural': 'Veze ugovora i menica',
                'db_table': 'ugovori_contract_menica_link',
                'ordering': ['-created_at'],
            },
        ),
    ]
