# Generated by Django 5.0.9 on 2026-05-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugovori', '0007_contract_has_guarantees_contract_has_incoming_menice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True, verbose_name='Broj zahteva')),
                ('request_date', models.DateField(verbose_name='Datum zahteva')),
                ('external_partner_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv narucioca')),
                ('request_type', models.CharField(choices=[('testing', 'Ispitivanje'), ('service', 'Usluga'), ('field', 'Izlazak na teren'), ('consulting', 'Konsultacija'), ('other', 'Ostalo')], db_index=True, default='service', max_length=20, verbose_name='Tip zahteva')),
                ('subject', models.CharField(max_length=255, verbose_name='Predmet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis / napomena')),
                ('center', models.CharField(blank=True, default='', max_length=100, verbose_name='Centar / sektor')),
                ('status', models.CharField(choices=[('recorded', 'Evidentiran'), ('in_progress', 'U radu'), ('completed', 'Zavrsen'), ('rejected', 'Odbijen'), ('archived', 'Arhiviran')], db_index=True, default='recorded', max_length=20, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='ugovori/zahtevi/%Y/%m/', verbose_name='Fajl zahteva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_zahtevi_kreirani', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_requests', to='ugovori.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Zahtev',
                'verbose_name_plural': 'Zahtevi',
                'db_table': 'ugovori_business_request',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=100, unique=True, verbose_name='Broj ponude')),
                ('offer_date', models.DateField(verbose_name='Datum ponude')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vazi do')),
                ('direction', models.CharField(choices=[('outgoing', 'Nasa ponuda'), ('incoming', 'Ponuda data nama')], db_index=True, default='outgoing', max_length=20, verbose_name='Smer')),
                ('external_partner_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv partnera')),
                ('offer_type', models.CharField(choices=[('testing', 'Ispitivanje'), ('service', 'Usluga'), ('field', 'Izlazak na teren'), ('procurement', 'Nabavka'), ('other', 'Ostalo')], db_index=True, default='service', max_length=20, verbose_name='Tip ponude')),
                ('subject', models.CharField(max_length=255, verbose_name='Predmet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis / napomena')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Vrednost')),
                ('currency', models.CharField(choices=[('RSD', 'RSD'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF')], default='RSD', max_length=10, verbose_name='Valuta')),
                ('status', models.CharField(choices=[('recorded', 'Evidentirana'), ('accepted', 'Prihvacena'), ('rejected', 'Odbijena'), ('expired', 'Istekla'), ('archived', 'Arhivirana')], db_index=True, default='recorded', max_length=20, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to='ugovori/ponude/%Y/%m/', verbose_name='Fajl ponude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori_ponude_kreirane', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='ugovori.partner', verbose_name='Partner')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='ugovori.businessrequest', verbose_name='Zahtev')),
            ],
            options={
                'verbose_name': 'Ponuda',
                'verbose_name_plural': 'Ponude',
                'db_table': 'ugovori_offer',
                'ordering': ['-offer_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessrequest',
            index=models.Index(fields=['request_type', 'status'], name='ugovori_bus_request_6aa44c_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['direction', 'status'], name='ugovori_off_directi_e2422a_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'status'], name='ugovori_off_offer_t_c84774_idx'),
        ),
    ]
