# Generated by Django 5.0.9 on 2026-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinskipostupak',
            name='mera_vrsta',
            field=models.CharField(blank=True, choices=[('1', 'Pisana opomena'), ('2', 'Udaljenje sa rada bez naknade zarade od 1 do 15 radnih dana'), ('3', 'Novčana kazna do 20% osnovne zarade za mesec u kome je izrečena, u trajanju do 3 meseca'), ('4', 'Prestanak radnog odnosa')], max_length=1, verbose_name='Izrečena mera'),
        ),
    ]
