# Generated by Django 5.0.9 on 2026-10-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravna', '0002_disciplinskipostupak_mera_vrsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinskipostupak',
            name='mera_procenat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Procenat osnovne zarade'),
        ),
        migrations.AddField(
            model_name='disciplinskipostupak',
            name='mera_trajanje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trajanje (meseci)'),
        ),
    ]
