# Generated by Django 5.0.9 on 2026-10-01 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacija', '0009_dodela_daje_ulogu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupaKategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redosled', models.PositiveSmallIntegerField()),
                ('klasifikaciona_oznaka', models.CharField(max_length=30, verbose_name='Klasifikaciona oznaka')),
                ('naziv', models.CharField(max_length=500, verbose_name='Naziv grupe')),
            ],
            options={
                'verbose_name': 'Grupa kategorija',
                'verbose_name_plural': 'Grupe kategorija',
                'db_table': 'arhiva_grupa_kategorija',
                'ordering': ['verzija', 'redosled'],
            },
        ),
        migrations.CreateModel(
            name='EvidencionaKnjiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('delovodnik', 'Delovodnik'), ('dostavna', 'Dostavna knjiga'), ('otpremna', 'Otpremna knjiga (P-3)')], default='delovodnik', max_length=20)),
                ('godina', models.PositiveSmallIntegerField()),
                ('oznaka', models.CharField(blank=True, default='', help_text='Za dostavne knjige po OJ; delovodnik je jedan za ceo Institut.', max_length=40)),
                ('naziv', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('otvorena', 'Otvorena'), ('zakljucena', 'Zaključena')], default='otvorena', max_length=12)),
                ('istorijska', models.BooleanField(default=False, help_text='Uvezena iz ranijeg programa, samo za čitanje.')),
                ('zakljucena_at', models.DateTimeField(blank=True, null=True)),
                ('broj_akata_pri_zakljucenju', models.PositiveIntegerField(blank=True, null=True)),
                ('zabeleska', models.TextField(blank=True, default='', verbose_name='Službena zabeleška')),
                ('zakljucio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidenciona knjiga',
                'verbose_name_plural': 'Evidencione knjige',
                'db_table': 'arhiva_evidenciona_knjiga',
                'ordering': ['-godina', 'vrsta', 'oznaka'],
            },
        ),
        migrations.CreateModel(
            name='BrojacKnjige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poslednji_broj', models.PositiveIntegerField(default=0)),
                ('knjiga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brojac', to='arhiva.evidencionaknjiga')),
            ],
            options={
                'verbose_name': 'Brojač knjige',
                'verbose_name_plural': 'Brojači knjiga',
                'db_table': 'arhiva_brojac_knjige',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField(verbose_name='Redni broj')),
                ('naziv', models.TextField(verbose_name='Kategorija dokumentarnog materijala')),
                ('rok_tekst', models.CharField(max_length=200, verbose_name='Rok čuvanja (kako piše u Listi)')),
                ('rok_godina', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rok (godina)')),
                ('trajno', models.BooleanField(default=False, verbose_name='Trajno')),
                ('operativno', models.BooleanField(default=False, verbose_name='Trajno operativno')),
                ('pocetak_roka', models.CharField(choices=[('zavrsetak_predmeta', 'Od završetka predmeta'), ('istek_ugovora', 'Od isteka ugovora'), ('prestanak_vazenja', 'Od prestanka važenja'), ('okoncanje_postupka', 'Po okončanju postupka'), ('prestanak_zakupa', 'Od prestanka zakupa'), ('prestanak_radnog_odnosa', 'Od prestanka radnog odnosa'), ('rucno', 'Određuje se pojedinačno')], default='zavrsetak_predmeta', max_length=30, verbose_name='Rok teče')),
                ('napomena_roka', models.CharField(blank=True, default='', max_length=300, verbose_name='Napomena uz rok')),
                ('aktivna', models.BooleanField(default=True, verbose_name='Nudi se pri izboru')),
                ('duplikat_od', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplikati', to='arhiva.kategorija', verbose_name='Duplikat stavke')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kategorije', to='arhiva.grupakategorija')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'db_table': 'arhiva_kategorija',
                'ordering': ['verzija', 'redni_broj'],
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osnovni_broj', models.PositiveIntegerField(verbose_name='Osnovni broj')),
                ('delovodni_broj', models.CharField(max_length=40, verbose_name='Delovodni broj')),
                ('datum_zavodjenja', models.DateField(verbose_name='Datum zavođenja')),
                ('naslov', models.CharField(max_length=500, verbose_name='Predmet')),
                ('smer', models.CharField(choices=[('ulazni', 'Ulazni'), ('izlazni', 'Izlazni'), ('interni', 'Interni')], default='ulazni', max_length=10, verbose_name='Smer')),
                ('korespondent', models.CharField(blank=True, default='', help_text='Ime i prezime ili naziv', max_length=255, verbose_name='Pošiljalac / primalac')),
                ('mesto', models.CharField(blank=True, default='', max_length=100, verbose_name='Mesto')),
                ('broj_akta_posiljaoca', models.CharField(blank=True, default='', max_length=100, verbose_name='Broj akta pošiljaoca')),
                ('datum_akta_posiljaoca', models.DateField(blank=True, null=True, verbose_name='Datum akta pošiljaoca')),
                ('oznaka_centra', models.CharField(help_text='Snimak u trenutku zavođenja; ulazi u delovodni broj.', max_length=40, verbose_name='Oznaka centra (u broju)')),
                ('status', models.CharField(choices=[('zaveden', 'Zaveden'), ('razveden', 'Razveden'), ('u_radu', 'U radu'), ('zavrsen', 'Završen'), ('storniran', 'Storniran')], db_index=True, default='zaveden', max_length=12)),
                ('napomena', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('razlog_storna', models.TextField(blank=True, default='', verbose_name='Razlog storna')),
                ('stornirano_at', models.DateTimeField(blank=True, null=True)),
                ('zavedeno_at', models.DateTimeField(auto_now_add=True)),
                ('dodatne_oj', models.ManyToManyField(blank=True, related_name='arhiva_predmeti_dodatno', to='organizacija.orgnode', verbose_name='Dodatne OJ')),
                ('glavna_oj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arhiva_predmeti', to='organizacija.orgnode', verbose_name='Organizaciona jedinica')),
                ('kategorija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predmeti', to='arhiva.kategorija', verbose_name='Kategorija')),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predmeti', to='arhiva.evidencionaknjiga')),
                ('referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arhiva_predmeti', to=settings.AUTH_USER_MODEL, verbose_name='Zaduženi referent')),
                ('stornirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zaveo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predmet',
                'verbose_name_plural': 'Predmeti',
                'db_table': 'arhiva_predmet',
                'ordering': ['-knjiga__godina', '-osnovni_broj'],
            },
        ),
        migrations.CreateModel(
            name='Akt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podbroj', models.PositiveSmallIntegerField(verbose_name='Podbroj')),
                ('delovodni_broj', models.CharField(max_length=50, verbose_name='Delovodni broj akta')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('opis', models.CharField(max_length=500, verbose_name='Opis')),
                ('smer', models.CharField(choices=[('ulazni', 'Ulazni'), ('izlazni', 'Izlazni'), ('interni', 'Interni')], default='ulazni', max_length=10, verbose_name='Smer')),
                ('zavedeno_at', models.DateTimeField(auto_now_add=True)),
                ('zaveo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='akti', to='arhiva.predmet')),
            ],
            options={
                'verbose_name': 'Akt',
                'verbose_name_plural': 'Akti',
                'db_table': 'arhiva_akt',
                'ordering': ['predmet', 'podbroj'],
            },
        ),
        migrations.CreateModel(
            name='VerzijaListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv')),
                ('datum_donosenja', models.DateField(blank=True, null=True, verbose_name='Datum donošenja')),
                ('broj_saglasnosti', models.CharField(blank=True, default='', max_length=100, verbose_name='Broj saglasnosti arhiva')),
                ('datum_saglasnosti', models.DateField(blank=True, null=True, verbose_name='Datum saglasnosti')),
                ('vazi_od', models.DateField(blank=True, null=True, verbose_name='Važi od')),
                ('aktivna', models.BooleanField(default=False, verbose_name='Aktivna')),
                ('izvor', models.CharField(blank=True, default='', max_length=255, verbose_name='Uvezeno iz fajla')),
                ('uvezeno_at', models.DateTimeField(auto_now_add=True)),
                ('uvezao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verzija Liste kategorija',
                'verbose_name_plural': 'Verzije Liste kategorija',
                'db_table': 'arhiva_verzija_liste',
                'ordering': ['-datum_donosenja', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='kategorija',
            name='verzija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorije', to='arhiva.verzijaliste'),
        ),
        migrations.AddField(
            model_name='grupakategorija',
            name='verzija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='arhiva.verzijaliste'),
        ),
        migrations.AddConstraint(
            model_name='evidencionaknjiga',
            constraint=models.UniqueConstraint(fields=('vrsta', 'godina', 'oznaka'), name='arhiva_knjiga_godina'),
        ),
        migrations.AddIndex(
            model_name='predmet',
            index=models.Index(fields=['datum_zavodjenja'], name='arhiva_pred_datum_z_a41803_idx'),
        ),
        migrations.AddConstraint(
            model_name='predmet',
            constraint=models.UniqueConstraint(fields=('knjiga', 'osnovni_broj'), name='arhiva_predmet_osnovni_broj'),
        ),
        migrations.AddConstraint(
            model_name='predmet',
            constraint=models.UniqueConstraint(fields=('knjiga', 'delovodni_broj'), name='arhiva_predmet_delovodni_broj'),
        ),
        migrations.AddConstraint(
            model_name='akt',
            constraint=models.UniqueConstraint(fields=('predmet', 'podbroj'), name='arhiva_akt_podbroj'),
        ),
        migrations.AddConstraint(
            model_name='verzijaliste',
            constraint=models.UniqueConstraint(condition=models.Q(('aktivna', True)), fields=('aktivna',), name='arhiva_jedna_aktivna_lista'),
        ),
        migrations.AddConstraint(
            model_name='kategorija',
            constraint=models.UniqueConstraint(fields=('verzija', 'redni_broj'), name='arhiva_kategorija_rb'),
        ),
    ]
