from django.urls import path

from .views.mobile import (
    MobileAssignmentCreateView,
    MobileAssignmentDeleteView,
    MobileAssignmentListView,
    MobileAssignmentUpdateView,
    MobileDashboardView,
    MobilePhoneDetailView,
    MobilePackageCreateView,
    MobilePackageDeleteView,
    MobilePackageListView,
    MobilePackageUpdateView,
    MobileParkingExemptionCreateView,
    MobileParkingExemptionDeleteView,
    MobileParkingExemptionListView,
    MobileParkingExemptionUpdateView,
    MobileUsageCreateView,
    MobileUsageDeleteView,
    MobileUsageListView,
    MobileUsageUpdateView,
    MobileUserCreateView,
    MobileUserDeleteView,
    MobileUserListView,
    MobileUserUpdateView,
    MobileWithholdingReportView,
    export_employee_withholdings_csv,
    export_assignments_xlsx,
    export_packages_xlsx,
    export_usages_xlsx,
    export_users_xlsx,
    mobile_import_view,
)


app_name = "mobilni"

urlpatterns = [
    path("", MobileDashboardView.as_view(), name="mobile_dashboard"),
    path("import/", mobile_import_view, name="mobile_import"),
    path("dodele/", MobileAssignmentListView.as_view(), name="mobile_assignment_list"),
    path("dodele/export.xlsx", export_assignments_xlsx, name="mobile_assignment_export"),
    path("brojevi/<str:phone_number>/", MobilePhoneDetailView.as_view(), name="mobile_phone_detail"),
    path("dodele/novo/", MobileAssignmentCreateView.as_view(), name="mobile_assignment_create"),
    path("dodele/<int:pk>/izmena/", MobileAssignmentUpdateView.as_view(), name="mobile_assignment_update"),
    path("dodele/<int:pk>/brisanje/", MobileAssignmentDeleteView.as_view(), name="mobile_assignment_delete"),
    path("potrosnja/", MobileUsageListView.as_view(), name="mobile_usage_list"),
    path("potrosnja/export.xlsx", export_usages_xlsx, name="mobile_usage_export"),
    path("potrosnja/obracunski-mesec.csv", export_employee_withholdings_csv, name="mobile_usage_accounting_csv"),
    path("potrosnja/novo/", MobileUsageCreateView.as_view(), name="mobile_usage_create"),
    path("potrosnja/<int:pk>/izmena/", MobileUsageUpdateView.as_view(), name="mobile_usage_update"),
    path("potrosnja/<int:pk>/brisanje/", MobileUsageDeleteView.as_view(), name="mobile_usage_delete"),
    path("paketi/", MobilePackageListView.as_view(), name="mobile_package_list"),
    path("paketi/export.xlsx", export_packages_xlsx, name="mobile_package_export"),
    path("paketi/novo/", MobilePackageCreateView.as_view(), name="mobile_package_create"),
    path("paketi/<int:pk>/izmena/", MobilePackageUpdateView.as_view(), name="mobile_package_update"),
    path("paketi/<int:pk>/brisanje/", MobilePackageDeleteView.as_view(), name="mobile_package_delete"),
    path("korisnici/", MobileUserListView.as_view(), name="mobile_user_list"),
    path("korisnici/export.xlsx", export_users_xlsx, name="mobile_user_export"),
    path("korisnici/novo/", MobileUserCreateView.as_view(), name="mobile_user_create"),
    path("korisnici/<int:pk>/izmena/", MobileUserUpdateView.as_view(), name="mobile_user_update"),
    path("korisnici/<int:pk>/brisanje/", MobileUserDeleteView.as_view(), name="mobile_user_delete"),
    path("parking-izuzeci/", MobileParkingExemptionListView.as_view(), name="mobile_parking_exemption_list"),
    path("parking-izuzeci/novo/", MobileParkingExemptionCreateView.as_view(), name="mobile_parking_exemption_create"),
    path("parking-izuzeci/<int:pk>/izmena/", MobileParkingExemptionUpdateView.as_view(), name="mobile_parking_exemption_update"),
    path("parking-izuzeci/<int:pk>/brisanje/", MobileParkingExemptionDeleteView.as_view(), name="mobile_parking_exemption_delete"),
    path(
        "obustave/",
        MobileWithholdingReportView.as_view(report_type="sve"),
        name="mobile_withholding_all",
    ),
    path(
        "obustave/zaposleni/",
        MobileWithholdingReportView.as_view(report_type="zaposleni"),
        name="mobile_withholding_employees",
    ),
    path(
        "obustave/bivsi-zaposleni/",
        MobileWithholdingReportView.as_view(report_type="bivsi-zaposleni"),
        name="mobile_withholding_former_employees",
    ),
    path(
        "obustave/nezaposleni/",
        MobileWithholdingReportView.as_view(report_type="nezaposleni"),
        name="mobile_withholding_non_employees",
    ),
    path(
        "obustave/zaposleni/export.csv",
        export_employee_withholdings_csv,
        name="mobile_withholding_employees_export",
    ),
]
