# Generated by Django 5.0.9 on 2026-09-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrazivanja', '0002_initial_aging_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=64)),
                ('row_count', models.PositiveBigIntegerField()),
                ('first_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='potrazivanja.collectionsyncrun')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('partner_code', models.IntegerField(blank=True, null=True)),
                ('job_code', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='potrazivanja.sourcedataset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sourcedataset',
            constraint=models.UniqueConstraint(fields=('name', 'fingerprint'), name='col_dataset_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='sourcerow',
            index=models.Index(fields=['dataset', 'partner_code'], name='col_source_partner'),
        ),
        migrations.AddConstraint(
            model_name='sourcerow',
            constraint=models.UniqueConstraint(fields=('dataset', 'ordinal'), name='col_source_ordinal'),
        ),
    ]
