# Generated by Django 5.0.9 on 2026-09-18 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrazivanja', '0003_sourcedataset_sourcerow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionactivity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='potrazivanja.collectioncontact'),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ime'),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='import_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='separated_contacts', to='potrazivanja.collectioncontact'),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prezime'),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='original_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='collectioncontact',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Funkcija / odeljenje'),
        ),
        migrations.AddField(
            model_name='collectionnotice',
            name='body',
            field=models.TextField(blank=True, verbose_name='Tekst dokumenta'),
        ),
        migrations.AddField(
            model_name='collectionnotice',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, verbose_name='Primalac'),
        ),
        migrations.AddField(
            model_name='collectionnotice',
            name='response_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rok za odgovor / plaćanje'),
        ),
        migrations.AddField(
            model_name='collectionstate',
            name='operations_independent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollectionLegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('tip', models.CharField(choices=[('tuzeni', 'Tuženi'), ('tuzili', 'Tužili'), ('stecaj', 'Stečaj'), ('uppr', 'UPPR')], default='tuzeni', max_length=20, verbose_name='Vrsta postupka')),
                ('sud', models.CharField(blank=True, max_length=255, verbose_name='Sud')),
                ('broj_predmeta', models.CharField(blank=True, max_length=100, verbose_name='Broj predmeta')),
                ('sifra_partnera', models.IntegerField(blank=True, null=True)),
                ('naziv_partnera', models.CharField(blank=True, max_length=255, verbose_name='Naziv partnera u evidenciji')),
                ('valuta', models.CharField(choices=[('RSD', 'RSD'), ('EUR', 'EUR'), ('USD', 'USD')], default='RSD', max_length=10, verbose_name='Valuta')),
                ('osnovni_dug', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Osnovni dug')),
                ('arhivirano', models.BooleanField(default=False)),
                ('izvrsiteljski_broj', models.CharField(blank=True, max_length=100, verbose_name='Izvršiteljski broj')),
                ('datum_pokretanja', models.DateField(blank=True, null=True, verbose_name='Datum pokretanja')),
                ('predmet_spora', models.TextField(blank=True, verbose_name='Predmet spora')),
                ('tuzilac', models.CharField(blank=True, max_length=255, verbose_name='Tužilac')),
                ('vrednost_spora', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Vrednost spora')),
                ('datum_podnosenja_tuzbe', models.DateField(blank=True, null=True, verbose_name='Datum podnošenja tužbe')),
                ('vece', models.CharField(blank=True, max_length=100, verbose_name='Veće')),
                ('kamata', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Kamata')),
                ('troskovi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Troškovi')),
                ('ukupan_dug', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ukupan dug')),
                ('datum_otvaranja_stecaja', models.DateField(blank=True, null=True, verbose_name='Datum otvaranja stečaja')),
                ('prijava_potrazivanja', models.TextField(blank=True, verbose_name='Prijava potraživanja')),
                ('novi_broj', models.CharField(blank=True, max_length=100, verbose_name='Novi broj')),
                ('pib', models.CharField(blank=True, max_length=20, verbose_name='PIB')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='potrazivanja.financepartneridentity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionLegalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('date', models.DateField(verbose_name='Datum')),
                ('text', models.TextField(verbose_name='Promena / beleška')),
                ('archived', models.BooleanField(default=False)),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='potrazivanja.collectionlegalcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('phone', 'Telefon'), ('mobile', 'Mobilni'), ('email', 'E-pošta')], max_length=10, verbose_name='Vrsta')),
                ('value', models.CharField(max_length=255, verbose_name='Broj / adresa')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Namena')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='potrazivanja.collectioncontact')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(max_length=30)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'entity_id', 'created_at'], name='col_audit_entity')],
            },
        ),
        migrations.AddConstraint(
            model_name='contactpoint',
            constraint=models.UniqueConstraint(fields=('contact', 'kind', 'value'), name='col_contact_point_unique'),
        ),
    ]
