# Generated by Django 5.0.9 on 2026-09-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacija', '0006_nauka_deo_bloka_3'),
        ('potrazivanja', '0006_collectionfileimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableposition',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='potrazivanja_pozicije', to='organizacija.orgnode'),
        ),
        migrations.AddField(
            model_name='receivableposting',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='potrazivanja_stavke', to='organizacija.orgnode'),
        ),
    ]
