# Generated by Django 5.0.9 on 2026-10-06 14:13

from django.conf import settings
from django.db import migrations, models


def _kljuc(broj):
    broj = (broj or "").strip()
    deo, tacka, decimale = broj.partition(".")
    if tacka and deo.isdigit() and decimale and set(decimale) == {"0"}:
        broj = deo
    return broj.upper()


def razdvoji_duplikate(apps, schema_editor):
    """Isti broj iste vrste u istoj godini: prvi (po datumu, pa unosu) zadržava broj, ostali dobijaju -1, -2, …
    Promena se beleži u evidenciji izmena Potraživanja."""
    Notice = apps.get_model("potrazivanja", "CollectionNotice")
    Audit = apps.get_model("potrazivanja", "CollectionAudit")
    grupe, zauzeti = {}, set()
    for n in Notice.objects.exclude(number="").exclude(year__isnull=True).order_by("issued_on", "pk"):
        grupe.setdefault((n.kind, n.year, _kljuc(n.number)), []).append(n)
        zauzeti.add((n.kind, n.year, _kljuc(n.number)))
    for (vrsta, godina, kljuc), zapisi in grupe.items():
        for n in zapisi[1:]:
            i = 1
            while (vrsta, godina, f"{kljuc}-{i}".upper()) in zauzeti:
                i += 1
            novi = f"{kljuc}-{i}"
            zauzeti.add((vrsta, godina, novi.upper()))
            Audit.objects.create(entity="potrazivanja.collectionnotice", entity_id=n.pk, action="renumber",
                                 before={"number": n.number}, after={"number": novi})
            Notice.objects.filter(pk=n.pk).update(number=novi)


class Migration(migrations.Migration):

    dependencies = [
        ('potrazivanja', '0007_veza_sa_registrom_organizacije'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(razdvoji_duplikate, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='collectionnotice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__gt', ''), ('year__isnull', False)), fields=('kind', 'year', 'number'), name='col_notice_broj_jedinstven'),
        ),
    ]
