# Generated by Django 5.0.9 on 2026-10-07 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nabavka', '0027_fiskalni_interni_broj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnjizenjeRacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('poslato', 'Čeka knjiženje'), ('vraceno', 'Vraćeno na doradu'), ('proknjizeno', 'Proknjiženo')], db_index=True, default='poslato', max_length=20, verbose_name='Status')),
                ('poslato_at', models.DateTimeField(blank=True, null=True, verbose_name='Poslato na knjiženje')),
                ('datum_knjizenja', models.DateField(blank=True, null=True, verbose_name='Datum knjiženja')),
                ('broj_naloga', models.CharField(blank=True, default='', max_length=50, verbose_name='Broj naloga za knjiženje')),
                ('napomena', models.CharField(blank=True, default='', max_length=500, verbose_name='Napomena knjiženja')),
                ('proknjizeno_at', models.DateTimeField(blank=True, null=True, verbose_name='Proknjiženo (upis)')),
                ('razlog_vracanja', models.CharField(blank=True, default='', max_length=500, verbose_name='Razlog vraćanja')),
                ('vraceno_at', models.DateTimeField(blank=True, null=True, verbose_name='Vraćeno na doradu')),
                ('knjizio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proknjižio')),
                ('poslao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Poslao na knjiženje')),
                ('racun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knjizenje', to='nabavka.fiskalniracun', verbose_name='Fiskalni račun')),
                ('vratio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vratio na doradu')),
            ],
            options={
                'verbose_name': 'Knjiženje računa',
                'verbose_name_plural': 'Knjiženja računa',
            },
        ),
        migrations.CreateModel(
            name='DogadjajKnjizenja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('poslato', 'Poslato na knjiženje'), ('vraceno', 'Vraćeno na doradu'), ('proknjizeno', 'Proknjiženo'), ('ponisteno', 'Poništeno knjiženje')], max_length=20, verbose_name='Vrsta')),
                ('vreme', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vreme')),
                ('napomena', models.CharField(blank=True, default='', max_length=500, verbose_name='Napomena')),
                ('korisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
                ('knjizenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogadjaji', to='knjizenje.knjizenjeracuna', verbose_name='Knjiženje')),
            ],
            options={
                'verbose_name': 'Događaj knjiženja',
                'verbose_name_plural': 'Događaji knjiženja',
                'ordering': ['-vreme', '-pk'],
            },
        ),
    ]
