# Generated by Django 5.0.9 on 2026-10-08 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knjizenje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knjizenjeracuna',
            name='broj_stampanja',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Broj štampanja'),
        ),
        migrations.AddField(
            model_name='knjizenjeracuna',
            name='stampano_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Poslednja štampa'),
        ),
        migrations.AddField(
            model_name='knjizenjeracuna',
            name='stampao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Poslednji štampao'),
        ),
        migrations.AlterField(
            model_name='dogadjajknjizenja',
            name='vrsta',
            field=models.CharField(choices=[('poslato', 'Poslato na knjiženje'), ('vraceno', 'Vraćeno na doradu'), ('proknjizeno', 'Proknjiženo'), ('ponisteno', 'Poništeno knjiženje'), ('stampano', 'Odštampano')], max_length=20, verbose_name='Vrsta'),
        ),
    ]
