# Generated by Django 5.0.9 on 2026-07-10 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0064_employee_skip_hr_identity_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Godina')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mesec')),
                ('status', models.CharField(choices=[('draft', 'Popunjava se'), ('submitted', 'Predato'), ('approved', 'Odobreno')], default='draft', max_length=20, verbose_name='Status')),
                ('meal_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Topli obrok - broj dana')),
                ('field_allowance_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Terenski dodatak - broj dana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_time_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_time_sheets', to='fleet.employee', verbose_name='Zaposleni')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_work_time_sheets', to=settings.AUTH_USER_MODEL, verbose_name='Azurirao')),
            ],
            options={
                'verbose_name': 'Radna lista',
                'verbose_name_plural': 'Radne liste',
                'ordering': ['-year', '-month', 'employee__last_name', 'employee__first_name'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkTimeSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(verbose_name='R.b.')),
                ('day_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_11', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_12', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_13', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_14', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_15', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_16', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_17', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_18', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_19', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_20', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_21', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_22', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_23', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_24', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_25', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_26', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_27', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_28', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_29', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_30', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day_31', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('work_conditions', models.CharField(blank=True, max_length=100, verbose_name='Uslovi rada')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Napomena')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_time_sheet_lines', to='fleet.organizationalunit', verbose_name='Sifra posla')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.worktimesheet', verbose_name='Radna lista')),
            ],
            options={
                'verbose_name': 'Red radne liste',
                'verbose_name_plural': 'Redovi radne liste',
                'ordering': ['line_number'],
                'unique_together': {('sheet', 'line_number')},
            },
        ),
    ]
