# Generated by Django 5.0.9 on 2026-07-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0064_employee_skip_hr_identity_update'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimesheet',
            name='meal_organizational_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_work_time_sheets', to='fleet.organizationalunit', verbose_name='Topli obrok - sifra posla'),
        ),
    ]
