# Generated by Django 5.0.9 on 2026-09-11 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0075_vehicle_photo'),
        ('hr', '0003_integer_work_time_sheet_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeaveImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='RFZO datoteka')),
                ('file_hash', models.CharField(max_length=64)),
                ('source_date', models.DateField(verbose_name='Datum RFZO izvoza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('unlinked_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leave_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uvoz bolovanja',
                'verbose_name_plural': 'Uvozi bolovanja',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfzo_id', models.CharField(max_length=64, unique=True, verbose_name='RFZO ID')),
                ('personal_number', models.CharField(max_length=13, verbose_name='JMBG iz izvora')),
                ('start_date', models.DateField(db_index=True, verbose_name='Početak bolovanja')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Završetak bolovanja')),
                ('source_status', models.CharField(max_length=50, verbose_name='Status RFZO')),
                ('source_total_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukupno dana RFZO')),
                ('source_date', models.DateField(verbose_name='Datum RFZO izvoza')),
                ('matching_note', models.CharField(blank=True, max_length=100, verbose_name='Povezivanje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leaves', to='fleet.employee', verbose_name='Zaposleni')),
                ('last_import', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leaves', to='hr.sickleaveimport')),
            ],
            options={
                'verbose_name': 'Bolovanje',
                'verbose_name_plural': 'Bolovanja',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='sickleave',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hr_sick_leave_valid_period'),
        ),
    ]
