# Generated by Django 5.0.9 on 2026-09-11 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_sick_leave_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Šifra primaoca')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv vrste primaoca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
            ],
            options={
                'verbose_name': 'Vrsta primaoca',
                'verbose_name_plural': 'Vrste primalaca',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Oznaka')),
                ('name', models.CharField(max_length=100, verbose_name='Napomena za radnu listu')),
                ('employee_selectable', models.BooleanField(default=True, verbose_name='Zaposleni bira u radnoj listi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Redosled')),
            ],
            options={
                'verbose_name': 'Vrsta rada / odsustva',
                'verbose_name_plural': 'Vrste rada / odsustva',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='worktimesheetline',
            name='work_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheet_lines', to='hr.worktimecategory', verbose_name='Vrsta rada / odsustva'),
        ),
        migrations.CreateModel(
            name='WorkTimeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_code', models.PositiveIntegerField(verbose_name='Šifra elementa (elsif)')),
                ('payroll_name', models.CharField(max_length=255, verbose_name='Naziv elementa (elnaz)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='hr.worktimecategory', verbose_name='Napomena za radnu listu')),
                ('recipient_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='hr.recipienttype', verbose_name='Vrsta primaoca')),
            ],
            options={
                'verbose_name': 'Element radne liste',
                'verbose_name_plural': 'Elementi radne liste',
                'ordering': ['recipient_type__code', 'payroll_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='worktimeelement',
            constraint=models.UniqueConstraint(fields=('recipient_type', 'payroll_code'), name='hr_unique_recipient_payroll_element'),
        ),
    ]
