# Generated by Django 5.0.9 on 2026-09-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0076_employee_recipient_code_employee_recipient_name'),
        ('hr', '0007_work_time_catalog_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeaveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('counts', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_leave_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinhronizacija godišnjih odmora',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaveDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina prava')),
                ('employee_code', models.IntegerField(verbose_name='Šifra zaposlenog u izvoru')),
                ('source_present', models.BooleanField(default=True, verbose_name='Prisutan u izvoru')),
                ('last_seen_at', models.DateTimeField()),
                ('source_start_key', models.CharField(max_length=26)),
                ('start_date', models.DateField(verbose_name='Od')),
                ('end_date', models.DateField(verbose_name='Do')),
                ('approved_days', models.PositiveIntegerField(verbose_name='Dana po rešenju')),
                ('source_comment', models.CharField(blank=True, max_length=255, verbose_name='Komentar iz rešenja')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.employee')),
                ('last_sync', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.annualleavesync')),
            ],
            options={
                'verbose_name': 'Rešenje godišnjeg odmora',
                'verbose_name_plural': 'Rešenja godišnjeg odmora',
                'ordering': ['-year', '-start_date', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaveAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.PositiveIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina prava')),
                ('employee_code', models.IntegerField(verbose_name='Šifra zaposlenog u izvoru')),
                ('source_present', models.BooleanField(default=True, verbose_name='Prisutan u izvoru')),
                ('last_seen_at', models.DateTimeField()),
                ('source_employee_name', models.CharField(blank=True, max_length=255)),
                ('allocated_days', models.PositiveIntegerField(verbose_name='Dodeljeno dana')),
                ('source_day_1', models.IntegerField(blank=True, null=True)),
                ('source_day_2', models.IntegerField(blank=True, null=True)),
                ('source_day_3', models.IntegerField(blank=True, null=True)),
                ('source_day_4', models.IntegerField(blank=True, null=True)),
                ('source_day_5', models.IntegerField(blank=True, null=True)),
                ('source_day_6', models.IntegerField(blank=True, null=True)),
                ('source_other', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.employee')),
                ('last_sync', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.annualleavesync')),
            ],
            options={
                'verbose_name': 'Dodela godišnjeg odmora',
                'verbose_name_plural': 'Dodele godišnjeg odmora',
                'ordering': ['-year', 'employee_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='annualleavedecision',
            constraint=models.UniqueConstraint(fields=('company_code', 'year', 'employee_code', 'source_start_key'), name='hr_annual_decision_source_key'),
        ),
        migrations.AddConstraint(
            model_name='annualleavedecision',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='hr_annual_decision_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='annualleaveallowance',
            constraint=models.UniqueConstraint(fields=('company_code', 'year', 'employee_code'), name='hr_annual_allowance_source_key'),
        ),
    ]
