# Generated by Django 5.0.9 on 2026-09-11 12:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0076_employee_recipient_code_employee_recipient_name'),
        ('hr', '0009_annual_leave_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Šifra merila')),
                ('name', models.CharField(max_length=500, verbose_name='Naziv merila (ćirilica)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Redosled')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Oznaka')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv grupe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('revision', models.PositiveIntegerField(default=1)),
                ('unit_code', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('stimulation', models.DecimalField(decimal_places=5, max_digits=10)),
                ('personal_coefficient', models.DecimalField(decimal_places=5, max_digits=10)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_evaluations', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='fleet.employee')),
                ('general_director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee')),
                ('source_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='hr.employeeevaluation')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('supervisor', 'Непосредни руководилац'), ('director', 'Директор центра'), ('general_director', 'Генерални директор')], max_length=20)),
                ('actor_name', models.CharField(max_length=255)),
                ('document_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coefficient', models.DecimalField(decimal_places=5, max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_approvals', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='hr.employeeevaluation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationEmployeeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_setup', to='fleet.employee', verbose_name='Zaposleni')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.evaluationgroup', verbose_name='Grupa za ocenjivanje')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Bodovi (0–4)')),
                ('coefficient', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Koeficijent stimulacije')),
                ('description', models.TextField(blank=True, verbose_name='Opis osnove bodovanja (ćirilica)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scales', to='hr.evaluationcriterion', verbose_name='Merilo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scales', to='hr.evaluationgroup', verbose_name='Grupa')),
            ],
            options={
                'ordering': ['group__name', 'criterion__sort_order', '-points'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationUnitSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20, unique=True, verbose_name='Šifra OJ iz kadrovske evidencije')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee', verbose_name='Direktor centra')),
                ('general_director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee', verbose_name='Generalni direktor')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.employee', verbose_name='Neposredni rukovodilac')),
            ],
            options={
                'ordering': ['unit_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeevaluation',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month', 'revision'), name='hr_evaluation_revision_key'),
        ),
        migrations.AddConstraint(
            model_name='employeeevaluation',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1), ('month__lte', 12)), name='hr_evaluation_valid_month'),
        ),
        migrations.AddConstraint(
            model_name='evaluationapproval',
            constraint=models.UniqueConstraint(fields=('evaluation', 'stage'), name='hr_evaluation_approval_key'),
        ),
        migrations.AddConstraint(
            model_name='evaluationscale',
            constraint=models.UniqueConstraint(fields=('group', 'criterion', 'points'), name='hr_evaluation_scale_key'),
        ),
    ]
