# Generated by Django 5.0.9 on 2026-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_evaluation_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationapproval',
            name='stage',
            field=models.CharField(choices=[('supervisor', 'Neposredni rukovodilac'), ('director', 'Direktor centra'), ('general_director', 'Generalni direktor')], max_length=20),
        ),
    ]
