# Generated by Django 5.0.9 on 2026-09-23 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0080_employee_full_name_cyrillic'),
        ('hr', '0012_alter_evaluationapproval_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VrstaResenja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=40, unique=True, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=120, verbose_name='Naziv vrste (za listu)')),
                ('naslov', models.CharField(default='РЕШЕЊЕ', max_length=120, verbose_name='Naslov (ćirilica)')),
                ('podnaslov', models.CharField(blank=True, max_length=255, verbose_name='Podnaslov (ćirilica)')),
                ('pravni_osnov', models.TextField(verbose_name='Pravni osnov (ćirilica)')),
                ('dispozitiv', models.TextField(help_text='Svaka tačka u svom redu. Čuvari mesta: {zaposleni}, {oj}, {radno_mesto}, {centar}, {period}, {dani}, {dani_vikend}, {dani_drzavni}, {dani_verski}, {radni_dani}, {datum_povratka}. Oblik po polu: {rod:дужан|дужна}. Uslovni deo: [[dani_verski| и {dani_verski} на дан верског празника]].', verbose_name='Dispozitiv (ćirilica)')),
                ('obrazlozenje', models.TextField(blank=True, help_text='Čuvari mesta: {zahtev_broj}, {zahtev_datum}, {napomena}.', verbose_name='Obrazloženje (ćirilica)')),
                ('pravna_pouka', models.TextField(blank=True, verbose_name='Pravna pouka (ćirilica)')),
                ('dostavljeno', models.TextField(blank=True, help_text='Svaka stavka u svom redu. Čuvar mesta {centar} daje šifru centra zaposlenog.', verbose_name='Dostavljeno (ćirilica)')),
                ('trazi_period', models.BooleanField(default=False, verbose_name='Traži period od–do')),
                ('trazi_dane', models.BooleanField(default=False, verbose_name='Traži pojedinačne dane')),
                ('trazi_radne_dane', models.BooleanField(default=False, verbose_name='Traži broj radnih dana i povratak')),
                ('podrazumevano_pismo', models.CharField(choices=[('cirilica', 'Ćirilica'), ('latinica', 'Latinica')], default='cirilica', max_length=10, verbose_name='Podrazumevano pismo')),
                ('redosled', models.PositiveSmallIntegerField(default=0, verbose_name='Redosled')),
                ('je_aktivna', models.BooleanField(default=True, verbose_name='Aktivna')),
            ],
            options={
                'verbose_name': 'Vrsta rešenja',
                'verbose_name_plural': 'Vrste rešenja',
                'ordering': ['redosled', 'naziv'],
            },
        ),
        migrations.CreateModel(
            name='Potpisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkcija', models.CharField(default='Генерални директор', max_length=120, verbose_name='Funkcija (ćirilica)')),
                ('ime_cirilica', models.CharField(blank=True, help_text='Npr. „др Драган Бојовић, дипл.инж.“. Ostavi prazno za automatsko preslovljavanje.', max_length=150, verbose_name='Ime u potpisu (ćirilica)')),
                ('vazi_od', models.DateField(verbose_name='Važi od')),
                ('vazi_do', models.DateField(blank=True, null=True, verbose_name='Važi do (isključivo)')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potpisi_resenja', to='fleet.employee', verbose_name='Zaposleni')),
            ],
            options={
                'verbose_name': 'Potpisnik rešenja',
                'verbose_name_plural': 'Potpisnici rešenja',
                'ordering': ['-vazi_od', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Resenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(help_text='Prepisuje se iz delovodnika, npr. 43-15238.', max_length=40, verbose_name='Broj rešenja')),
                ('datum_resenja', models.DateField(verbose_name='Datum rešenja')),
                ('pismo', models.CharField(choices=[('cirilica', 'Ćirilica'), ('latinica', 'Latinica')], default='cirilica', max_length=10, verbose_name='Pismo')),
                ('zaposleni_tekst', models.CharField(help_text='Popunjava se automatski; ispravi ručno kada je potreban drugi padež.', max_length=200, verbose_name='Zaposleni u tekstu rešenja')),
                ('oj_naziv', models.CharField(blank=True, max_length=200, verbose_name='Organizaciona jedinica u tekstu')),
                ('radno_mesto', models.CharField(blank=True, max_length=200, verbose_name='Radno mesto u tekstu')),
                ('oj_kod', models.CharField(blank=True, max_length=20, verbose_name='Šifra OJ')),
                ('centar', models.CharField(blank=True, max_length=10, verbose_name='Šifra centra')),
                ('datum_od', models.DateField(blank=True, null=True, verbose_name='Period od')),
                ('datum_do', models.DateField(blank=True, null=True, verbose_name='Period do')),
                ('do_zavrsetka_posla', models.BooleanField(default=False, verbose_name='Do završetka posla')),
                ('broj_radnih_dana', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Broj radnih dana')),
                ('datum_povratka', models.DateField(blank=True, null=True, verbose_name='Datum javljanja na posao')),
                ('zahtev_broj', models.CharField(blank=True, max_length=40, verbose_name='Broj zahteva')),
                ('zahtev_datum', models.DateField(blank=True, null=True, verbose_name='Datum zahteva')),
                ('napomena', models.TextField(blank=True, verbose_name='Napomena uz obrazloženje')),
                ('status', models.CharField(choices=[('nacrt', 'Nacrt'), ('izdato', 'Izdato'), ('stornirano', 'Stornirano')], default='nacrt', max_length=15, verbose_name='Status')),
                ('dokument', models.JSONField(blank=True, null=True, verbose_name='Snimak dokumenta')),
                ('izdato_at', models.DateTimeField(blank=True, null=True, verbose_name='Izdato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='izdata_resenja', to=settings.AUTH_USER_MODEL)),
                ('potpisnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resenja', to='hr.potpisnik', verbose_name='Potpisnik')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resenja', to='fleet.employee', verbose_name='Zaposleni')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resenja', to='hr.vrstaresenja', verbose_name='Vrsta rešenja')),
            ],
            options={
                'verbose_name': 'Rešenje',
                'verbose_name_plural': 'Rešenja',
                'ordering': ['-datum_resenja', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResenjeDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrsta_dana', models.CharField(choices=[('prekovremeni', 'Prekovremeni rad'), ('nocni', 'Noćni rad'), ('vikend', 'Rad vikendom'), ('drzavni', 'Državni praznik'), ('verski', 'Verski praznik'), ('odsustvo', 'Plaćeno odsustvo')], default='prekovremeni', max_length=15, verbose_name='Vrsta dana')),
                ('resenje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dani', to='hr.resenje', verbose_name='Rešenje')),
            ],
            options={
                'verbose_name': 'Dan rešenja',
                'verbose_name_plural': 'Dani rešenja',
                'ordering': ['datum', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='resenjedan',
            constraint=models.UniqueConstraint(fields=('resenje', 'datum', 'vrsta_dana'), name='hr_resenje_dan_key'),
        ),
        migrations.AddConstraint(
            model_name='resenje',
            constraint=models.UniqueConstraint(fields=('broj', 'datum_resenja'), name='hr_resenje_broj_datum'),
        ),
        migrations.AddConstraint(
            model_name='resenje',
            constraint=models.CheckConstraint(check=models.Q(('datum_do__isnull', True), ('datum_od__isnull', True), ('datum_do__gte', models.F('datum_od')), _connector='OR'), name='hr_resenje_period'),
        ),
    ]
