# Generated by Django 5.0.9 on 2026-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_resenja_sifrarnik_i_dozvole'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenje',
            name='pol',
            field=models.CharField(blank=True, choices=[('M', 'Muški'), ('F', 'Ženski')], max_length=1, verbose_name='Pol za tekst rešenja'),
        ),
        migrations.AddField(
            model_name='resenje',
            name='vreme_do',
            field=models.TimeField(blank=True, null=True, verbose_name='Vreme rada do'),
        ),
        migrations.AddField(
            model_name='resenje',
            name='vreme_od',
            field=models.TimeField(blank=True, null=True, verbose_name='Vreme rada od'),
        ),
        migrations.AlterField(
            model_name='resenje',
            name='zahtev_broj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zahtev (broj ili opis)'),
        ),
    ]
