# Generated by Django 5.0.9 on 2026-09-24 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0081_customuser_allowed_hr_unit_codes'),
        ('hr', '0015_resenje_pol_resenje_vreme_do_resenje_vreme_od_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrojacZahteva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.PositiveSmallIntegerField(unique=True, verbose_name='Godina')),
                ('poslednji_broj', models.PositiveIntegerField(default=0, verbose_name='Poslednji dodeljeni broj')),
            ],
            options={
                'verbose_name': 'Brojač zahteva',
                'verbose_name_plural': 'Brojači zahteva',
                'ordering': ['-godina'],
            },
        ),
        migrations.AddField(
            model_name='resenje',
            name='dodatni_podaci',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dodatni podaci'),
        ),
        migrations.AddField(
            model_name='resenje',
            name='podbroj',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Podbroj zahteva'),
        ),
        migrations.AddField(
            model_name='vrstaresenja',
            name='dodatna_polja',
            field=models.TextField(blank=True, help_text='Svako polje u svom redu, u obliku oznaka|Naziv polja (npr. poslovi|Poslovi koje preuzima). U tekstu se koristi kao {oznaka}.', verbose_name='Dodatna polja'),
        ),
        migrations.AlterField(
            model_name='resenje',
            name='broj',
            field=models.CharField(help_text='Rešenje po zahtevu dobija broj automatski, kao podbroj zahteva (npr. 43-17/1). Za rešenje bez zahteva broj se unosi ručno.', max_length=40, verbose_name='Broj rešenja'),
        ),
        migrations.AlterField(
            model_name='vrstaresenja',
            name='obrazlozenje',
            field=models.TextField(blank=True, help_text='Čuvari mesta: {zahtev_broj}, {zahtev_datum}, {razlog_zahteva}, {podnosilac}, {podnosilac_funkcija}, {napomena} i dodatna polja.', verbose_name='Obrazloženje (ćirilica)'),
        ),
        migrations.CreateModel(
            name='VrstaZahteva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=40, unique=True, verbose_name='Oznaka')),
                ('naziv', models.CharField(max_length=120, verbose_name='Naziv vrste (za listu)')),
                ('predmet', models.CharField(max_length=255, verbose_name='Predmet (ćirilica)')),
                ('tekst', models.TextField(help_text='Svaki pasus u svom redu. Čuvari mesta kao kod rešenja, uz {razlog}, {podnosilac}, {podnosilac_funkcija}, {odobrava}, {odobrava_funkcija} i dodatna polja.', verbose_name='Tekst zahteva (ćirilica)')),
                ('trazi_period', models.BooleanField(default=False, verbose_name='Traži period od–do')),
                ('trazi_dane', models.BooleanField(default=False, verbose_name='Traži pojedinačne dane')),
                ('trazi_radne_dane', models.BooleanField(default=False, verbose_name='Traži broj radnih dana i povratak')),
                ('dodatna_polja', models.TextField(blank=True, help_text='Svako polje u svom redu, u obliku oznaka|Naziv polja (npr. poslovi|Poslovi koje preuzima). U tekstu se koristi kao {oznaka}.', verbose_name='Dodatna polja')),
                ('podrazumevano_pismo', models.CharField(choices=[('cirilica', 'Ćirilica'), ('latinica', 'Latinica')], default='cirilica', max_length=10, verbose_name='Podrazumevano pismo')),
                ('redosled', models.PositiveSmallIntegerField(default=0, verbose_name='Redosled')),
                ('je_aktivna', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('vrsta_resenja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vrste_zahteva', to='hr.vrstaresenja', verbose_name='Rešenje koje se izdaje po zahtevu')),
            ],
            options={
                'verbose_name': 'Vrsta zahteva',
                'verbose_name_plural': 'Vrste zahteva',
                'ordering': ['redosled', 'naziv'],
            },
        ),
        migrations.CreateModel(
            name='Zahtev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('redni_broj', models.PositiveIntegerField(verbose_name='Redni broj')),
                ('broj', models.CharField(help_text='Jedinstven u godini, kao u delovodniku: redni broj počinje od 1 svake godine.', max_length=40, verbose_name='Broj zahteva')),
                ('datum_zahteva', models.DateField(verbose_name='Datum zahteva')),
                ('pismo', models.CharField(choices=[('cirilica', 'Ćirilica'), ('latinica', 'Latinica')], default='cirilica', max_length=10, verbose_name='Pismo')),
                ('pol', models.CharField(blank=True, choices=[('M', 'Muški'), ('F', 'Ženski')], max_length=1, verbose_name='Pol za tekst zahteva')),
                ('zaposleni_tekst', models.CharField(help_text='Popunjava se automatski; ispravi ručno kada je potreban drugi padež.', max_length=200, verbose_name='Zaposleni u tekstu zahteva')),
                ('oj_naziv', models.CharField(blank=True, max_length=200, verbose_name='Organizaciona jedinica u tekstu')),
                ('radno_mesto', models.CharField(blank=True, max_length=200, verbose_name='Radno mesto u tekstu')),
                ('oj_kod', models.CharField(blank=True, max_length=20, verbose_name='Šifra OJ')),
                ('centar', models.CharField(blank=True, max_length=10, verbose_name='Šifra centra')),
                ('datum_od', models.DateField(blank=True, null=True, verbose_name='Period od')),
                ('datum_do', models.DateField(blank=True, null=True, verbose_name='Period do')),
                ('vreme_od', models.TimeField(blank=True, null=True, verbose_name='Vreme rada od')),
                ('vreme_do', models.TimeField(blank=True, null=True, verbose_name='Vreme rada do')),
                ('do_zavrsetka_posla', models.BooleanField(default=False, verbose_name='Do završetka posla')),
                ('broj_radnih_dana', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Broj radnih dana')),
                ('datum_povratka', models.DateField(blank=True, null=True, verbose_name='Datum javljanja na posao')),
                ('razlog', models.TextField(blank=True, help_text='Npr. „потребе за радом већим од четрдесет сати недељно“. Ulazi u tekst zahteva i rešenja.', verbose_name='Razlog zahteva')),
                ('dodatni_podaci', models.JSONField(blank=True, default=dict, verbose_name='Dodatni podaci')),
                ('podnosilac_funkcija', models.CharField(blank=True, help_text='Npr. „Финансијски директор“, „Директор центра“.', max_length=120, verbose_name='Funkcija podnosioca')),
                ('odobrava_funkcija', models.CharField(blank=True, default='Генерални директор', max_length=120, verbose_name='Funkcija onoga ko odobrava')),
                ('napomena', models.TextField(blank=True, verbose_name='Interna napomena')),
                ('status', models.CharField(choices=[('nacrt', 'Nacrt'), ('podnet', 'Podnet'), ('storniran', 'Storniran')], default='nacrt', max_length=15, verbose_name='Status')),
                ('dokument', models.JSONField(blank=True, null=True, verbose_name='Snimak dokumenta')),
                ('podneto_at', models.DateTimeField(blank=True, null=True, verbose_name='Podneto')),
                ('poslednji_podbroj', models.PositiveSmallIntegerField(default=0, verbose_name='Poslednji podbroj rešenja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uneti_zahtevi', to=settings.AUTH_USER_MODEL)),
                ('odobrava', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zahtevi_za_odobrenje', to='fleet.employee', verbose_name='Ko odobrava zahtev')),
                ('podnosilac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='podneti_zahtevi', to='fleet.employee', verbose_name='Ko podnosi zahtev')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zahtevi', to='hr.vrstazahteva', verbose_name='Vrsta zahteva')),
                ('zaposleni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zahtevi', to='fleet.employee', verbose_name='Zaposleni')),
            ],
            options={
                'verbose_name': 'Zahtev',
                'verbose_name_plural': 'Zahtevi',
                'ordering': ['-datum_zahteva', '-redni_broj'],
            },
        ),
        migrations.AddField(
            model_name='resenje',
            name='zahtev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resenja', to='hr.zahtev', verbose_name='Zahtev'),
        ),
        migrations.CreateModel(
            name='ZahtevDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('vrsta_dana', models.CharField(choices=[('prekovremeni', 'Prekovremeni rad'), ('nocni', 'Noćni rad'), ('vikend', 'Rad vikendom'), ('drzavni', 'Državni praznik'), ('verski', 'Verski praznik'), ('odsustvo', 'Plaćeno odsustvo')], default='prekovremeni', max_length=15, verbose_name='Vrsta dana')),
                ('zahtev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dani', to='hr.zahtev', verbose_name='Zahtev')),
            ],
            options={
                'verbose_name': 'Dan zahteva',
                'verbose_name_plural': 'Dani zahteva',
                'ordering': ['datum', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='zahtev',
            constraint=models.UniqueConstraint(fields=('godina', 'redni_broj'), name='hr_zahtev_godina_redni_broj'),
        ),
        migrations.AddConstraint(
            model_name='zahtev',
            constraint=models.UniqueConstraint(fields=('godina', 'broj'), name='hr_zahtev_godina_broj'),
        ),
        migrations.AddConstraint(
            model_name='zahtev',
            constraint=models.CheckConstraint(check=models.Q(('datum_do__isnull', True), ('datum_od__isnull', True), ('datum_do__gte', models.F('datum_od')), _connector='OR'), name='hr_zahtev_period'),
        ),
        migrations.AddConstraint(
            model_name='zahtevdan',
            constraint=models.UniqueConstraint(fields=('zahtev', 'datum', 'vrsta_dana'), name='hr_zahtev_dan_key'),
        ),
    ]
