# Generated by Django 5.0.9 on 2026-09-29 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0087_zaposleni_u_registru'),
        ('hr', '0018_resenje_obavezan_jedinstven_zahtev'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UgovoriSinhronizacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counts', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_ugovori_sinhronizacije', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinhronizacija ugovora zaposlenih',
                'db_table': 'hr_ugovori_sinhronizacija',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='UgovorZaposlenog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.IntegerField(verbose_name='Šifra radnika')),
                ('redni_broj', models.IntegerField(verbose_name='Redni broj perioda')),
                ('ime_prezime', models.CharField(blank=True, default='', max_length=150, verbose_name='Ime i prezime (kadrovska baza)')),
                ('kategorija', models.CharField(choices=[('radni_odnos', 'Radni odnos'), ('van_radnog_odnosa', 'Van radnog odnosa')], db_index=True, default='radni_odnos', max_length=20, verbose_name='Kategorija')),
                ('datum_od', models.DateField(verbose_name='Od')),
                ('datum_do', models.DateField(blank=True, null=True, verbose_name='Do')),
                ('na_neodredjeno', models.BooleanField(default=False, verbose_name='Na neodređeno')),
                ('opis', models.CharField(blank=True, default='', max_length=255, verbose_name='Opis iz kadrovske baze')),
                ('staz_godina', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('staz_meseci', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('staz_dana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('u_izvoru', models.BooleanField(db_index=True, default=True, verbose_name='Postoji u kadrovskoj bazi')),
                ('radnik_aktivan', models.BooleanField(db_index=True, default=False, verbose_name='Radnik aktivan')),
                ('prethodni_datum_od', models.DateField(blank=True, null=True, verbose_name='Raniji datum početka')),
                ('sinhronizovano', models.DateTimeField(blank=True, null=True)),
                ('oj', models.CharField(blank=True, default='', max_length=20, verbose_name='OJ')),
                ('naziv_oj', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv OJ')),
                ('sifra_sistematizacije', models.CharField(blank=True, default='', max_length=20, verbose_name='Šifra po sistematizaciji')),
                ('naziv_radnog_mesta', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv radnog mesta')),
                ('podaci_poreklo', models.CharField(blank=True, choices=[('sinhronizacija', 'Iz kadrovske baze'), ('rucno', 'Uneto ručno')], default='', max_length=20, verbose_name='Poreklo OJ i radnog mesta')),
                ('podaci_zabelezeni', models.DateField(blank=True, null=True, verbose_name='OJ i radno mesto zabeleženi')),
                ('broj_ugovora', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Broj ugovora')),
                ('broj_aneksa', models.CharField(blank=True, default='', max_length=100, verbose_name='Broj aneksa')),
                ('dokument', models.FileField(blank=True, max_length=255, upload_to='hr/ugovori/%Y/%m/', verbose_name='Skeniran dokument')),
                ('dokument_naziv', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv fajla')),
                ('napomena', models.TextField(blank=True, default='', verbose_name='Napomena')),
                ('izmenjeno', models.DateTimeField(blank=True, null=True, verbose_name='Izmenjeno')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ugovori', to='fleet.employee', verbose_name='Zaposleni')),
                ('glavni_ugovor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aneksi', to='hr.ugovorzaposlenog', verbose_name='Glavni ugovor')),
                ('izmenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_ugovori_izmenjeni', to=settings.AUTH_USER_MODEL, verbose_name='Izmenio')),
            ],
            options={
                'verbose_name': 'Ugovor zaposlenog',
                'verbose_name_plural': 'Ugovori zaposlenih',
                'db_table': 'hr_ugovor_zaposlenog',
                'ordering': ['employee_code', 'redni_broj'],
                'indexes': [models.Index(fields=['employee_code', 'datum_od'], name='hr_ugovor_z_employe_9a2a2e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ugovorzaposlenog',
            constraint=models.UniqueConstraint(fields=('employee_code', 'redni_broj'), name='hr_ugovor_izvor_kljuc'),
        ),
    ]
