# Generated by Django 5.0.9 on 2026-10-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_ugovor_datum_ugovora'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatnoRadnoMesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj', models.CharField(blank=True, default='', max_length=20, verbose_name='OJ')),
                ('naziv_oj', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv OJ')),
                ('sifra_sistematizacije', models.CharField(blank=True, default='', max_length=20, verbose_name='Šifra po sistematizaciji')),
                ('naziv_radnog_mesta', models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv radnog mesta')),
                ('ugovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatna_radna_mesta', to='hr.ugovorzaposlenog', verbose_name='Ugovor')),
            ],
            options={
                'verbose_name': 'Dodatno radno mesto',
                'verbose_name_plural': 'Dodatna radna mesta',
                'db_table': 'hr_ugovor_dodatno_radno_mesto',
                'ordering': ['ugovor', 'pk'],
            },
        ),
    ]
