# Generated by Django 5.0.9 on 2026-10-05 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0090_raspolaganje_iz_ugovora'),
        ('hr', '0022_zahtev_tekst_bez_ponavljanja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KomentarProlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('tekst', models.CharField(max_length=500, verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Upisano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Izmenjeno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Upisao')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentari_prolaza', to='fleet.employee', verbose_name='Zaposleni')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Izmenio')),
            ],
            options={
                'verbose_name': 'Komentar na prolaze',
                'verbose_name_plural': 'Komentari na prolaze',
                'ordering': ['datum'],
            },
        ),
        migrations.AddConstraint(
            model_name='komentarprolaza',
            constraint=models.UniqueConstraint(fields=('employee', 'datum'), name='hr_komentar_prolaza_jedan_po_danu'),
        ),
    ]
