# Generated by Django 5.0.9 on 2026-10-07 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_komentar_prolaza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadnaListaPrilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('propusnice', 'Skenirane propusnice'), ('finalna', 'Finalna (potpisana) radna lista'), ('ostalo', 'Ostalo')], default='propusnice', max_length=20, verbose_name='Vrsta')),
                ('fajl', models.FileField(max_length=255, upload_to='hr/radne_liste/%Y/%m/', verbose_name='Dokument')),
                ('naziv', models.CharField(max_length=255, verbose_name='Naziv fajla')),
                ('velicina', models.PositiveIntegerField(default=0)),
                ('napomena', models.CharField(blank=True, max_length=255, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodato')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dodao')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prilozi', to='hr.worktimesheet', verbose_name='Radna lista')),
            ],
            options={
                'verbose_name': 'Prilog radne liste',
                'verbose_name_plural': 'Prilozi radne liste',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
