# Generated by Django 5.0.9 on 2026-10-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_radna_lista_prilozi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenje',
            name='zahtev_broj_arhiva',
            field=models.CharField(blank=True, max_length=60, verbose_name='Broj zahteva iz arhive'),
        ),
        migrations.AlterField(
            model_name='vrstaresenja',
            name='obrazlozenje',
            field=models.TextField(blank=True, help_text='Čuvari mesta: {zahtev_broj}, {zahtev_broj_arhiva}, {zahtev_datum}, {razlog_zahteva}, {podnosilac}, {podnosilac_funkcija}, {napomena} i dodatna polja.', verbose_name='Obrazloženje (ćirilica)'),
        ),
    ]
