# Generated by Django 5.0.9 on 2026-10-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_resenje_broj_zahteva_arhiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ugovorzaposlenog',
            name='delovodni_broj',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Delovodni broj — broj'),
        ),
        migrations.AddField(
            model_name='ugovorzaposlenog',
            name='delovodni_godina',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Delovodni broj — godina'),
        ),
        migrations.AddField(
            model_name='ugovorzaposlenog',
            name='delovodni_upisano',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delovodni broj upisan'),
        ),
        migrations.AddField(
            model_name='ugovorzaposlenog',
            name='delovodni_upisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Delovodni broj upisao'),
        ),
    ]
