# Generated by Django 5.0.9 on 2026-10-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_ugovor_delovodni_broj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugovorzaposlenog',
            name='delovodni_broj',
        ),
        migrations.RemoveField(
            model_name='ugovorzaposlenog',
            name='delovodni_godina',
        ),
        migrations.RemoveField(
            model_name='ugovorzaposlenog',
            name='delovodni_upisano',
        ),
        migrations.RemoveField(
            model_name='ugovorzaposlenog',
            name='delovodni_upisao',
        ),
    ]
