# Generated by Django 5.0.9 on 2026-10-09 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_ukloni_delovodni_ugovor_zaposlenog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimesheet',
            name='odobreno_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odobreno'),
        ),
        migrations.AddField(
            model_name='worktimesheet',
            name='odobrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Odobrio'),
        ),
    ]
