"""Pregledi iz poslovnih menija koji mogu da se otvore bez izbora konkretnog zapisa.

Namenski spisak: ne nuditi automatski akcije, izvoze i rute koje traže ID.
Tuple: ruta, naziv za korisnika, argumenti, stvarni kod dozvole view-a.
"""

EKRANI = {'fleet': [('dashboard', 'Pregled', {}, 'dashboard'),
           ('vehicle_list', 'Spisak vozila', {}, 'vehicle_list'),
           ('fleet_analytics', 'Analitika', {}, 'fleet_analytics'),
           ('trafficcard_list', 'Saobraćajne dozvole', {}, 'trafficcard_list'),
           ('putninalog_list', 'Putni nalozi', {}, 'putninalog_list'),
           ('vehicle_travel_order_list', 'Zaduženja vozila', {}, 'vehicle_travel_order_list'),
           ('kvar_list', 'Garaža IMS', {}, 'kvar_list'),
           ('incident_list', 'Incidenti', {}, 'incident_list'),
           ('reports_index', 'Izveštaji', {}, 'reports_index'),
           ('fleet_other', 'Ostalo', {}, 'fleet_other')],
 'kadrovi': [('hr:pregled', 'Pregled', {}, 'hr:pregled'),
             ('employee_list', 'Spisak zaposlenih', {}, 'employee_list'),
             ('hr:annual_leave_list', 'Godišnji odmori', {}, 'hr:annual_leave_list'),
             ('hr:sick_leave_list', 'Bolovanja', {}, 'hr:sick_leave_list'),
             ('hr:sick_leave_import', 'Uvoz bolovanja', {}, 'hr:sick_leave_import'),
             ('hr:evaluation_list', 'Ocenjivanje zaposlenih', {}, 'hr:evaluation_list'),
             ('hr:zahtev_list', 'Zahtevi zaposlenih', {}, 'hr:zahtev_list'),
             ('hr:resenje_list', 'Rešenja zaposlenih', {}, 'hr:resenje_list'),
             ('hr:ugovor_list', 'Ugovori', {}, 'hr:ugovor_list'),
             ('hr:work_time_catalog', 'Elementi radne liste', {}, 'hr:work_time_catalog'),
             ('my_employee_profile', 'Moj profil', {}, 'my_employee_profile')],
 'nabavka': [('nabavka:dashboard', 'Kontrolna tabla', {}, 'nabavka:dashboard'),
             ('nabavka:case_list', 'Zahtevi za nabavku i uslugu', {}, 'nabavka:case_list'),
             ('nabavka:euf_invoice_list', 'Preuzete EUF', {}, 'nabavka:euf_invoice_list'),
             ('nabavka:euf_item_list', 'UF stavke', {}, 'nabavka:euf_invoice_list'),
             ('nabavka:goods_list', 'Roba', {}, 'nabavka:euf_invoice_list'),
             ('nabavka:fiskalni_list', 'Fiskalni računi', {}, 'nabavka:fiskalni_list'),
             ('nabavka:uf_sef_list', 'UF SEF', {}, 'nabavka:uf_sef_list'),
             ('nabavka:purchase_contract_list', 'Kupovni ugovori', {}, 'nabavka:purchase_contract_list'),
             ('nabavka:public_procurement_list', 'Javne nabavke', {}, 'nabavka:public_procurement_list'),
             ('nabavka:purchase_order_list', 'Narudžbenice', {}, 'nabavka:purchase_order_list'),
             ('nabavka:reports', 'Izveštaji', {}, 'nabavka:reports'),
             ('nabavka:alerts', 'Alarmi', {}, 'nabavka:alerts')],
 'isplate': [('isplate:neoporezive_isplate', 'Isplata neoporezovanih', {}, 'isplate:neoporezive_isplate'),
             ('isplate:putni_nalozi_pravdanje', 'Putni nalozi – pravdanje', {}, 'isplate:putni_nalozi_pravdanje'),
             ('isplate:fiskalni_putni_nalozi',
              'Putni nalozi – Fiskalni računi',
              {},
              'isplate:fiskalni_putni_nalozi'),
             ('isplate:converter', 'Konverter', {}, 'isplate:converter')],
 'pravna': [('pravna:cases_list', 'Tuženi', {'case_type': 'tuzeni'}, 'pravna:cases_list'),
            ('pravna:cases_list', 'Tužili', {'case_type': 'tuzili'}, 'pravna:cases_list'),
            ('pravna:cases_list', 'Stečaj', {'case_type': 'stecaj'}, 'pravna:cases_list'),
            ('pravna:cases_list', 'UPPR', {'case_type': 'uppr'}, 'pravna:cases_list'),
            ('pravna:disciplinski_lista', 'Disciplinski postupci', {}, 'pravna:disciplinski_lista')],
 'ugovori': [('ugovori:contract_list', 'Ugovori', {}, 'ugovori:contract_list'),
             ('ugovori:business_request_list', 'Zahtevi', {}, 'ugovori:business_request_list'),
             ('ugovori:offer_list', 'Ponude', {}, 'ugovori:offer_list'),
             ('ugovori:partner_list', 'Partneri', {}, 'ugovori:partner_list'),
             ('ugovori:contract_type_list', 'Tipovi ugovora', {}, 'ugovori:contract_type_list')],
 'menice': [('menice:menica_list', 'Izlazne menice', {'tip': 'izlazna'}, 'menice:menica_list'),
            ('menice:ulazna_menica_list', 'Ulazne menice', {}, 'menice:ulazna_menica_list')],
 'mobilni': [('mobilni:mobile_dashboard', 'Pregled', {}, 'mobilni:mobile_dashboard'),
             ('mobilni:mobile_assignment_list', 'Dodele', {}, 'mobilni:mobile_assignment_list'),
             ('mobilni:mobile_usage_list', 'Potrošnja', {}, 'mobilni:mobile_usage_list'),
             ('mobilni:mobile_package_list', 'Paketi', {}, 'mobilni:mobile_package_list'),
             ('mobilni:mobile_user_list', 'Korisnici', {}, 'mobilni:mobile_user_list'),
             ('mobilni:mobile_withholding_all', 'Obustave', {}, 'mobilni:mobile_withholding_all'),
             ('mobilni:mobile_parking_exemption_list',
              'Parking izuzeci',
              {},
              'mobilni:mobile_parking_exemption_list'),
             ('mobilni:mobile_import', 'Import', {}, 'mobilni:mobile_import')],
 'arhiva': [('arhiva:pisarnica', 'Pisarnica', {}, 'arhiva:pisarnica'),
            ('arhiva:delovodnik', 'Delovodnik', {}, 'arhiva:delovodnik'),
            ('arhiva:kategorije', 'Lista kategorija', {}, 'arhiva:kategorije')],
 'organizacija': [('organizacija:stablo', 'Stablo organizacije', {}, 'organizacija:stablo'),
                  ('organizacija:sema', 'Organizaciona šema', {}, 'organizacija:sema'),
                  ('organizacija:dodele', 'Dodele uloga', {}, 'organizacija:dodele')],
 'finansije': [('finansije:ledger', 'Knjiženja', {}, 'finansije:ledger'),
               ('finansije:bank_list', 'Banke', {}, 'finansije:bank_list'),
               ('finansije:sef_list', 'SEF fakture', {}, 'finansije:sef_list'),
               ('finansije:sync_status', 'Sinhronizacija', {}, 'finansije:sync_status')]}
