# Generated by Django 5.0.3 on 2024-07-17 09:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Šifra zaposlenog')),
                ('name', models.CharField(max_length=100, verbose_name='Ime i prezime')),
                ('position', models.CharField(max_length=100, verbose_name='Pozicija')),
                ('department_code', models.IntegerField(verbose_name='Šifra odeljenja')),
                ('gender', models.CharField(choices=[('M', 'Muški'), ('F', 'Ženski')], max_length=1, verbose_name='Pol')),
                ('date_of_birth', models.DateField(verbose_name='Datum rođenja')),
                ('date_of_joining', models.DateField(verbose_name='Datum zapošljavanja')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Broj telefona')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Naziv tipa servisa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=20, unique=True, verbose_name='Inventarni broj')),
                ('chassis_number', models.CharField(max_length=17, unique=True, verbose_name='Broj šasije')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year_of_manufacture', models.IntegerField(verbose_name='Godina proizvodnje')),
                ('first_registration_date', models.DateField(verbose_name='Datum prve registracije')),
                ('color', models.CharField(max_length=30, verbose_name='Boja')),
                ('number_of_axles', models.IntegerField(verbose_name='Broj osovina')),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Zapremina motora')),
                ('engine_number', models.CharField(max_length=50, unique=True, verbose_name='Broj motora')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Masa')),
                ('engine_power', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Snaga motora')),
                ('load_capacity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Nosivost')),
                ('category', models.CharField(max_length=50, verbose_name='Kategorija')),
                ('maximum_permissible_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maksimalna dozvoljena masa')),
                ('fuel_type', models.CharField(max_length=20, verbose_name='Tip goriva')),
                ('number_of_seats', models.IntegerField(verbose_name='Broj sedišta')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vrednost vozila')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Registracioni broj mora biti u formatu AA999AA ili AA9999AA', regex='^[A-Z]{2}\\d{3,4}[A-Z]{2}$')], verbose_name='Registracioni broj')),
                ('issue_date', models.DateField(verbose_name='Datum izdavanja')),
                ('valid_until', models.DateField(verbose_name='Važi do')),
                ('traffic_card_number', models.CharField(max_length=50, verbose_name='Broj saobraćajne dozvole')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serijski broj')),
                ('owner', models.CharField(max_length=100, verbose_name='Vlasnik')),
                ('homologation_number', models.CharField(max_length=50, verbose_name='Homologacioni broj')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_cards', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Datum servisa')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Trošak')),
                ('provider', models.CharField(max_length=100, verbose_name='Dobavljač')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.servicetype', verbose_name='Tip servisa')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='PutniNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=20, verbose_name='Šifra posla')),
                ('travel_location', models.CharField(max_length=100, verbose_name='Mesto putovanja')),
                ('contract_offer', models.CharField(max_length=50, verbose_name='Ugovor/ponuda')),
                ('travel_date', models.DateField(verbose_name='Datum putovanja')),
                ('number_of_days', models.IntegerField(verbose_name='Broj dana')),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Avans')),
                ('travel_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Troškovi putovanja')),
                ('settlement_date', models.DateField(verbose_name='Datum likvidacije')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_orders', to='fleet.employee', verbose_name='Zaposleni')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_orders', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_pib', models.CharField(max_length=20, verbose_name='PIB partnera')),
                ('partner_name', models.CharField(max_length=100, verbose_name='Naziv partnera')),
                ('invoice_id', models.IntegerField(verbose_name='ID fakture')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Broj fakture')),
                ('issue_date', models.DateField(verbose_name='Datum izdavanja')),
                ('insurance_type', models.CharField(max_length=50, verbose_name='Tip osiguranja')),
                ('policy_number', models.CharField(max_length=50, verbose_name='Broj polise')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos premije')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('first_installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos prve rate')),
                ('other_installments_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos ostalih rata')),
                ('number_of_installments', models.IntegerField(verbose_name='Broj rata')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(max_length=20, verbose_name='Šifra partnera')),
                ('partner_name', models.CharField(max_length=100, verbose_name='Naziv partnera')),
                ('job_code', models.CharField(max_length=20, verbose_name='Šifra posla')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Broj ugovora')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(verbose_name='Datum završetka')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=20, verbose_name='Šifra posla')),
                ('assigned_date', models.DateField(verbose_name='Datum dodele')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_codes', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation', models.TextField(verbose_name='Prekršaj')),
                ('date', models.DateField(verbose_name='Datum')),
                ('location', models.CharField(max_length=100, verbose_name='Lokacija')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos kazne')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fleet.employee', verbose_name='Zaposleni')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina')),
                ('fuel_type', models.CharField(max_length=20, verbose_name='Tip goriva')),
                ('supplier', models.CharField(max_length=50, verbose_name='Dobavljač')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
    ]
