# Generated by Django 5.0.9 on 2024-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AddField(
            model_name='draftrequisition',
            name='nije_garaza',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nije garaža'),
        ),
        migrations.AddField(
            model_name='draftservicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AddField(
            model_name='draftservicetransaction',
            name='nije_garaza',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nije garaža'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='kilometraza',
            field=models.IntegerField(default=0, verbose_name='Kilometraža'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='nije_garaza',
            field=models.BooleanField(default=0, verbose_name='Nije garaža'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='popravka_kategorija',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategorija popravke'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='kilometraza',
            field=models.IntegerField(default=0, verbose_name='Kilometraža'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='nije_garaza',
            field=models.BooleanField(default=0, verbose_name='Nije garaža'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service_interval',
            field=models.IntegerField(default=15000, verbose_name='Servisni interval'),
        ),
    ]
