# Generated by Django 5.0.3 on 2024-07-17 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficcard',
            name='registration_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Registracioni broj mora biti u formatu AA999-AA ili AA9999-AA', regex='^[A-Z]{2}\\d{3,4}-[A-Z]{2}$')], verbose_name='Registracioni broj'),
        ),
    ]
