# Generated by Django 5.0.9 on 2024-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_draftrequisition_kilometraza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='nije_garaza',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nije garaža'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='nije_garaza',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nije garaža'),
        ),
    ]
