# Generated by Django 5.0.3 on 2024-07-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_vehicle_load_capacity_alter_vehicle_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nosivost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masa'),
        ),
    ]
