# Generated by Django 5.0.3 on 2024-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_load_capacity_alter_vehicle_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vrednost vozila'),
        ),
    ]
