# Generated by Django 5.0.9 on 2024-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_requisition_kilometraza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequisition',
            name='mesec_unosa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mesec unosa'),
        ),
    ]
