# Generated by Django 5.0.9 on 2024-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_draftrequisition_mesec_unosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequisition',
            name='popravka_kategorija',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategorija popravke'),
        ),
    ]
