# Generated by Django 5.0.3 on 2024-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_purchase_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='maximum_permissible_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maksimalna dozvoljena masa'),
        ),
    ]
