# Generated by Django 5.0.9 on 2024-12-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_draftrequisition_popravka_kategorija'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcard',
            name='traffic_card_pdf',
            field=models.FileField(blank=True, null=True, upload_to='traffic_cards/', verbose_name='PDF Saobraćajne dozvole'),
        ),
    ]
