# Generated by Django 5.1 on 2024-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_vehicle_maximum_permissible_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='cost_bruto',
            field=models.CharField(default=1, max_length=20, verbose_name='Iznos - Bruto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='cost_neto',
            field=models.CharField(default=1, max_length=20, verbose_name='Iznos - Neto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='current_payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Trenutna vrednost otplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='otpis',
            field=models.BooleanField(default=False, editable=False, verbose_name='Otpis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nabavna vrednost vozila'),
        ),
    ]
