# Generated by Django 5.0.9 on 2025-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_trafficcard_traffic_card_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_renewable',
            field=models.BooleanField(default=True, verbose_name='Da li se polisa obnavlja?'),
        ),
    ]
