# Generated by Django 5.1 on 2024-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_fuelconsumption_cost_bruto_fuelconsumption_cost_neto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='invoice_id',
            field=models.IntegerField(unique=True, verbose_name='ID fakture'),
        ),
    ]
