# Generated by Django 5.0.9 on 2025-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_policy_is_renewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='is_renewable',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Da li se polisa obnavlja?'),
        ),
    ]
