# Generated by Django 5.1 on 2024-09-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Šifra centra')),
            ],
        ),
        migrations.RenameField(
            model_name='jobcode',
            old_name='assigned_date',
            new_name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='jobcode',
            name='job_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_code',
            field=models.CharField(max_length=20, verbose_name='Šifra posla'),
        ),
        migrations.AlterField(
            model_name='jobcode',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_codes', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Šifra organizacione jedinice')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='fleet.center')),
            ],
        ),
        migrations.AddField(
            model_name='jobcode',
            name='organizational_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='fleet.organizationalunit', verbose_name='Organizaciona jedinica'),
        ),
    ]
