# Generated by Django 5.0.9 on 2025-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_policy_is_renewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='is_renewable',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=True, verbose_name='Da li se polisa obnavlja?'),
        ),
    ]
