# Generated by Django 5.0.9 on 2025-02-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_alter_policy_is_renewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='partner_pib',
            field=models.IntegerField(max_length=20, verbose_name='PIB partnera'),
        ),
    ]
