# Generated by Django 5.1 on 2024-09-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_center_rename_assigned_date_jobcode_date_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcode',
            old_name='date_assigned',
            new_name='assigned_date',
        ),
    ]
