# Generated by Django 5.1 on 2024-09-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_rename_date_assigned_jobcode_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='put_in_use_date',
            field=models.DateField(null=True, verbose_name='Datum prve registracije'),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sif_pred', models.IntegerField(blank=True, null=True, verbose_name='Šifra predmeta')),
                ('god', models.IntegerField(verbose_name='Godina')),
                ('oj', models.CharField(max_length=20, verbose_name='Organizaciona jedinica')),
                ('sif_dok', models.CharField(max_length=20, verbose_name='Šifra dokumenta')),
                ('br_dok', models.CharField(max_length=50, verbose_name='Broj dokumenta')),
                ('sif_vrsart', models.CharField(max_length=20, verbose_name='Šifra vrste artikla')),
                ('stavka', models.IntegerField(verbose_name='Stavka')),
                ('sif_art', models.CharField(max_length=20, verbose_name='Šifra artikla')),
                ('naz_art', models.CharField(max_length=255, verbose_name='Naziv artikla')),
                ('kol', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('vrednost_nab', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vrednost nabavke')),
                ('mesec_unosa', models.IntegerField(verbose_name='Mesec unosa')),
                ('datum_trebovanja', models.DateField(verbose_name='Datum trebovanja')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(verbose_name='Godina')),
                ('sif_par_pl', models.CharField(max_length=20, verbose_name='Šifra partnera (pl)')),
                ('naz_par_pl', models.CharField(max_length=255, verbose_name='Naziv partnera (pl)')),
                ('datum', models.DateTimeField(verbose_name='Datum')),
                ('sif_vrs', models.CharField(max_length=10, verbose_name='Šifra vrste')),
                ('br_naloga', models.CharField(max_length=50, verbose_name='Broj naloga')),
                ('vez_dok', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezani dokument')),
                ('knt_pl', models.CharField(max_length=20, verbose_name='Konto pl')),
                ('potrazuje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potražuje')),
                ('sif_par_npl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera (npl)')),
                ('knt_npl', models.CharField(max_length=20, verbose_name='Konto npl')),
                ('duguje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Duguje')),
                ('konto_vozila', models.CharField(max_length=20, verbose_name='Konto vozila')),
                ('kom', models.TextField(blank=True, null=True, verbose_name='Komentar')),
                ('popravka_kategorija', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategorija poptavke')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
    ]
