# Generated by Django 5.0.9 on 2025-02-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_alter_policy_partner_pib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpolicy',
            name='partner_pib',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='PIB partnera'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='Da li se ovaj servis ne pripada garaži?'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='partner_pib',
            field=models.IntegerField(verbose_name='PIB partnera'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='Nije garaža'),
        ),
    ]
