# Generated by Django 5.0.9 on 2025-02-24 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_alter_draftpolicy_partner_pib_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putninalog',
            name='return_date',
        ),
        migrations.AddField(
            model_name='putninalog',
            name='daily_allowance',
            field=models.DecimalField(decimal_places=2, default=2600, max_digits=10, verbose_name='Dnevnica'),
        ),
        migrations.AddField(
            model_name='putninalog',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Broj dana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putninalog',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum izdavanja naloga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putninalog',
            name='order_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Broj naloga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='putninalog',
            name='task',
            field=models.TextField(default=1, verbose_name='Zadatak'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draftpolicy',
            name='partner_pib',
            field=models.IntegerField(blank=True, null=True, verbose_name='PIB partnera'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Isplata'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Godina'),
        ),
        migrations.AddConstraint(
            model_name='jobcode',
            constraint=models.UniqueConstraint(fields=('vehicle', 'assigned_date'), name='unique_vehicle_assigned_date'),
        ),
    ]
