# Generated by Django 5.1 on 2024-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_vehicle_put_in_use_date_requisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='center_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Šifra centra (OJ)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Broj fakture'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='partner_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Šifra partnera'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='partner_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Naziv partnera'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='Datum nabavke'),
        ),
    ]
