# Generated by Django 5.1 on 2024-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_vehicle_center_code_vehicle_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionOMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255, verbose_name='Issuer')),
                ('customer', models.CharField(max_length=255, verbose_name='Customer')),
                ('card', models.CharField(max_length=255, verbose_name='Card')),
                ('license_plate_no', models.CharField(max_length=20, verbose_name='License plate No')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction date')),
                ('product_inv', models.CharField(max_length=255, verbose_name='Product INV')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('gross_cc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross CC')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT')),
                ('voucher', models.CharField(max_length=255, verbose_name='Voucher')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mileage')),
                ('corrected_mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corrected mileage')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional info')),
                ('supply_country', models.CharField(max_length=255, verbose_name='Supply country')),
                ('site_town', models.CharField(max_length=255, verbose_name='Site Town')),
                ('product_del', models.CharField(max_length=255, verbose_name='Product DEL')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit price')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('surcharge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surcharge')),
                ('vat_2010', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT2010')),
                ('supplier_currency', models.CharField(max_length=20, verbose_name='Supplier currency')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='Invoice No')),
                ('invoice_date', models.DateField(verbose_name='Invoice date')),
                ('invoiced', models.BooleanField(default=False, verbose_name='Invoiced?')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('cost_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost 1')),
                ('cost_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost 2')),
                ('reference_no', models.CharField(max_length=255, verbose_name='Reference No')),
                ('record_type', models.CharField(max_length=50, verbose_name='Record type')),
                ('amount_other', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount other')),
                ('is_list_price', models.BooleanField(default=False, verbose_name='Is list price?')),
                ('approval_code', models.CharField(max_length=50, verbose_name='Approval code')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date to')),
                ('final_trx', models.BooleanField(default=False, verbose_name='Final Trx')),
                ('lpi', models.CharField(blank=True, max_length=50, null=True, verbose_name='LPI')),
            ],
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='oj',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sif_dok',
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='kom',
            field=models.TextField(blank=True, null=True, verbose_name='Komada'),
        ),
    ]
