# Generated by Django 5.0.9 on 2025-02-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_remove_putninalog_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putninalog',
            name='job_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_order_job_code', to='fleet.jobcode', verbose_name='Šifra posla'),
        ),
    ]
