# Generated by Django 5.1 on 2024-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_transactionomv_remove_requisition_oj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='final_trx',
            field=models.DateField(verbose_name='Final Trx'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='is_list_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Is list price?'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='vat_2010',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT2010'),
        ),
    ]
