# Generated by Django 5.1 on 2024-09-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_transactionomv_final_trx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='invoiced',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Invoiced?'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='supplier_currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Supplier currency'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='voucher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Voucher'),
        ),
        migrations.AddConstraint(
            model_name='transactionomv',
            constraint=models.UniqueConstraint(fields=('license_plate_no', 'transaction_date'), name='unique_license_plate_transaction'),
        ),
    ]
