# Generated by Django 5.0.9 on 2025-02-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_alter_putninalog_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putninalog',
            name='year',
        ),
    ]
