# Generated by Django 5.1 on 2024-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_alter_transactionomv_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='final_trx',
            field=models.CharField(max_length=50, verbose_name='Final Trx'),
        ),
    ]
