# Generated by Django 5.0.9 on 2025-03-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_baza_dodelabucketa_ispravke_kontakti_napomene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequisition',
            name='popravka_kategorija_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.servicetype', verbose_name='Kategorija popravke (povezana)'),
        ),
        migrations.AddField(
            model_name='draftservicetransaction',
            name='popravka_kategorija_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.servicetype', verbose_name='Kategorija popravke (povezana)'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='popravka_kategorija_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.servicetype', verbose_name='Kategorija popravke (povezana)'),
        ),
        migrations.AddField(
            model_name='servicetransaction',
            name='popravka_kategorija_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.servicetype', verbose_name='Kategorija popravke (povezana)'),
        ),
    ]
