# Generated by Django 5.1 on 2024-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_alter_transactionomv_final_trx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='approval_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Approval code'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='final_trx',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Final Trx'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='is_list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Is list price?'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='product_inv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product INV'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='record_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Record type'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='reference_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier'),
        ),
    ]
