# Generated by Django 5.0.9 on 2025-03-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_draftrequisition_popravka_kategorija_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftrequisition',
            name='popravka_kategorija',
        ),
        migrations.RemoveField(
            model_name='draftservicetransaction',
            name='popravka_kategorija',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='popravka_kategorija',
        ),
        migrations.RemoveField(
            model_name='servicetransaction',
            name='popravka_kategorija',
        ),
    ]
