# Generated by Django 5.1 on 2024-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_transactionomv_approval_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='gross_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross CC'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VAT'),
        ),
    ]
