# Generated by Django 5.1 on 2024-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_transactionomv_gross_cc_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionomv',
            name='unique_license_plate_transaction',
        ),
        migrations.AddConstraint(
            model_name='transactionomv',
            constraint=models.UniqueConstraint(fields=('license_plate_no', 'transaction_date', 'product_inv'), name='unique_license_plate_transaction'),
        ),
    ]
