# Generated by Django 5.0.9 on 2025-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_rename_popravka_kategorija_fk_draftrequisition_popravka_kategorija_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
    ]
