# Generated by Django 5.1 on 2024-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_remove_transactionomv_unique_license_plate_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionomv',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mileage'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='product_del',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product DEL'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='site_town',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Town'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='supply_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Supply country'),
        ),
        migrations.AlterField(
            model_name='transactionomv',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit price'),
        ),
    ]
