# Generated by Django 5.1 on 2024-09-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_alter_transactionomv_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupac', models.CharField(max_length=255, verbose_name='Kupac')),
                ('sifra_kupca', models.CharField(max_length=50, verbose_name='Šifra kupca')),
                ('broj_kartice', models.CharField(max_length=50, verbose_name='Broj kartice')),
                ('kompanijski_kod_kupca', models.CharField(max_length=50, verbose_name='Kompanijski kod kupca')),
                ('zemlja_sipanja', models.CharField(max_length=50, verbose_name='Zemlja sipanja')),
                ('benzinska_stanica', models.CharField(max_length=255, verbose_name='Benzinska stanica')),
                ('id_transakcije', models.CharField(max_length=100, verbose_name='ID transakcije')),
                ('app_kod', models.CharField(max_length=50, verbose_name='App kod')),
                ('datum_transakcije', models.DateTimeField(verbose_name='Datum transakcije')),
                ('tociono_mesto', models.CharField(max_length=50, verbose_name='Točiono mesto')),
                ('naziv_kartice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naziv kartice')),
                ('licenca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Licenca')),
                ('broj_gazdinstva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj gazdinstva')),
                ('registarska_oznaka_vozila', models.CharField(max_length=50, verbose_name='Registarska oznaka vozila')),
                ('broj_racuna', models.CharField(max_length=50, verbose_name='Broj računa')),
                ('kilometraza', models.IntegerField(verbose_name='Kilometraža')),
                ('sipanje_van_rezervoara', models.BooleanField(verbose_name='Sipanje van rezervoara')),
                ('naziv_proizvoda', models.CharField(max_length=255, verbose_name='Naziv proizvoda')),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina')),
                ('kolicina_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Količina KG')),
                ('popust', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Popust')),
                ('primenjen_popust', models.CharField(max_length=255, verbose_name='Primenjen popust')),
                ('cena_sa_kase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena sa kase')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('total_sa_kase', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total sa kase')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('valuta', models.CharField(max_length=10, verbose_name='Valuta')),
                ('aktivirano_prekoracenje', models.BooleanField(verbose_name='Aktivirano prekoračenje')),
                ('kolicinsko_prekoracenje', models.BooleanField(verbose_name='Količinsko prekoračenje')),
                ('finansijsko_prekoracenje', models.BooleanField(verbose_name='Finansijsko prekoračenje')),
                ('nacin_ocitavanja_kartice', models.CharField(max_length=50, verbose_name='Način očitavanja kartice')),
            ],
        ),
    ]
