# Generated by Django 5.0.9 on 2025-03-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_alter_requisition_kilometraza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='center_code',
        ),
    ]
