# Generated by Django 5.1.7 on 2025-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_remove_vehicle_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('finansijski', 'Finansijski'), ('operativni', 'Operativni'), ('dugorocni', 'Dugoročni najam')], default='finansijski', max_length=20, verbose_name='Vrsta lizinga'),
        ),
    ]
