# Generated by Django 5.1 on 2024-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_transactionnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnis',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AddConstraint(
            model_name='transactionnis',
            constraint=models.UniqueConstraint(fields=('datum_transakcije', 'registarska_oznaka_vozila', 'naziv_proizvoda'), name='unique_transaction'),
        ),
    ]
