# Generated by Django 5.0.9 on 2025-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_lease_lease_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_centers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='allowed_centers',
            field=models.ManyToManyField(blank=True, to='fleet.organizationalunit'),
        ),
    ]
