# Generated by Django 5.1 on 2024-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_alter_transactionnis_kilometraza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='center',
            field=models.CharField(max_length=10, unique=True, verbose_name='Šifra centra'),
        ),
        migrations.DeleteModel(
            name='Center',
        ),
    ]
