# Generated by Django 5.0.9 on 2025-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_remove_customuser_allowed_centers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
    ]
