# Generated by Django 5.1 on 2024-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_alter_organizationalunit_center_delete_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='center',
            field=models.CharField(max_length=10, verbose_name='Šifra centra'),
        ),
    ]
