# Generated by Django 5.0.9 on 2025-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_alter_servicetransaction_kilometraza'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetKontoVozila',
            fields=[
                ('knt', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Konto')),
                ('naz_knt', models.CharField(max_length=200, verbose_name='Naziv konta')),
            ],
            options={
                'verbose_name': 'Konto vozila',
                'verbose_name_plural': 'Konta vozila',
            },
        ),
        migrations.DeleteModel(
            name='Baza',
        ),
        migrations.DeleteModel(
            name='DodelaBucketa',
        ),
        migrations.DeleteModel(
            name='Ispravke',
        ),
        migrations.DeleteModel(
            name='Kontakti',
        ),
        migrations.DeleteModel(
            name='Napomene',
        ),
        migrations.DeleteModel(
            name='Opomene',
        ),
        migrations.DeleteModel(
            name='Partneri',
        ),
        migrations.DeleteModel(
            name='PoziviTel',
        ),
        migrations.DeleteModel(
            name='PozivPismo',
        ),
        migrations.DeleteModel(
            name='SifBaket',
        ),
        migrations.DeleteModel(
            name='SifKategorija',
        ),
        migrations.DeleteModel(
            name='Tuzbe',
        ),
        migrations.AddConstraint(
            model_name='draftservicetransaction',
            constraint=models.UniqueConstraint(fields=('datum', 'duguje', 'vez_dok', 'br_naloga'), name='unique_draft_service_transaction'),
        ),
    ]
