# Generated by Django 5.1 on 2024-09-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_alter_organizationalunit_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='put_in_use_date',
        ),
    ]
