# Generated by Django 5.1 on 2024-09-09 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_remove_vehicle_put_in_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Registracioni broj mora biti u formatu AA999-AA ili AA9999-AA', regex='^[A-Z]{2}\\d{3,4}-[A-Z]{2}$')], verbose_name='Registracioni broj'),
        ),
    ]
