# Generated by Django 5.0.9 on 2025-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_fleetkontovozila_delete_baza_delete_dodelabucketa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaskoRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '[dbo].[kasko_rate]',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='FleetKontoVozila',
            new_name='KontaVozila',
        ),
    ]
