# Generated by Django 5.0.9 on 2025-09-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_kaskorate_rename_fleetkontovozila_kontavozila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Ne'), (False, 'Da')], default=False, verbose_name='Da li se ovaj servis pripada garaži?'),
        ),
        migrations.CreateModel(
            name='VehicleTenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('license_plate', 'Slika tablica'), ('sticker', 'Slika nalepnice'), ('other', 'Drugo')], default='license_plate', max_length=20, verbose_name='Tip dokumenta')),
                ('title', models.CharField(max_length=255, verbose_name='Naziv')),
                ('image', models.ImageField(upload_to='vehicle_tender_documents/%Y/%m/', verbose_name='Slika')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('taken_at', models.DateField(blank=True, null=True, verbose_name='Datum fotografisanja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_documents', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
            options={
                'verbose_name': 'Tender dokument vozila',
                'verbose_name_plural': 'Tender dokumenti vozila',
                'ordering': ['-created_at'],
            },
        ),
    ]
