# Generated by Django 5.1 on 2024-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_alter_service_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Godina'),
            preserve_default=False,
        ),
    ]
