# Generated by Django 5.0.9 on 2025-10-01 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_alter_draftservicetransaction_nije_garaza_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(blank=True, null=True, verbose_name='Godina')),
                ('sif_vrs', models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra vrste')),
                ('br_naloga', models.CharField(max_length=50, verbose_name='Broj naloga')),
                ('stavka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stavka')),
                ('oj', models.CharField(blank=True, max_length=50, null=True, verbose_name='OJ')),
                ('knt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Konto')),
                ('datum', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('vez_dok', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezni dokument')),
                ('potrazuje', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potražuje')),
                ('kola', models.BooleanField(blank=True, default=True, null=True, verbose_name='Odnosi se na auto')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_insurances', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
            options={
                'verbose_name': 'Draft osiguranje',
                'verbose_name_plural': 'Draft osiguranja',
                'indexes': [models.Index(fields=['god', 'sif_vrs', 'br_naloga', 'stavka', 'knt'], name='fleet_draft_god_731cca_idx'), models.Index(fields=['br_naloga'], name='fleet_draft_br_nalo_91d290_idx')],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(blank=True, null=True, verbose_name='Godina')),
                ('sif_vrs', models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra vrste')),
                ('br_naloga', models.CharField(max_length=50, verbose_name='Broj naloga')),
                ('stavka', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stavka')),
                ('oj', models.CharField(blank=True, max_length=50, null=True, verbose_name='OJ')),
                ('knt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Konto')),
                ('datum', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('vez_dok', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezni dokument')),
                ('potrazuje', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potražuje')),
                ('kola', models.BooleanField(default=True, verbose_name='Odnosi se na auto')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
            options={
                'verbose_name': 'Osiguranje',
                'verbose_name_plural': 'Osiguranja',
                'indexes': [models.Index(fields=['god', 'sif_vrs', 'br_naloga', 'stavka', 'knt'], name='fleet_insur_god_10b62b_idx'), models.Index(fields=['br_naloga'], name='fleet_insur_br_nalo_dd4fff_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='insurance',
            constraint=models.UniqueConstraint(fields=('god', 'sif_vrs', 'br_naloga', 'stavka', 'knt'), name='uniq_insurance_key'),
        ),
    ]
