# Generated by Django 5.1 on 2024-09-10 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_putninalog_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putninalog',
            name='travel_expenses',
        ),
        migrations.AddField(
            model_name='putninalog',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum povratka'),
            preserve_default=False,
        ),
    ]
