# Generated by Django 5.0.9 on 2025-12-01 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_draftinsurance_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraza', models.PositiveIntegerField(verbose_name='Kilometraza')),
                ('opis', models.TextField(verbose_name='Opis kvara')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('van_ims', models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, help_text="Oznaci 'Da' ako se kvar resava van IMS garaze.", verbose_name='Popravka van IMS-a')),
                ('rbz', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='R.b.z.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum i vreme prijave')),
            ],
            options={
                'verbose_name': 'Kvar vozila',
                'verbose_name_plural': 'Kvarovi vozila',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='draftinsurance',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potra┼╛uje'),
        ),
        migrations.AlterField(
            model_name='draftinsurance',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='┼áifra vrste'),
        ),
        migrations.AlterField(
            model_name='draftpolicy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum zavr┼íetka'),
        ),
        migrations.AlterField(
            model_name='draftpolicy',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum po─ìetka'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='nije_garaza',
            field=models.BooleanField(default=False, verbose_name='Nije gara┼╛a'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='sif_pred',
            field=models.IntegerField(blank=True, null=True, verbose_name='┼áifra predmeta'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Ne'), (False, 'Da')], default=False, verbose_name='Da li se ovaj servis pripada gara┼╛i?'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Potra┼╛uje'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_par_npl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='┼áifra partnera (npl)'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_par_pl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='┼áifra partnera (pl)'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='┼áifra vrste'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Datum ro─æenja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(verbose_name='Datum zapo┼íljavanja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_code',
            field=models.IntegerField(verbose_name='┼áifra odeljenja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(unique=True, verbose_name='┼áifra zaposlenog'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Mu┼íki'), ('F', '┼╜enski')], max_length=1, verbose_name='Pol'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koli─ìina'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='job_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='┼áifra posla'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='mileage',
            field=models.IntegerField(verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='supplier',
            field=models.CharField(max_length=50, verbose_name='Dobavlja─ì'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='violation',
            field=models.TextField(verbose_name='Prekr┼íaj'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potra┼╛uje'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='┼áifra vrste'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(verbose_name='Datum zavr┼íetka'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='job_code',
            field=models.CharField(max_length=20, verbose_name='┼áifra posla'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('finansijski', 'Finansijski'), ('operativni', 'Operativni'), ('dugorocni', 'Dugoro─ìni najam')], default='finansijski', max_length=20, verbose_name='Vrsta lizinga'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='partner_code',
            field=models.CharField(max_length=20, verbose_name='┼áifra partnera'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(verbose_name='Datum po─ìetka'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='center',
            field=models.CharField(max_length=10, verbose_name='┼áifra centra'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='┼áifra organizacione jedinice'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='Datum zavr┼íetka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='Datum po─ìetka'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='job_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_order_job_code', to='fleet.organizationalunit', verbose_name='Tro┼íkovi idu na teret'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='kol',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koli─ìina'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='nije_garaza',
            field=models.BooleanField(verbose_name='Nije gara┼╛a'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_art',
            field=models.CharField(max_length=20, verbose_name='┼áifra artikla'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_pred',
            field=models.IntegerField(verbose_name='┼áifra predmeta'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_vrsart',
            field=models.CharField(max_length=20, verbose_name='┼áifra vrste artikla'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tro┼íak'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='Dobavlja─ì'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='Nije gara┼╛a'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='potrazuje',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potra┼╛uje'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_par_npl',
            field=models.CharField(max_length=20, verbose_name='┼áifra partnera (npl)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_par_pl',
            field=models.CharField(max_length=20, verbose_name='┼áifra partnera (pl)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_vrs',
            field=models.CharField(max_length=10, verbose_name='┼áifra vrste'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='traffic_card_number',
            field=models.CharField(max_length=50, verbose_name='Broj saobra─çajne dozvole'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='traffic_card_pdf',
            field=models.FileField(blank=True, null=True, upload_to='traffic_cards/', verbose_name='PDF Saobra─çajne dozvole'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='valid_until',
            field=models.DateField(verbose_name='Va┼╛i do'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='aktivirano_prekoracenje',
            field=models.BooleanField(verbose_name='Aktivirano prekora─ìenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='broj_racuna',
            field=models.CharField(max_length=50, verbose_name='Broj ra─ìuna'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='finansijsko_prekoracenje',
            field=models.BooleanField(verbose_name='Finansijsko prekora─ìenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometra┼╛a'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicina',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Koli─ìina'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicina_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koli─ìina KG'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicinsko_prekoracenje',
            field=models.BooleanField(verbose_name='Koli─ìinsko prekora─ìenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='nacin_ocitavanja_kartice',
            field=models.CharField(max_length=50, verbose_name='Na─ìin o─ìitavanja kartice'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='sifra_kupca',
            field=models.CharField(max_length=50, verbose_name='┼áifra kupca'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='tociono_mesto',
            field=models.CharField(max_length=50, verbose_name='To─ìiono mesto'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(max_length=17, unique=True, verbose_name='Broj ┼íasije'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_seats',
            field=models.IntegerField(verbose_name='Broj sedi┼íta'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner_code',
            field=models.CharField(max_length=20, null=True, verbose_name='┼áifra partnera'),
        ),
        migrations.AddIndex(
            model_name='jobcode',
            index=models.Index(fields=['vehicle', '-assigned_date', '-id'], name='fleet_jobco_vehicle_29c69a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcode',
            index=models.Index(fields=['organizational_unit'], name='fleet_jobco_organiz_715863_idx'),
        ),
        migrations.AddField(
            model_name='kvar',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvarovi', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
