# Generated by Django 5.1 on 2024-09-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_remove_putninalog_travel_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='first_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos prve rate'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='other_installments_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos ostalih rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
