# Generated by Django 5.1 on 2024-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_alter_policy_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='cost_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos - Bruto'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='cost_neto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos - Neto'),
        ),
    ]
