# Generated by Django 5.0.9 on 2025-12-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_kvar_alter_draftinsurance_potrazuje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvar',
            name='work_type',
            field=models.CharField(choices=[('mali_servis', 'Mali servis'), ('veliki_servis', 'Veliki servis'), ('popravka', 'Popravka')], default='popravka', max_length=20, verbose_name='Vrsta intervencije'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='allowed_centers',
            field=models.ManyToManyField(blank=True, to='fleet.organizationalunit', verbose_name='Dozvoljene organizacione jedinice'),
        ),
        migrations.AlterField(
            model_name='draftinsurance',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potražuje'),
        ),
        migrations.AlterField(
            model_name='draftinsurance',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra vrste'),
        ),
        migrations.AlterField(
            model_name='draftinsurance',
            name='vez_dok',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezani dokument'),
        ),
        migrations.AlterField(
            model_name='draftpolicy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='draftpolicy',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='br_dok',
            field=models.CharField(max_length=50, verbose_name='Broj dokumenta'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='datum_trebovanja',
            field=models.DateField(blank=True, null=True, verbose_name='Datum trebovanja'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='god',
            field=models.IntegerField(blank=True, null=True, verbose_name='Godina'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='kol',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='napomena',
            field=models.TextField(blank=True, null=True, verbose_name='Napomena'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='naz_art',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv artikla'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='nije_garaza',
            field=models.BooleanField(default=False, verbose_name='Nije garaža'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='sif_art',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Šifra artikla'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='sif_pred',
            field=models.IntegerField(blank=True, null=True, verbose_name='Šifra predmeta'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='sif_vrsart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Šifra vrste artikla'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='stavka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stavka'),
        ),
        migrations.AlterField(
            model_name='draftrequisition',
            name='vrednost_nab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Vrednost nabavke'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='knt_npl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Konto NPL'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='knt_pl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Konto PL'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='naz_par_pl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv partnera (PL)'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='Da li ovaj servis pripada garaži?'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Potražuje'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_par_npl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera (NPL)'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_par_pl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera (PL)'),
        ),
        migrations.AlterField(
            model_name='draftservicetransaction',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Šifra vrste'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Datum rođenja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(verbose_name='Datum zapošljavanja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_code',
            field=models.IntegerField(verbose_name='Šifra odeljenja'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(unique=True, verbose_name='Šifra zaposlenog'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Muški'), ('F', 'Ženski')], max_length=1, verbose_name='Pol'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Prezime'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='cost_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos – bruto'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='cost_neto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos – neto'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='fuel_type',
            field=models.CharField(max_length=20, verbose_name='Vrsta goriva'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='job_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Šifra posla'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='mileage',
            field=models.IntegerField(verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='fuelconsumption',
            name='supplier',
            field=models.CharField(max_length=50, verbose_name='Dobavljač'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='violation',
            field=models.TextField(verbose_name='Prekršaj'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='potrazuje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potražuje'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='sif_vrs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra vrste'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='vez_dok',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezani dokument'),
        ),
        migrations.AlterField(
            model_name='kvar',
            name='kilometraza',
            field=models.PositiveIntegerField(verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='kvar',
            name='van_ims',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, help_text="Označi 'Da' ako se kvar rešava van IMS garaže.", verbose_name='Popravka van IMS-a'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='current_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Trenutna rata / iznos otplate'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='job_code',
            field=models.CharField(max_length=20, verbose_name='Šifra posla'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(choices=[('finansijski', 'Finansijski'), ('operativni', 'Operativni'), ('dugoročnI', 'Dugoročni najam')], default='finansijski', max_length=20, verbose_name='Vrsta lizinga'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='partner_code',
            field=models.CharField(max_length=20, verbose_name='Šifra partnera'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='center',
            field=models.CharField(max_length=10, verbose_name='Šifra centra'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Šifra organizacione jedinice'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='contract_offer',
            field=models.CharField(max_length=50, verbose_name='Ugovor / ponuda'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='job_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_order_job_code', to='fleet.organizationalunit', verbose_name='Troškovi idu na teret'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='kol',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='nije_garaza',
            field=models.BooleanField(verbose_name='Nije garaža'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_art',
            field=models.CharField(max_length=20, verbose_name='Šifra artikla'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_pred',
            field=models.IntegerField(verbose_name='Šifra predmeta'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_vrsart',
            field=models.CharField(max_length=20, verbose_name='Šifra vrste artikla'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Trošak'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='Dobavljač'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='knt_npl',
            field=models.CharField(max_length=20, verbose_name='Konto NPL'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='knt_pl',
            field=models.CharField(max_length=20, verbose_name='Konto PL'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='naz_par_pl',
            field=models.CharField(max_length=255, verbose_name='Naziv partnera (PL)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='nije_garaza',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=False, verbose_name='Nije garaža'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='potrazuje',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potražuje'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_par_npl',
            field=models.CharField(max_length=20, verbose_name='Šifra partnera (NPL)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_par_pl',
            field=models.CharField(max_length=20, verbose_name='Šifra partnera (PL)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_vrs',
            field=models.CharField(max_length=10, verbose_name='Šifra vrste'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='traffic_card_number',
            field=models.CharField(max_length=50, verbose_name='Broj saobraćajne dozvole'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='traffic_card_pdf',
            field=models.FileField(blank=True, null=True, upload_to='traffic_cards/', verbose_name='PDF saobraćajne dozvole'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='valid_until',
            field=models.DateField(verbose_name='Važi do'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='aktivirano_prekoracenje',
            field=models.BooleanField(verbose_name='Aktivirano prekoračenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='broj_racuna',
            field=models.CharField(max_length=50, verbose_name='Broj računa'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='finansijsko_prekoracenje',
            field=models.BooleanField(verbose_name='Finansijsko prekoračenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kilometraza',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraža'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicina',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Količina'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicina_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Količina (kg)'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='kolicinsko_prekoracenje',
            field=models.BooleanField(verbose_name='Količinsko prekoračenje'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='nacin_ocitavanja_kartice',
            field=models.CharField(max_length=50, verbose_name='Način očitavanja kartice'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='sifra_kupca',
            field=models.CharField(max_length=50, verbose_name='Šifra kupca'),
        ),
        migrations.AlterField(
            model_name='transactionnis',
            name='tociono_mesto',
            field=models.CharField(max_length=50, verbose_name='Točeno mesto'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Kategorija vozila'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(max_length=17, unique=True, verbose_name='Broj šasije'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Snaga motora (kW)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Zapremina motora (cm³)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=20, verbose_name='Vrsta goriva'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inventory_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Inventarski broj'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nosivost (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='maximum_permissible_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maksimalna dozvoljena masa (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_seats',
            field=models.IntegerField(verbose_name='Broj sedišta'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Šifra partnera'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nabavna vrednost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service_interval',
            field=models.IntegerField(default=15000, verbose_name='Servisni interval (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Knjigovodstvena vrednost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masa (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicletenderdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.CreateModel(
            name='KvarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv dela')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Količina')),
                ('uom', models.CharField(default='kom', max_length=30, verbose_name='Jedinica mere')),
                ('kvar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='fleet.kvar', verbose_name='Kvar')),
            ],
            options={
                'verbose_name': 'Deo za kvar',
                'verbose_name_plural': 'Delovi za kvar',
            },
        ),
        migrations.CreateModel(
            name='VehicleTravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn_number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='PN broj')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Datum otvaranja naloga')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Datum zatvaranja naloga')),
                ('rbz', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='R.b.z.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_travel_orders', to='fleet.employee', verbose_name='Zaposleni')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_travel_orders', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
            options={
                'verbose_name': 'Putni nalog vozila',
                'verbose_name_plural': 'Putni nalozi vozila',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
