# Generated by Django 5.1 on 2024-09-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_alter_fuelconsumption_cost_bruto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(null=True, verbose_name='Datum servisa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleet.servicetype', verbose_name='Tip servisa'),
        ),
    ]
