# Generated by Django 5.0.9 on 2025-12-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_kvar_work_type_alter_customuser_allowed_centers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftrequisition',
            name='kvar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_requisitions', to='fleet.kvar', verbose_name='Kvar (IMS)'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='kvar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='fleet.kvar', verbose_name='Kvar (IMS)'),
        ),
        migrations.AddField(
            model_name='vehicletravelorder',
            name='end_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Krajnja kilometraža'),
        ),
        migrations.AddField(
            model_name='vehicletravelorder',
            name='start_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Početna kilometraža'),
        ),
    ]
