# Generated by Django 5.0.9 on 2025-12-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_draftrequisition_kvar_requisition_kvar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Broj GZN')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('job_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='fleet.organizationalunit', verbose_name='Sifra posla (OJ)')),
            ],
            options={
                'verbose_name': 'Zahtev za nabavku',
                'verbose_name_plural': 'Zahtevi za nabavku',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv materijala / usluge')),
                ('uom', models.CharField(max_length=30, verbose_name='Jedinica mere')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kolicina')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fleet.procurementrequest', verbose_name='Zahtev za nabavku')),
            ],
            options={
                'verbose_name': 'Stavka zahteva za nabavku',
                'verbose_name_plural': 'Stavke zahteva za nabavku',
            },
        ),
    ]
