# Generated by Django 5.0.9 on 2026-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_procurementrequest_procurementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_center_codes',
            field=models.CharField(blank=True, help_text='Unesi šifre centara odvojene zarezom, npr: 43, 12, 77', max_length=255, null=True, verbose_name='Dozvoljeni centri (šifre)'),
        ),
    ]
