# Generated by Django 5.1 on 2024-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_alter_requisition_datum_trebovanja_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
