# Generated by Django 5.1 on 2024-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransaction',
            name='datum',
            field=models.DateField(verbose_name='Datum'),
        ),
    ]
