# Generated by Django 5.0.9 on 2026-01-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_customuser_allowed_center_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='Kod dozvole')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Kod dozvole',
                'verbose_name_plural': 'Kodovi dozvola',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naziv uloge')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
            ],
            options={
                'verbose_name': 'Uloga',
                'verbose_name_plural': 'Uloge',
            },
        ),
        migrations.CreateModel(
            name='PutniNalogSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=10, verbose_name='Šifra centra')),
                ('year', models.PositiveIntegerField(verbose_name='Godina')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Sledeći broj')),
            ],
            options={
                'verbose_name': 'Brojač putnih naloga',
                'verbose_name_plural': 'Brojači putnih naloga',
                'unique_together': {('center_code', 'year')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='fleet.role', verbose_name='Uloge'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='fleet.permissioncode')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='fleet.role')),
            ],
            options={
                'verbose_name': 'Dozvola uloge',
                'verbose_name_plural': 'Dozvole uloga',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='fleet.RolePermission', to='fleet.permissioncode', verbose_name='Dozvole'),
        ),
    ]
