# Generated by Django 5.0.9 on 2026-01-26 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_permissioncode_role_putninalogsequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='other_vehicle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prevozno sredstvo (ostalo)'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Isplata/Akontacija'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='contract_offer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ugovor / ponuda'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum izdavanja naloga'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_orders', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
