# Generated by Django 5.1 on 2024-09-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_alter_servicetransaction_datum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putninalog',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='putninalog',
            name='settlement_date',
        ),
    ]
