# Generated by Django 5.0.9 on 2026-02-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_putninalog_other_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='is_weekly',
            field=models.BooleanField(default=False, verbose_name='Nedeljni nalog'),
        ),
    ]
