# Generated by Django 5.1 on 2024-09-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='allowed_centers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dozvole za centar'),
        ),
    ]
