# Generated by Django 5.0.9 on 2026-02-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_putninalog_is_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partija'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Škola'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra zanimanja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv zanimanja'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobilni broj'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org_unit_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OJ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Matični broj'),
        ),
        migrations.AddField(
            model_name='employee',
            name='slava',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slava'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Šifra statusa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv statusa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='system_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Šifra sistema'),
        ),
        migrations.AddField(
            model_name='employee',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv sistema'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Titula'),
        ),
    ]
