# Generated by Django 5.0.9 on 2026-02-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_employee_account_number_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='advance_payment_currency',
            field=models.CharField(choices=[('RSD', 'RSD'), ('USD', 'USD'), ('EUR', 'EUR')], default='RSD', max_length=3, verbose_name='Valuta akontacije'),
        ),
        migrations.AddField(
            model_name='putninalog',
            name='other_employee_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Zaposleni (ostalo)'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_orders', to='fleet.employee', verbose_name='Zaposleni'),
        ),
    ]
