# Generated by Django 5.1 on 2024-09-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_alter_customuser_allowed_centers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionnis',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nis_transactions', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AddField(
            model_name='transactionomv',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omv_transactions', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_transactions', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
