# Generated by Django 5.0.9 on 2026-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_putninalog_advance_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='opravdan',
            field=models.BooleanField(default=False, verbose_name='Opravdan'),
        ),
    ]
