# Generated by Django 5.0.9 on 2026-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_putninalog_opravdan'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='storniran',
            field=models.BooleanField(default=False, verbose_name='Storniran'),
        ),
    ]
