# Generated by Django 5.1 on 2024-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_transactionnis_vehicle_transactionomv_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='job_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Šifra posla'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval',
            field=models.IntegerField(default=15000, verbose_name='Servisni interval'),
            preserve_default=False,
        ),
    ]
