# Generated by Django 5.0.9 on 2026-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_putninalog_storniran'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='napomena',
            field=models.TextField(blank=True, null=True, verbose_name='Napomena'),
        ),
    ]
