# Generated by Django 5.1 on 2024-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_fuelconsumption_job_code_vehicle_service_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Broj telefona'),
        ),
        migrations.AddConstraint(
            model_name='servicetransaction',
            constraint=models.UniqueConstraint(fields=('datum', 'duguje', 'vez_dok', 'br_naloga'), name='unique_service_transaction'),
        ),
    ]
