# Generated by Django 5.1 on 2024-09-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Knjigovodstvena vrednost vozila'),
        ),
    ]
