# Generated by Django 5.0.9 on 2026-04-24 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_putninalog_napomena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletravelorder',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum otvaranja naloga'),
        ),
    ]
