# Generated by Django 5.0.9 on 2024-09-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_vehicle_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Godina')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Iznos kamate')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_interests', to='fleet.lease', verbose_name='Lizing')),
            ],
            options={
                'unique_together': {('year', 'lease')},
            },
        ),
    ]
