# Generated by Django 5.0.9 on 2026-04-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0044_normalize_long_term_lease_type'),
    ]

    operations = [
    ]
