# Generated by Django 5.0.9 on 2026-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0045_test_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trenutna kilometraža'),
        ),
    ]
