# Generated by Django 5.0.9 on 2024-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0045_remove_employee_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(unique=True, verbose_name='Šifra zaposlenog'),
        ),
    ]
