# Generated by Django 5.0.9 on 2026-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_current_mileage_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='goddada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Godina'),
        ),
    ]
