# Generated by Django 5.0.9 on 2024-09-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_alter_employee_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='date',
            field=models.DateTimeField(verbose_name='Datum'),
        ),
        migrations.AddConstraint(
            model_name='fuelconsumption',
            constraint=models.UniqueConstraint(fields=('date', 'cost_neto'), name='unique_fuel_consumption'),
        ),
    ]
