# Generated by Django 5.0.9 on 2026-04-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_insurance_goddada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='goddada',
        ),
    ]
