# Generated by Django 5.0.9 on 2024-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0047_alter_fuelconsumption_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fuelconsumption',
            name='unique_fuel_consumption',
        ),
        migrations.AddConstraint(
            model_name='fuelconsumption',
            constraint=models.UniqueConstraint(fields=('date', 'cost_bruto', 'amount'), name='unique_fuel_consumption'),
        ),
    ]
