# Generated by Django 5.0.9 on 2024-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_remove_fuelconsumption_unique_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Kilometraža'),
            preserve_default=False,
        ),
    ]
