# Generated by Django 5.0.9 on 2024-11-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0049_fuelconsumption_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_pib', models.CharField(blank=True, max_length=20, null=True, verbose_name='PIB partnera')),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Naziv partnera')),
                ('invoice_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID fakture')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj fakture')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Datum izdavanja')),
                ('insurance_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tip osiguranja')),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj polise')),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos premije')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Datum početka')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Datum završetka')),
                ('first_installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos prve rate')),
                ('other_installments_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos ostalih rata')),
                ('number_of_installments', models.IntegerField(blank=True, null=True, verbose_name='Broj rata')),
            ],
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='first_installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos prve rate'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='number_of_installments',
            field=models.IntegerField(verbose_name='Broj rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='other_installments_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos ostalih rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='datum_trebovanja',
            field=models.DateField(verbose_name='Datum trebovanja'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='mesec_unosa',
            field=models.IntegerField(verbose_name='Mesec unosa'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='sif_pred',
            field=models.IntegerField(verbose_name='Šifra predmeta'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='popravka_kategorija',
            field=models.CharField(max_length=100, verbose_name='Kategorija poptavke'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='sif_par_npl',
            field=models.CharField(max_length=20, verbose_name='Šifra partnera (npl)'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AlterField(
            model_name='servicetransaction',
            name='vez_dok',
            field=models.CharField(max_length=50, verbose_name='Vezani dokument'),
        ),
        migrations.CreateModel(
            name='DraftRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sif_pred', models.IntegerField(blank=True, null=True, verbose_name='Šifra predmeta')),
                ('god', models.IntegerField(blank=True, null=True)),
                ('br_dok', models.CharField(max_length=50)),
                ('sif_vrsart', models.CharField(blank=True, max_length=50, null=True)),
                ('stavka', models.CharField(blank=True, max_length=50, null=True)),
                ('sif_art', models.CharField(blank=True, max_length=50, null=True)),
                ('naz_art', models.CharField(blank=True, max_length=255, null=True)),
                ('kol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vrednost_nab', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('datum_trebovanja', models.DateField(blank=True, null=True)),
                ('napomena', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_requisitions', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
        migrations.CreateModel(
            name='DraftServiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god', models.IntegerField(blank=True, null=True, verbose_name='Godina')),
                ('sif_par_pl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera (pl)')),
                ('naz_par_pl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv partnera (pl)')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('sif_vrs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Šifra vrste')),
                ('br_naloga', models.CharField(max_length=50, verbose_name='Broj naloga')),
                ('vez_dok', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vezani dokument')),
                ('knt_pl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Konto pl')),
                ('potrazuje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Potražuje')),
                ('sif_par_npl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera (npl)')),
                ('knt_npl', models.CharField(blank=True, max_length=20, null=True, verbose_name='Konto npl')),
                ('duguje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duguje')),
                ('konto_vozila', models.CharField(blank=True, max_length=20, null=True, verbose_name='Konto vozila')),
                ('kom', models.TextField(blank=True, null=True, verbose_name='Komada')),
                ('popravka_kategorija', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategorija popravke')),
                ('napomena', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_service_transactions', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
        ),
    ]
