# Generated by Django 5.0.9 on 2024-11-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0050_draftpolicy_alter_policy_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpolicy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_policies', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
