# Generated by Django 5.0.9 on 2026-05-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0051_alter_transactionomv_unique_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_mileage',
        ),
    ]
