# Generated by Django 5.0.9 on 2026-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0052_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficcard',
            name='traffic_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='traffic_cards/images/%Y/%m/', verbose_name='Slika saobraćajne dozvole - zadnja strana'),
        ),
        migrations.AddField(
            model_name='trafficcard',
            name='traffic_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='traffic_cards/images/%Y/%m/', verbose_name='Slika saobraćajne dozvole - prednja strana'),
        ),
    ]
