# Generated by Django 5.0.9 on 2026-06-02 12:25

import django.db.models.deletion
from django.db import migrations, models


USER_EMPLOYEE_CODES = {
    'aleksandra.nikolic': 183,
    'ana.andjelkovic': 1015,
    'dragana.jovanovic': 895,
    'helena.stevancevic': 5,
    'ivana.sibinovic': 724,
    'jasminka.knezevic': 645,
    'kristina.ilic': 873,
    'milica.teslic': 979,
    'milivoje.peric': 752,
    'milka.popovic': 146,
    'mirjana.zivanovic': 511,
    'nikolina': 872,
    'olivera.pavlovic': 981,
    'rajo': 849,
    'stana.prica': 772,
    'suzana.injac': 831,
    'vesna.meha': 654,
    'zoran': 706,
    'zorica.tomasevic': 261,
}


def link_users_to_employees(apps, schema_editor):
    CustomUser = apps.get_model('fleet', 'CustomUser')
    Employee = apps.get_model('fleet', 'Employee')

    employees_by_code = {
        employee.employee_code: employee.pk
        for employee in Employee.objects.filter(employee_code__in=USER_EMPLOYEE_CODES.values())
    }
    for username, employee_code in USER_EMPLOYEE_CODES.items():
        employee_id = employees_by_code.get(employee_code)
        if employee_id is not None:
            CustomUser.objects.filter(username=username).update(employee_id=employee_id)


def unlink_users_from_employees(apps, schema_editor):
    CustomUser = apps.get_model('fleet', 'CustomUser')
    CustomUser.objects.filter(username__in=USER_EMPLOYEE_CODES).update(employee_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_trafficcard_traffic_card_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='fleet.employee', verbose_name='Zaposleni'),
        ),
        migrations.RunPython(link_users_to_employees, unlink_users_from_employees),
    ]
