# Generated by Django 5.0.9 on 2026-06-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0054_link_users_to_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naziv posla ili projekta')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Organizacija / klijent')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Uloga')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Period od')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Period do')),
                ('description', models.TextField(verbose_name='Opis aktivnosti')),
                ('skills', models.TextField(blank=True, verbose_name='Znanja i vestine')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_items', to='fleet.employee', verbose_name='Zaposleni')),
            ],
            options={
                'verbose_name': 'CV stavka',
                'verbose_name_plural': 'CV stavke',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
