# Generated by Django 5.0.9 on 2026-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0055_employee_cv_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='display_first_name_override',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ime za prikaz'),
        ),
        migrations.AddField(
            model_name='employee',
            name='display_last_name_override',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prezime za prikaz'),
        ),
    ]
