# Generated by Django 5.0.9 on 2026-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0058_dedupe_omv_transactions_unique_voucher_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='original_full_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Originalno ime i prezime'),
        ),
    ]
