# Generated by Django 5.0.9 on 2026-06-10 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0059_employee_original_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='virman_generated',
            field=models.BooleanField(default=False, verbose_name='Virman odradjen'),
        ),
        migrations.AddField(
            model_name='putninalog',
            name='virman_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vreme generisanja virmana'),
        ),
        migrations.AddField(
            model_name='putninalog',
            name='virman_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_travel_order_virmans', to=settings.AUTH_USER_MODEL, verbose_name='Virman generisao'),
        ),
    ]
