# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0061_vehicle_category_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="residence_municipality",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Opstina boravka",
            ),
        ),
    ]
