# Generated by Django 5.0.9 on 2026-07-07 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_activity_log_permission(apps, schema_editor):
    PermissionCode = apps.get_model("fleet", "PermissionCode")
    Role = apps.get_model("fleet", "Role")
    RolePermission = apps.get_model("fleet", "RolePermission")

    permission, _ = PermissionCode.objects.get_or_create(
        code="activity_log_list",
        defaults={"label": "Activity log"},
    )
    role, _ = Role.objects.get_or_create(
        slug="uprava",
        defaults={"name": "Uprava", "is_active": True},
    )
    RolePermission.objects.get_or_create(role=role, permission=permission)


def remove_activity_log_permission(apps, schema_editor):
    PermissionCode = apps.get_model("fleet", "PermissionCode")
    PermissionCode.objects.filter(code="activity_log_list").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0062_employee_residence_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('actor_display_name', models.CharField(blank=True, max_length=255, verbose_name='Ime korisnika')),
                ('action', models.CharField(choices=[('request', 'Akcija'), ('login', 'Prijava'), ('logout', 'Odjava'), ('login_failed', 'Neuspesna prijava'), ('manual', 'Rucni zapis')], db_index=True, default='request', max_length=30, verbose_name='Akcija')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Opis')),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Aplikacija')),
                ('view_name', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='View')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Metod')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Putanja')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Status')),
                ('object_model', models.CharField(blank=True, max_length=150, verbose_name='Model')),
                ('object_pk', models.CharField(blank=True, max_length=80, verbose_name='ID zapisa')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Zapis')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Detalji')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vreme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Activity log',
                'verbose_name_plural': 'Activity log',
                'db_table': 'fleet_activity_log',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fleet_activ_user_id_20cb5b_idx'), models.Index(fields=['action', '-created_at'], name='fleet_activ_action_cda1d8_idx'), models.Index(fields=['app_label', '-created_at'], name='fleet_activ_app_lab_4ec6b9_idx')],
            },
        ),
        migrations.RunPython(grant_activity_log_permission, remove_activity_log_permission),
    ]
