# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0063_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="skip_hr_identity_update",
            field=models.BooleanField(
                default=False,
                help_text="Ako je ukljuceno, HR sinhronizacija ne menja titulu, ime, prezime i pol.",
                verbose_name="Ne azuriraj identitet iz HR-a",
            ),
        ),
    ]
