# Generated by Django 5.0.9 on 2026-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0064_employee_skip_hr_identity_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='putninalog',
            name='isplaceno',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Isplaćeno'),
        ),
    ]
