# Generated by Django 5.0.9 on 2026-07-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0067_requisition_direct_sync_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftRequisition',
        ),
    ]
