# Generated by Django 5.0.9 on 2026-07-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0068_delete_draftrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum završetka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='first_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos prve rate'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tip osiguranja'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj fakture'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum izdavanja'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='other_installments_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos ostalih rata'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naziv partnera'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='partner_pib',
            field=models.IntegerField(blank=True, null=True, verbose_name='PIB partnera'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj polise'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Iznos premije'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum početka'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
