# Generated by Django 5.0.9 on 2026-07-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0070_migrate_draft_policies_to_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftPolicy',
        ),
    ]
