# Generated by Codex on 2026-08-03

from django.db import migrations, models


def grant_task_history_permission(apps, schema_editor):
    PermissionCode = apps.get_model("fleet", "PermissionCode")
    Role = apps.get_model("fleet", "Role")
    RolePermission = apps.get_model("fleet", "RolePermission")

    permission, _ = PermissionCode.objects.get_or_create(
        code="task_history_list",
        defaults={"label": "Task history"},
    )
    role, _ = Role.objects.get_or_create(
        slug="uprava",
        defaults={"name": "Uprava", "is_active": True},
    )
    RolePermission.objects.get_or_create(role=role, permission=permission)


def remove_task_history_permission(apps, schema_editor):
    PermissionCode = apps.get_model("fleet", "PermissionCode")
    PermissionCode.objects.filter(code="task_history_list").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0071_delete_draftpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.CharField(max_length=255, unique=True, verbose_name="Task ID")),
                ("task_name", models.CharField(db_index=True, max_length=255, verbose_name="Task")),
                ("display_name", models.CharField(blank=True, max_length=255, verbose_name="Naziv")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Pokrenut"),
                            ("success", "Uspesan"),
                            ("skipped", "Preskocen"),
                            ("failure", "Neuspesan"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("short_message", models.CharField(blank=True, max_length=500, verbose_name="Kratko obavestenje")),
                ("result", models.TextField(blank=True, verbose_name="Rezultat")),
                ("error", models.TextField(blank=True, verbose_name="Greska")),
                ("args", models.JSONField(blank=True, default=list, verbose_name="Argumenti")),
                ("kwargs", models.JSONField(blank=True, default=dict, verbose_name="Keyword argumenti")),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Pocetak")),
                ("finished_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Kraj")),
                ("elapsed_seconds", models.FloatField(blank=True, null=True, verbose_name="Trajanje u sekundama")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Detalji")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Kreirano")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Azurirano")),
            ],
            options={
                "verbose_name": "Task history",
                "verbose_name_plural": "Task history",
                "db_table": "fleet_task_history",
                "ordering": ["-started_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "-started_at"], name="fleet_task__status_6a9a4e_idx"),
                    models.Index(fields=["task_name", "-started_at"], name="fleet_task__task_na_001578_idx"),
                ],
            },
        ),
        migrations.RunPython(grant_task_history_permission, remove_task_history_permission),
    ]
