# Generated by Django 5.0.9 on 2026-09-10 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0072_taskhistory'),
        ('ugovori', '0011_restore_contract_file_separation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('owned', 'Vlasništvo IMS'), ('contract', 'Korišćenje po ugovoru')], max_length=20, verbose_name='Osnov raspolaganja')),
                ('start_date', models.DateField(verbose_name='Važi od')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Važi do (uključivo)')),
                ('financing', models.CharField(blank=True, choices=[('', 'Nije evidentirano'), ('own_funds', 'Sopstvena sredstva'), ('credit', 'Kredit')], max_length=20, verbose_name='Finansiranje nabavke')),
                ('evidence', models.CharField(blank=True, max_length=255, verbose_name='Dokument / osnov promene')),
                ('note', models.TextField(blank=True, verbose_name='Napomena')),
            ],
            options={
                'verbose_name': 'Osnov raspolaganja vozilom',
                'verbose_name_plural': 'Osnovi raspolaganja vozilima',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='trafficcard',
            options={'ordering': ['-issue_date', '-id']},
        ),
        migrations.AddField(
            model_name='lease',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_leases', to='ugovori.contract', verbose_name='Ugovor iz evidencije Ugovori'),
        ),
        migrations.AddField(
            model_name='trafficcard',
            name='registration_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Registracija važi do'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='homologation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Homologacioni broj'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='homologation_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Homologacioni broj — prethodna evidencija'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Registracioni broj mora biti u formatu AA999-AA ili AA9999-AA', regex='^[A-Z]{2}\\d{3,4}-[A-Z]{2}$')], verbose_name='Registracioni broj'),
        ),
        migrations.AlterField(
            model_name='trafficcard',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Rok važenja saobraćajne (ako je naveden)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Boja'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Broj motora'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Snaga motora (kW)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Zapremina motora (cm³)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum prve registracije'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vrsta goriva'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Inventarski broj'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Broj fakture'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nosivost (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='maximum_permissible_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimalna dozvoljena masa (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_axles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj osovina'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Broj sedišta'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra partnera'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naziv partnera'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum nabavke'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nabavna vrednost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Knjigovodstvena vrednost'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Masa (kg)'),
        ),
        migrations.AddIndex(
            model_name='trafficcard',
            index=models.Index(fields=['vehicle', '-issue_date', '-id'], name='traffic_vehicle_issued_idx'),
        ),
        migrations.AddField(
            model_name='vehicleholding',
            name='financing_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_holdings', to='ugovori.contract', verbose_name='Ugovor o finansiranju'),
        ),
        migrations.AddField(
            model_name='vehicleholding',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='fleet.lease', verbose_name='Lizing / najam'),
        ),
        migrations.AddField(
            model_name='vehicleholding',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AddConstraint(
            model_name='vehicleholding',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='holding_dates_order'),
        ),
    ]
