# Generated by Django 5.0.9 on 2026-09-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0074_vehicle_onboarding_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicles/photos/%Y/%m/', verbose_name='Slika vozila'),
        ),
    ]
