# Generated by Django 5.0.9 on 2026-09-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0075_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='recipient_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Šifra vrste primaoca'),
        ),
        migrations.AddField(
            model_name='employee',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vrsta primaoca iz HR-a'),
        ),
    ]
