# Generated by Django 5.0.9 on 2026-09-19 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0076_employee_recipient_code_employee_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletravelorder',
            name='job_code',
            field=models.ForeignKey(blank=True, help_text='Jedan nalog pripada jednom poslu. Prazno znači da pripadnost još nije potvrđena.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_usage_orders', to='fleet.organizationalunit', verbose_name='Troškovi na teret šifre posla'),
        ),
        migrations.CreateModel(
            name='LeaseChargePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Važi od')),
                ('end', models.DateField(verbose_name='Važi do (uključivo)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iznos RSD')),
                ('basis', models.CharField(choices=[('monthly', 'Mesečna naknada'), ('total', 'Ukupno za ovaj period')], max_length=10, verbose_name='Značenje iznosa')),
                ('evidence', models.CharField(max_length=500, verbose_name='Dokument, obuhvat usluga i poreska osnova')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_charges', to='fleet.lease', verbose_name='Ugovor')),
            ],
            options={
                'ordering': ['start', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAnalysisProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Važi od')),
                ('purpose', models.CharField(choices=[('laboratory', 'Prevoz laboratorijske ekipe i opreme'), ('supervision', 'Nadzor i terenski rad'), ('management', 'Uprava i poslovna mobilnost'), ('transport', 'Transport mašina i kontejnera'), ('drilling', 'Vozilo sa bušećom mašinom'), ('towing', 'Prevoz / vuča SPT i druge opreme'), ('trailer', 'Priključno vozilo')], max_length=24, verbose_name='Poslovna namena')),
                ('criticality', models.CharField(blank=True, max_length=500, verbose_name='Zahtev raspoloživosti / razlog zadržavanja')),
                ('fuel_source', models.CharField(choices=[('transactions', 'NIS / OMV transakcije'), ('legacy', 'Ranija evidencija goriva')], default='transactions', max_length=16, verbose_name='Izvor goriva za analizu')),
                ('criterion_basis', models.CharField(blank=True, choices=[('owned', 'Vlasništvo IMS'), ('finansijski', 'Finansijski lizing'), ('operativni', 'Operativni lizing'), ('dugorocni', 'Dugoročni najam')], max_length=16, verbose_name='Raspolaganje za koje važi kriterijum')),
                ('cost_limit_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kontrolni prag RSD/km')),
                ('cost_limit_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kontrolni prag RSD/dan po nalogu')),
                ('criterion_source', models.TextField(blank=True, help_text='Navesti izvor, datum, namenu i zašto je prag uporediv sa obuhvaćenim troškovima. Prag je signal za pregled, ne odluka o zameni.', verbose_name='Osnov kriterijuma i obuhvat troškova')),
                ('note', models.TextField(blank=True, verbose_name='Napomena o podacima i režimu rada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'Profil analitike vozila',
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Neupotrebljivo od')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Poslednji dan neupotrebljivosti')),
                ('reason', models.CharField(max_length=200, verbose_name='Uzrok')),
                ('note', models.TextField(blank=True, verbose_name='Dokaz / napomena')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.kvar', verbose_name='Prijava / intervencija')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEconomicAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum procene')),
                ('title', models.CharField(max_length=160, verbose_name='Naziv procene')),
                ('years', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Zajednički horizont (godine)')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Realna diskontna stopa (%)')),
                ('annual_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Planirani km godišnje')),
                ('annual_days', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(366)], verbose_name='Planirani dani angažovanja godišnje')),
                ('scope', models.TextField(verbose_name='Isti posao, kapacitet, raspoloživost i obuhvat svih alternativa')),
                ('assumptions', models.TextField(verbose_name='Izvori cena, poreska osnova i pretpostavke')),
                ('snapshot', models.JSONField(default=dict, editable=False)),
                ('methodology_version', models.CharField(default='IMS-FLOTA-2.0', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-as_of', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEconomicScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Alternativa')),
                ('kind', models.CharField(choices=[('keep', 'Zadržavanje'), ('buy', 'Kupovina / zamena'), ('lease', 'Lizing / najam'), ('outsource', 'Spoljna usluga')], max_length=16, verbose_name='Vrsta')),
                ('initial_cost', models.DecimalField(decimal_places=2, help_text='Zadržavanje: današnja tržišna vrednost. Kupovina: nabavka i priprema. Najam: nepovratni početni izdaci. Bez ponovnog dodavanja glavnice.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Početna vrednost / nepovratni početni izdatak RSD')),
                ('annual_cost', models.DecimalField(decimal_places=2, help_text='Stalan godišnji iznos u današnjim cenama za zajednički plan rada. Uključiti rad, održavanje, osiguranje i ugovorne naknade po potrebi. Ne dodavati amortizaciju ni kamatu već obuhvaćenu kapitalnim modelom.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Svi godišnji budući troškovi RSD')),
                ('residual_value', models.DecimalField(decimal_places=2, help_text='Prodajna vrednost umanjena za trošak prodaje; za najam / spoljnu uslugu najčešće 0.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Neto preostala vrednost na kraju RSD')),
                ('feasible', models.BooleanField(default=False, verbose_name='Potvrđeno ispunjava isti posao i zahteve raspoloživosti')),
                ('evidence', models.TextField(verbose_name='Ponuda / procena i obrazloženje troškova')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='fleet.vehicleeconomicassessment')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleanalysisprofile',
            constraint=models.UniqueConstraint(fields=('vehicle', 'effective_from'), name='unique_vehicle_analysis_date'),
        ),
    ]
