# Generated by Django 5.0.9 on 2026-09-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0079_pravna_permission_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name_cyrillic',
            field=models.CharField(blank=True, default='', help_text='Koristi se u rešenjima koja se štampaju ćirilicom. Ostavi prazno za automatsko preslovljavanje, koje ume da pogreši kod slova lj, nj i dž.', max_length=150, verbose_name='Ime i prezime (ćirilica)'),
        ),
    ]
