# Generated by Django 5.0.9 on 2026-09-25 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0081_customuser_allowed_hr_unit_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slava_dan',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Datum slave - dan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='slava_mesec',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Npr. Sveti Nikola: dan 19, mesec 12. Ako je prazno, radna lista predlaže datum iz naziva slave.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Datum slave - mesec'),
        ),
    ]
