# Generated by Django 5.0.9 on 2026-09-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0083_employee_slava_jedan_datum'),
        ('organizacija', '0003_dozvola_organizaciona_sema'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsumption',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_gorivo', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='jobcode',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_dodele', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='lease',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_lizinzi', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_zahtevi_nabavke', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='putninalog',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_putni_nalozi', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='vehicletravelorder',
            name='org_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_nalozi_vozila', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
    ]
