# Generated by Django 5.0.9 on 2026-09-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0084_veza_sa_registrom_organizacije'),
        ('organizacija', '0006_nauka_deo_bloka_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelconsumption',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_gorivo', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AlterField(
            model_name='jobcode',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_dodele', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_lizinzi', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_zahtevi_nabavke', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AlterField(
            model_name='putninalog',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_putni_nalozi', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AlterField(
            model_name='vehicletravelorder',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_nalozi_vozila', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
    ]
