# Generated by Django 5.0.9 on 2026-09-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0085_org_node_bez_forme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_hr_unit_codes',
        ),
    ]
