# Generated by Django 5.0.9 on 2026-09-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0086_bez_kadrovskih_oj'),
        ('organizacija', '0009_dodela_daje_ulogu'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zaposleni', to='organizacija.orgnode', verbose_name='Organizaciona jedinica (registar)'),
        ),
    ]
