# Generated by Django 5.0.9 on 2026-09-29 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0087_zaposleni_u_registru'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='prilog',
            field=models.FileField(blank=True, max_length=255, upload_to='fleet/incidenti/%Y/%m/', verbose_name='Prilog'),
        ),
        migrations.AddField(
            model_name='incident',
            name='prilog_naziv',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Naziv priloga'),
        ),
        migrations.AddField(
            model_name='incident',
            name='uneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uneti_incidenti', to=settings.AUTH_USER_MODEL, verbose_name='Uneo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='uneto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uneto'),
        ),
    ]
