# Generated by Django 5.0.9 on 2026-09-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0088_incident_prilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpomenaGoriva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izvor', models.CharField(choices=[('nis', 'NIS'), ('omv', 'OMV')], max_length=5)),
                ('transakcija_id', models.BigIntegerField(verbose_name='Točenje (ID u tabeli izvora)')),
                ('vreme_tocenja', models.DateTimeField(verbose_name='Vreme točenja')),
                ('stanica', models.CharField(blank=True, default='', max_length=255, verbose_name='Stanica')),
                ('kolicina', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Količina (l)')),
                ('vrsta', models.CharField(choices=[('bez_km', 'Kilometraža nije uneta'), ('manja', 'Manja od prethodnog točenja'), ('skok', 'Nerealan skok kilometraže'), ('ista', 'Ista kao prethodno točenje')], db_index=True, max_length=10, verbose_name='Nepravilnost')),
                ('uneta_km', models.IntegerField(blank=True, null=True, verbose_name='Uneta kilometraža')),
                ('prethodna_km', models.IntegerField(blank=True, null=True, verbose_name='Prethodno točenje (km)')),
                ('prethodni_datum', models.DateField(blank=True, null=True, verbose_name='Prethodno točenje (datum)')),
                ('vozac_izvor', models.CharField(blank=True, default='', max_length=120, verbose_name='Odakle je vozač')),
                ('poruka', models.TextField(verbose_name='Tekst opomene')),
                ('status', models.CharField(choices=[('za_slanje', 'Pripremljena'), ('poslata', 'Poslata'), ('bez_vozaca', 'Vozač nije poznat'), ('bez_kontakta', 'Vozač nema kontakt'), ('greska', 'Greška pri slanju')], db_index=True, default='za_slanje', max_length=15)),
                ('kanal', models.CharField(blank=True, default='', max_length=20, verbose_name='Kanal')),
                ('poslato', models.DateTimeField(blank=True, null=True, verbose_name='Poslato')),
                ('greska', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opomene_goriva', to='fleet.employee', verbose_name='Vozač')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opomene_goriva', to='fleet.vehicle', verbose_name='Vozilo')),
            ],
            options={
                'verbose_name': 'Opomena za gorivo',
                'verbose_name_plural': 'Opomene za gorivo',
                'db_table': 'fleet_opomena_goriva',
                'ordering': ['-vreme_tocenja', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='opomenagoriva',
            constraint=models.UniqueConstraint(fields=('izvor', 'transakcija_id'), name='fleet_opomena_jedno_tocenje'),
        ),
    ]
