# Generated by Django 5.0.9 on 2026-10-06 13:33

import django.db.models.deletion
from django.db import migrations, models


def _jmbg(vrednost):
    return "".join(z for z in str(vrednost or "") if z.isdigit())


def popuni_osobe(apps, schema_editor):
    """Osoba po JMBG-u za postojeće zaposlene; bez JMBG-a svako zaposlenje dobija svoju osobu.
    Glavno zaposlenje (aktivno, poslednji prijem) daje ime; ime za prikaz i ćirilica — prvo upisano."""
    Employee = apps.get_model("fleet", "Employee")
    Osoba = apps.get_model("fleet", "Osoba")
    grupe = {}
    for e in Employee.objects.all():
        kljuc = _jmbg(e.personal_number) or f"bez-{e.pk}"
        grupe.setdefault(kljuc, []).append(e)
    for kljuc, zaposlenja in grupe.items():
        zaposlenja.sort(key=lambda e: (not e.is_active, -(e.date_of_joining.toordinal() if e.date_of_joining else 0),
                                       -e.employee_code))
        glavno = zaposlenja[0]
        prvo = lambda polje: next((getattr(e, polje) for e in zaposlenja if getattr(e, polje)), "")
        osoba = Osoba.objects.create(
            jmbg="" if kljuc.startswith("bez-") else kljuc, titula=glavno.title or "", ime=glavno.first_name or "",
            prezime=glavno.last_name or "", pol=glavno.gender or "", datum_rodjenja=glavno.date_of_birth,
            ime_za_prikaz=prvo("display_first_name_override"), prezime_za_prikaz=prvo("display_last_name_override"),
            ime_cirilica=prvo("full_name_cyrillic"))
        Employee.objects.filter(pk__in=[e.pk for e in zaposlenja]).update(
            osoba=osoba, display_first_name_override=osoba.ime_za_prikaz,
            display_last_name_override=osoba.prezime_za_prikaz, full_name_cyrillic=osoba.ime_cirilica)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0090_raspolaganje_iz_ugovora'),
        ('organizacija', '0009_dodela_daje_ulogu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmbg', models.CharField(blank=True, default='', help_text='Prazno ako JMBG nije upisan u kadrovskoj bazi.', max_length=13, verbose_name='JMBG')),
                ('titula', models.CharField(blank=True, default='', max_length=20, verbose_name='Titula')),
                ('ime', models.CharField(blank=True, default='', max_length=50, verbose_name='Ime')),
                ('prezime', models.CharField(blank=True, default='', max_length=50, verbose_name='Prezime')),
                ('pol', models.CharField(blank=True, default='', max_length=1, verbose_name='Pol')),
                ('datum_rodjenja', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('ime_za_prikaz', models.CharField(blank=True, default='', max_length=50, verbose_name='Ime za prikaz')),
                ('prezime_za_prikaz', models.CharField(blank=True, default='', max_length=50, verbose_name='Prezime za prikaz')),
                ('ime_cirilica', models.CharField(blank=True, default='', max_length=150, verbose_name='Ime i prezime (ćirilica)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osobe',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='preduzece',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Radni odnos'), (2, 'Van radnog odnosa')], default=1, verbose_name='Preduzeće'),
        ),
        migrations.AddField(
            model_name='employee',
            name='u_izvoru',
            field=models.BooleanField(default=True, help_text='Isključeno kad broj radnika nestane iz kadrovske baze.', verbose_name='Postoji u kadrovskoj bazi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.IntegerField(verbose_name='Šifra zaposlenog'),
        ),
        migrations.AddConstraint(
            model_name='osoba',
            constraint=models.UniqueConstraint(condition=models.Q(('jmbg__gt', '')), fields=('jmbg',), name='fleet_osoba_jmbg_jedinstven'),
        ),
        migrations.AddField(
            model_name='employee',
            name='osoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zaposlenja', to='fleet.osoba', verbose_name='Osoba'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('preduzece', 'employee_code'), name='fleet_employee_preduzece_broj'),
        ),
        migrations.RunPython(popuni_osobe, migrations.RunPython.noop),
    ]
