# Generated by Django 5.0.9 on 2026-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0091_osoba_i_zaposlenja'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='staz_dana',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ukupan staž — dana'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_godina',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ukupan staž — godina'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_ims_dana',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Staž u IMS — dana'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_ims_godina',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Staž u IMS — godina'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_ims_meseci',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Staž u IMS — meseci'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_meseci',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ukupan staž — meseci'),
        ),
        migrations.AddField(
            model_name='osoba',
            name='staz_preuzet',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Staž preuzet iz kadrovske baze'),
        ),
    ]
