# Generated by Django 5.0.9 on 2026-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0092_staz_osobe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionomv',
            name='unique_omv_transaction_line',
        ),
        migrations.AddConstraint(
            model_name='transactionomv',
            constraint=models.UniqueConstraint(fields=('license_plate_no', 'transaction_date', 'product_inv', 'voucher', 'quantity', 'card', 'gross_cc'), name='unique_omv_transaction_line_card_amount'),
        ),
    ]
