# Generated by Django 5.0.9 on 2026-10-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0093_omv_stavka_kartica_iznos'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='radna_mesta',
            field=models.JSONField(blank=True, default=list, verbose_name='Radna mesta'),
        ),
    ]
