# Generated by Django 5.0.9 on 2026-10-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0094_zaposleni_radna_mesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcitanaNovost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kljuc', models.CharField(max_length=60, verbose_name='Novost')),
                ('procitano', models.DateTimeField(auto_now_add=True, verbose_name='Potvrđeno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procitane_novosti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pročitana novost',
                'verbose_name_plural': 'Pročitane novosti',
                'db_table': 'fleet_procitana_novost',
            },
        ),
        migrations.AddConstraint(
            model_name='procitananovost',
            constraint=models.UniqueConstraint(fields=('user', 'kljuc'), name='fleet_procitana_novost_jednom'),
        ),
    ]
