# Generated by Django 5.0.9 on 2026-08-19 08:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0072_taskhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Godina')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mesec')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Broj')),
                ('number_active', models.BooleanField(default=True, verbose_name='Aktivan broj')),
                ('package_name', models.CharField(blank=True, max_length=100, verbose_name='Paket - naziv')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Paket od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Paket do')),
                ('package_net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Paket neto')),
                ('employee_code', models.IntegerField(blank=True, null=True, verbose_name='Sifra radnika')),
                ('employee_name', models.CharField(blank=True, max_length=150, verbose_name='Radnik')),
                ('employee_active', models.BooleanField(default=True, verbose_name='Aktivan radnik')),
                ('personal_number', models.CharField(blank=True, max_length=13, verbose_name='JMBG')),
                ('note', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Dodela mobilnog broja',
                'verbose_name_plural': 'Dodele mobilnih brojeva',
                'ordering': ['-year', '-month', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='MobilePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(blank=True, max_length=20, verbose_name='Sifra partnera')),
                ('partner_name', models.CharField(blank=True, max_length=150, verbose_name='Partner')),
                ('name', models.CharField(max_length=100, verbose_name='Paket')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vazi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vazi do')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Iznos neto')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Iznos bruto')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Mobilni paket',
                'verbose_name_plural': 'Mobilni paketi',
                'ordering': ['name', 'valid_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MobileUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Godina')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mesec')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Broj')),
                ('onnet', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mts_network', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='U MTS mrezi')),
                ('outside_mts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Van MTS mreze')),
                ('kim', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ka KIM')),
                ('special', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ka specijalnim')),
                ('international', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Internacionalni')),
                ('roaming', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Roaming')),
                ('gprs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GPRS')),
                ('sms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SMS')),
                ('sms_international', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SMS internac.')),
                ('sms_roaming', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SMS u roamingu')),
                ('mms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='MMS')),
                ('vas_sms', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='VAS SMS')),
                ('discount_traffic', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saobracaj za popust')),
                ('fixed_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fiksni popust')),
                ('variable_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Varijabilni popust')),
                ('services', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Usluge')),
                ('dispatch_notes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otpremnice')),
                ('parking', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Parking')),
                ('nzrd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='NZRD')),
                ('vat_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Osnovica za PDV')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PDV')),
                ('installments', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Placanje na rate')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ukupno za naplatu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Potrosnja mobilnog',
                'verbose_name_plural': 'Potrosnja mobilnih',
                'ordering': ['-year', '-month', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_unit', models.CharField(blank=True, max_length=20, verbose_name='OJ')),
                ('employee_code', models.IntegerField(unique=True, verbose_name='Sifra radnika')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ime i prezime')),
                ('personal_number', models.CharField(blank=True, max_length=13, verbose_name='JMBG')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Datum odlaska')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Korisnik mobilnog',
                'verbose_name_plural': 'Korisnici mobilnih',
                'ordering': ['full_name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='MobileImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('packages', 'Paketi'), ('users', 'Korisnici'), ('assignments', 'Dodele'), ('usages', 'Potrosnja')], max_length=20, verbose_name='Tip importa')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Godina')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mesec')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Fajl')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='Uvezeno')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Azurirano')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Preskoceno')),
                ('error_message', models.TextField(blank=True, verbose_name='Greska')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
            ],
            options={
                'verbose_name': 'Log importa mobilnih',
                'verbose_name_plural': 'Logovi importa mobilnih',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mobilepackage',
            constraint=models.UniqueConstraint(fields=('partner_code', 'name', 'valid_from'), name='uniq_mobilni_package_partner_name_from'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='mobilni.mobilepackage', verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='mobileusage',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='mobilni.mobileassignment', verbose_name='Dodela'),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_users', to='fleet.employee', verbose_name='Zaposleni'),
        ),
        migrations.AddField(
            model_name='mobileassignment',
            name='mobile_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='mobilni.mobileuser', verbose_name='Korisnik mobilnog'),
        ),
        migrations.AddIndex(
            model_name='mobileusage',
            index=models.Index(fields=['year', 'month'], name='mobilni_mob_year_45af8f_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileusage',
            index=models.Index(fields=['phone_number'], name='mobilni_mob_phone_n_ae4c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobileusage',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'phone_number'), name='uniq_mobilni_usage_period_number'),
        ),
        migrations.AddIndex(
            model_name='mobileuser',
            index=models.Index(fields=['employee_code'], name='mobilni_mob_employe_9c9924_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileuser',
            index=models.Index(fields=['full_name'], name='mobilni_mob_full_na_c56126_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileassignment',
            index=models.Index(fields=['year', 'month'], name='mobilni_mob_year_18d81f_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileassignment',
            index=models.Index(fields=['phone_number'], name='mobilni_mob_phone_n_3705cf_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileassignment',
            index=models.Index(fields=['employee_code'], name='mobilni_mob_employe_159bf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='mobileassignment',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'phone_number'), name='uniq_mobilni_assignment_period_number'),
        ),
    ]
