# Generated by Django 5.0.9 on 2026-08-19 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0072_taskhistory'),
        ('mobilni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_assignments', to='fleet.employee', verbose_name='Zaposleni'),
        ),
        migrations.AddField(
            model_name='mobileusage',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_usages', to='fleet.employee', verbose_name='Zaposleni'),
        ),
        migrations.AddIndex(
            model_name='mobileassignment',
            index=models.Index(fields=['employee'], name='mobilni_mob_employe_18f38d_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileusage',
            index=models.Index(fields=['employee'], name='mobilni_mob_employe_72b220_idx'),
        ),
    ]
