# Generated by Django 5.0.9 on 2026-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilni", "0003_mobilepackage_contract"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobileusage",
            options={
                "ordering": ["-year", "-month", "phone_number"],
                "verbose_name": "Potrošnja mobilnog",
                "verbose_name_plural": "Potrošnja mobilnih",
            },
        ),
        migrations.AlterField(
            model_name="mobileassignment",
            name="employee_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Šifra radnika"),
        ),
        migrations.AlterField(
            model_name="mobileassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ažurirano"),
        ),
        migrations.AlterField(
            model_name="mobileimportlog",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Greška"),
        ),
        migrations.AlterField(
            model_name="mobileimportlog",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("packages", "Paketi"),
                    ("users", "Korisnici"),
                    ("assignments", "Dodele"),
                    ("usages", "Potrošnja"),
                ],
                max_length=20,
                verbose_name="Tip importa",
            ),
        ),
        migrations.AlterField(
            model_name="mobileimportlog",
            name="updated_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Ažurirano"),
        ),
        migrations.AlterField(
            model_name="mobilepackage",
            name="partner_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Šifra partnera"),
        ),
        migrations.AlterField(
            model_name="mobilepackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ažurirano"),
        ),
        migrations.AlterField(
            model_name="mobilepackage",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="Važi od"),
        ),
        migrations.AlterField(
            model_name="mobilepackage",
            name="valid_to",
            field=models.DateField(blank=True, null=True, verbose_name="Važi do"),
        ),
        migrations.AlterField(
            model_name="mobileusage",
            name="discount_traffic",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Saobraćaj za popust",
            ),
        ),
        migrations.AlterField(
            model_name="mobileusage",
            name="installments",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Plaćanje na rate",
            ),
        ),
        migrations.AlterField(
            model_name="mobileusage",
            name="mts_network",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="U MTS mreži",
            ),
        ),
        migrations.AlterField(
            model_name="mobileusage",
            name="outside_mts",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Van MTS mreže",
            ),
        ),
        migrations.AlterField(
            model_name="mobileusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ažurirano"),
        ),
        migrations.AlterField(
            model_name="mobileuser",
            name="employee_code",
            field=models.IntegerField(unique=True, verbose_name="Šifra radnika"),
        ),
        migrations.AlterField(
            model_name="mobileuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ažurirano"),
        ),
    ]
