# Generated by Django 5.0.9 on 2026-08-28 07:27

from django.db import migrations, models


def clean_phone_number(value):
    value = "" if value is None else str(value).strip()
    if value.endswith(".0"):
        value = value[:-2]
    return "".join(ch for ch in value if ch.isdigit()) or value


def backfill_existing_parking_exemptions(apps, schema_editor):
    MobileAssignment = apps.get_model("mobilni", "MobileAssignment")
    MobileParkingExemption = apps.get_model("mobilni", "MobileParkingExemption")
    exempt_employee_codes = [141, 647]

    phone_numbers = (
        MobileAssignment.objects.filter(employee_code__in=exempt_employee_codes)
        .exclude(phone_number="")
        .values_list("phone_number", flat=True)
        .distinct()
    )
    for phone_number in phone_numbers:
        phone_number = clean_phone_number(phone_number)
        if phone_number:
            MobileParkingExemption.objects.get_or_create(phone_number=phone_number)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mobilni', '0004_alter_mobileusage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileParkingExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True, verbose_name='Broj telefona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Izuzetak parkinga',
                'verbose_name_plural': 'Izuzeci parkinga',
                'ordering': ['phone_number'],
            },
        ),
        migrations.RunPython(backfill_existing_parking_exemptions, noop_reverse),
    ]
