# Generated by Django 5.0.9 on 2026-09-21 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('u toku', 'U toku'), ('zavrseno', 'Zavrseno'), ('prekinuto', 'Prekinuto')], default='u toku', max_length=20)),
                ('source_rows', models.IntegerField(default=0, verbose_name='Procitano iz izvora')),
                ('nodes_created', models.IntegerField(default=0)),
                ('versions_created', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('unresolved', models.IntegerField(default=0, verbose_name='Na listi za razresenje')),
                ('report', models.TextField(blank=True, verbose_name='Izvestaj')),
            ],
            options={
                'verbose_name': 'Uvoz organizacije',
                'verbose_name_plural': 'Uvozi organizacije',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField(verbose_name='Firma')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1 — centar'), (2, '2 — organizaciona jedinica'), (3, '3 — sifra posla')], verbose_name='Nivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organizacioni cvor',
                'verbose_name_plural': 'Organizacioni cvorovi',
                'indexes': [models.Index(fields=['company', 'level'], name='organizacij_company_102864_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegacyOrgLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_label', models.CharField(max_length=80, verbose_name='Stari model')),
                ('legacy_id', models.BigIntegerField(verbose_name='Primarni kljuc u starom modelu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_links', to='organizacija.orgnode')),
            ],
            options={
                'verbose_name': 'Veza sa starim modelom',
                'verbose_name_plural': 'Veze sa starim modelima',
            },
        ),
        migrations.CreateModel(
            name='ExternalOrgMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80, verbose_name='Izvor')),
                ('company', models.PositiveIntegerField(verbose_name='Firma')),
                ('source_key', models.CharField(max_length=60, verbose_name='Kljuc u izvoru')),
                ('raw_value', models.CharField(blank=True, help_text='Neobradjena, sa rubnim razmacima kakvi su u izvoru.', max_length=60, verbose_name='Sirova vrednost')),
                ('valid_from', models.DateField(verbose_name='Vazi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vazi do (iskljucivo)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_mappings', to='organizacija.orgnode')),
            ],
            options={
                'verbose_name': 'Veza sa spoljnom sifrom',
                'verbose_name_plural': 'Veze sa spoljnim siframa',
                'ordering': ['source', 'source_key'],
            },
        ),
        migrations.CreateModel(
            name='OrgNodeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=20, verbose_name='Segment sifre')),
                ('full_code', models.CharField(db_index=True, max_length=40, verbose_name='Puna sifra')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Naziv')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('is_profit', models.BooleanField(blank=True, help_text='Samo za treci nivo. Prazno znaci da oznaka nije poznata, ne da je neprofitan.', null=True, verbose_name='Profitni')),
                ('valid_from', models.DateField(verbose_name='Vazi od')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vazi do (iskljucivo)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='organizacija.orgnode')),
                ('parent', models.ForeignKey(blank=True, help_text='Prazno samo za prvi nivo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_versions', to='organizacija.orgnode', verbose_name='Nadredjeni cvor')),
            ],
            options={
                'verbose_name': 'Verzija cvora',
                'verbose_name_plural': 'Verzije cvorova',
                'ordering': ['full_code', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='UnresolvedOrgCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField(verbose_name='Firma')),
                ('code', models.CharField(max_length=40, verbose_name='Sifra')),
                ('raw_code', models.CharField(blank=True, max_length=40, verbose_name='Sirova sifra')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Naziv u izvoru')),
                ('source_center', models.CharField(blank=True, max_length=10, verbose_name='Centar u izvoru')),
                ('family', models.CharField(choices=[('B', 'B — nauka (zaseban sifarnik)'), ('C', 'C — izuzetak')], max_length=1)),
                ('reason', models.CharField(max_length=300, verbose_name='Razlog')),
                ('is_active', models.BooleanField(default=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_codes', to='organizacija.orgimportrun')),
            ],
            options={
                'verbose_name': 'Nerazresena sifra',
                'verbose_name_plural': 'Nerazresene sifre',
                'ordering': ['family', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='legacyorglink',
            constraint=models.UniqueConstraint(fields=('legacy_label', 'legacy_id'), name='orglegacy_label_id'),
        ),
        migrations.AddIndex(
            model_name='externalorgmapping',
            index=models.Index(fields=['source', 'source_key'], name='organizacij_source_97b285_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalorgmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('source', 'company', 'source_key'), name='orgmap_open_source_key'),
        ),
        migrations.AddIndex(
            model_name='orgnodeversion',
            index=models.Index(fields=['full_code', 'valid_from'], name='organizacij_full_co_63e6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgnodeversion',
            constraint=models.UniqueConstraint(fields=('node', 'valid_from'), name='orgver_node_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='orgnodeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('node',), name='orgver_one_open_per_node'),
        ),
        migrations.AddConstraint(
            model_name='orgnodeversion',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='orgver_valid_range'),
        ),
        migrations.AddIndex(
            model_name='unresolvedorgcode',
            index=models.Index(fields=['run', 'family'], name='organizacij_run_id_c256e9_idx'),
        ),
    ]
