# Generated by Django 5.0.9 on 2026-09-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobActivityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_from', models.DateField(verbose_name='Prozor od')),
                ('window_to', models.DateField(verbose_name='Prozor do')),
                ('has_turnover', models.BooleanField(verbose_name='Ima obrt u prozoru')),
                ('rows', models.IntegerField(default=0, verbose_name='Knjizenja u prozoru')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_review', to='organizacija.orgnode')),
            ],
            options={
                'verbose_name': 'Nalaz o obrtu',
                'verbose_name_plural': 'Nalazi o obrtu',
                'ordering': ['node_id'],
            },
        ),
    ]
