# Generated by Django 5.0.9 on 2026-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacija', '0005_centri_2_i_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unresolvedorgcode',
            name='family',
            field=models.CharField(choices=[('B', 'B — nauka (deo bloka 3)'), ('C', 'C — izuzetak')], max_length=1),
        ),
    ]
