# Generated by Django 5.0.9 on 2026-09-25 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0085_org_node_bez_forme'),
        ('organizacija', '0006_nauka_deo_bloka_3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPutanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centar_sifra', models.CharField(max_length=40, verbose_name='Oznaka centra')),
                ('vazi_od', models.DateField(verbose_name='Vazi od')),
                ('vazi_do', models.DateField(blank=True, null=True, verbose_name='Vazi do (iskljucivo)')),
                ('centar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putanje_centra', to='organizacija.orgnode')),
                ('jedinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putanje_jedinice', to='organizacija.orgnode')),
                ('posao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putanje', to='organizacija.orgnode')),
            ],
            options={
                'verbose_name': 'Putanja sifre posla',
                'verbose_name_plural': 'Putanje sifara posla',
            },
        ),
        migrations.CreateModel(
            name='DodelaUloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cela_firma', models.BooleanField(default=False, verbose_name='Obuhvat: cela firma')),
                ('vazi_od', models.DateField(verbose_name='Vazi od')),
                ('vazi_do', models.DateField(blank=True, null=True, verbose_name='Vazi do (iskljucivo)')),
                ('status', models.CharField(choices=[('nacrt', 'Nacrt'), ('aktivna', 'Aktivna')], default='nacrt', max_length=10)),
                ('izvor', models.CharField(choices=[('prevod', 'Prevod starih prava'), ('rucno', 'Ručno')], default='rucno', max_length=10)),
                ('napomena', models.CharField(blank=True, max_length=300, verbose_name='Odakle je dodela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cvor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dodele_uloga', to='organizacija.orgnode', verbose_name='Obuhvat (cvor)')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodele_uloga', to=settings.AUTH_USER_MODEL)),
                ('uloga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodele', to='fleet.role')),
            ],
            options={
                'verbose_name': 'Dodela uloge sa obuhvatom',
                'verbose_name_plural': 'Dodele uloga sa obuhvatom',
                'indexes': [models.Index(fields=['korisnik', 'status'], name='organizacij_korisni_d560b2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dodelauloge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cela_firma', True), ('cvor__isnull', True)), models.Q(('cela_firma', False), ('cvor__isnull', False)), _connector='OR'), name='orgdodela_cvor_ili_firma'),
        ),
        migrations.AddIndex(
            model_name='orgputanja',
            index=models.Index(fields=['posao', 'vazi_od'], name='organizacij_posao_i_adaaff_idx'),
        ),
        migrations.AddIndex(
            model_name='orgputanja',
            index=models.Index(fields=['centar', 'vazi_od'], name='organizacij_centar__2eebb1_idx'),
        ),
    ]
