# Generated by Django 5.0.9 on 2026-09-25 14:58
"""Ekran dodela uloga (plan prelaska na registar, korak 3): ko je odobrio i opozvao dodelu,
i dozvole za ekran. Dozvole dobija samo uloga Uprava."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DOZVOLE = {
    'organizacija:dodele': 'Organizacija — dodele uloga (spisak)',
    'organizacija:dodele_korisnika': 'Organizacija — dodele uloga korisnika (pregled i nova dodela)',
    'organizacija:dodele_odobri': 'Organizacija — odobravanje nacrta dodela',
    'organizacija:dodela_opozovi': 'Organizacija — opoziv dodele',
}


def dodaj_dozvole(apps, schema_editor):
    Permission = apps.get_model('fleet', 'PermissionCode')
    Role = apps.get_model('fleet', 'Role')
    RolePermission = apps.get_model('fleet', 'RolePermission')
    db = schema_editor.connection.alias
    uprava = Role.objects.using(db).filter(slug='uprava').first()
    for kod, naziv in DOZVOLE.items():
        dozvola, _ = Permission.objects.using(db).get_or_create(code=kod, defaults={'label': naziv})
        if uprava:
            RolePermission.objects.using(db).get_or_create(role_id=uprava.pk, permission_id=dozvola.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('organizacija', '0007_putanja_i_dodele_uloga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dodelauloge',
            name='odobreno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dodelauloge',
            name='odobrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dodelauloge',
            name='opozvano',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dodelauloge',
            name='opozvao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(dodaj_dozvole, migrations.RunPython.noop),
    ]
