# Generated by Django 5.0.9 on 2026-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacija', '0008_dodele_odobravanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='dodelauloge',
            name='dodala_ulogu',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
