# Generated by Django 5.0.9 on 2026-05-26 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_trafficcard_traffic_card_back_image_and_more'),
        ('nabavka', '0002_procurementcase_is_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementcase',
            name='fleet_procurement_request',
        ),
        migrations.AlterField(
            model_name='procurementcase',
            name='case_type',
            field=models.CharField(choices=[('nabavka', 'Zahtev za nabavku'), ('usluga', 'Zahtev za uslugu'), ('oprema', 'Predlog za nabavku opreme')], db_index=True, default='nabavka', max_length=30, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='procurementcase',
            name='job_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_cases', to='fleet.organizationalunit', verbose_name='OJ / šifra posla'),
        ),
    ]
