# Generated by Django 5.0.9 on 2026-05-26 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0003_remove_procurementcase_fleet_procurement_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementItemInvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
            ],
            options={
                'verbose_name': 'Veza stavke i fakture',
                'verbose_name_plural': 'Veze stavki i faktura',
                'db_table': 'nabavka_item_invoice_link',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('euf', 'EUF')], db_index=True, default='euf', max_length=20, verbose_name='Izvor')),
                ('euf_key', models.CharField(db_index=True, max_length=64, verbose_name='EUF kljuc')),
                ('invoice_number', models.CharField(db_index=True, max_length=100, verbose_name='Broj fakture')),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum fakture')),
                ('invoice_date_raw', models.CharField(blank=True, max_length=50, null=True, verbose_name='Datum iz izvora')),
                ('supplier_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Naziv partnera')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Iznos')),
                ('center', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centar')),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magacin')),
                ('registration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registracija')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinhronizovano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Faktura nabavke',
                'verbose_name_plural': 'Fakture nabavke',
                'db_table': 'nabavka_invoice',
                'ordering': ['-invoice_date', '-id'],
                'indexes': [models.Index(fields=['invoice_number', 'supplier_name'], name='nabavka_inv_invoice_502f47_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='procurementinvoice',
            constraint=models.UniqueConstraint(fields=('source', 'euf_key'), name='uniq_nabavka_invoice_source_key'),
        ),
        migrations.AddField(
            model_name='procurementiteminvoicelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_item_invoice_links', to=settings.AUTH_USER_MODEL, verbose_name='Povezao'),
        ),
        migrations.AddField(
            model_name='procurementiteminvoicelink',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='nabavka.procurementinvoice', verbose_name='Faktura'),
        ),
        migrations.AddField(
            model_name='procurementiteminvoicelink',
            name='procurement_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_link', to='nabavka.procurementitem', verbose_name='Stavka nabavke'),
        ),
    ]
