# Generated by Django 5.0.9 on 2026-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0004_procurementiteminvoicelink_procurementinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementinvoice',
            name='center_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Naziv centra'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='goes_to_warehouse',
            field=models.BooleanField(default=False, verbose_name='Ide u magacin'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='internal_note',
            field=models.TextField(blank=True, null=True, verbose_name='Interna napomena'),
        ),
    ]
