# Generated by Django 5.0.9 on 2026-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0006_backfill_procurement_invoice_control_fields'),
        ('ugovori', '0007_contract_has_guarantees_contract_has_incoming_menice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementInvoiceContractLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nabavka_invoice_links', to='ugovori.contract', verbose_name='Kupovni ugovor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_invoice_contract_links', to=settings.AUTH_USER_MODEL, verbose_name='Povezao')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_links', to='nabavka.procurementinvoice', verbose_name='Faktura')),
            ],
            options={
                'verbose_name': 'Veza fakture i ugovora',
                'verbose_name_plural': 'Veze faktura i ugovora',
                'db_table': 'nabavka_invoice_contract_link',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='procurementinvoicecontractlink',
            constraint=models.UniqueConstraint(fields=('invoice', 'contract'), name='uniq_nabavka_invoice_contract'),
        ),
    ]
