# Generated by Django 5.0.9 on 2026-05-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0053_trafficcard_traffic_card_back_image_and_more'),
        ('nabavka', '0007_procurementinvoicecontractlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementinvoice',
            name='is_garage',
            field=models.BooleanField(default=False, verbose_name='Garaza'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='job_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_invoices', to='fleet.organizationalunit', verbose_name='OJ / sifra posla'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_invoices', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
    ]
