# Generated by Django 5.0.9 on 2026-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0008_procurementinvoice_is_garage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EufItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True, verbose_name='Kljuc izvora')),
                ('purchase_invoice_id', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='UF ID')),
                ('creation_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum kreiranja')),
                ('document_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum dokumenta')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Datum dospeca')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('contract_document_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referenca ugovora')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='Broj fakture')),
                ('tender_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj tendera')),
                ('partner_pib', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='PIB partnera')),
                ('partner_mb', models.CharField(blank=True, max_length=20, null=True, verbose_name='MB partnera')),
                ('partner_name', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='Partner')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ukupno')),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Osnovica')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Placanje')),
                ('uom', models.CharField(blank=True, max_length=10, null=True, verbose_name='JM')),
                ('item_name', models.TextField(blank=True, null=True, verbose_name='Naziv stavke')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Kolicina')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Cena')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Vrednost')),
                ('account', models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='Konto')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinhronizovano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'UF stavka',
                'verbose_name_plural': 'UF stavke',
                'db_table': 'nabavka_euf_item_snapshot',
                'ordering': ['-document_date', '-id'],
                'indexes': [models.Index(fields=['invoice_number', 'partner_name'], name='nabavka_euf_invoice_803b42_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoodsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True, verbose_name='Kljuc izvora')),
                ('year', models.CharField(blank=True, db_index=True, max_length=4, null=True, verbose_name='Godina')),
                ('document_number', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Broj dokumenta')),
                ('document_type', models.CharField(blank=True, db_index=True, max_length=3, null=True, verbose_name='Vrsta dokumenta')),
                ('organizational_unit', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='OJ')),
                ('partner_code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sifra partnera')),
                ('partner_name', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='Partner')),
                ('document_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum')),
                ('linked_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vezni dokument')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Potrazuje')),
                ('currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Valuta')),
                ('foreign_currency_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Devize')),
                ('subject_code', models.IntegerField(blank=True, null=True, verbose_name='Sifra predmeta')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='Stavka')),
                ('article_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Sifra artikla')),
                ('article_type', models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Vrsta artikla')),
                ('article_name', models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Naziv artikla')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Kolicina')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Cena')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinhronizovano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Roba',
                'verbose_name_plural': 'Roba',
                'db_table': 'nabavka_goods_snapshot',
                'ordering': ['-document_date', '-id'],
                'indexes': [models.Index(fields=['document_number', 'partner_name'], name='nabavka_goo_documen_0f7b10_idx'), models.Index(fields=['article_code', 'article_name'], name='nabavka_goo_article_0d8406_idx')],
            },
        ),
    ]
