# Generated by Django 5.0.9 on 2026-06-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0009_eufitemsnapshot_goodssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='euf_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_items', to='nabavka.procurementinvoice', verbose_name='EUF'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='goods_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_items', to='nabavka.goodssnapshot', verbose_name='Roba'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='source_type',
            field=models.CharField(blank=True, choices=[('', 'Bez povezivanja'), ('euf', 'EUF'), ('uf', 'UF'), ('goods', 'Roba')], max_length=10, verbose_name='Tip povezivanja'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='uf_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_items', to='nabavka.eufitemsnapshot', verbose_name='UF'),
        ),
    ]
