# Generated by Django 5.0.9 on 2026-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0010_procurementitem_euf_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementcase',
            name='needed_by',
            field=models.DateField(blank=True, null=True, verbose_name='Datum zahteva'),
        ),
    ]
