# Generated by Django 5.0.9 on 2026-06-03 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0011_procurement_case_request_date_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProcurementPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Godina')),
                ('version_number', models.PositiveIntegerField(verbose_name='Verzija')),
                ('source_filename', models.CharField(max_length=255, verbose_name='Excel fajl')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Ucitano')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Ukupno stavki')),
                ('added_count', models.PositiveIntegerField(default=0, verbose_name='Dodato')),
                ('changed_count', models.PositiveIntegerField(default=0, verbose_name='Izmenjeno')),
                ('unchanged_count', models.PositiveIntegerField(default=0, verbose_name='Bez izmene')),
                ('removed_count', models.PositiveIntegerField(default=0, verbose_name='Uklonjeno')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_procurement_plan_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uvezao')),
            ],
            options={
                'verbose_name': 'Verzija plana javnih nabavki',
                'verbose_name_plural': 'Verzije plana javnih nabavki',
                'db_table': 'nabavka_public_procurement_plan_version',
                'ordering': ['-year', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PublicProcurementPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('public', 'Javna nabavka'), ('exempt', 'Nabavka bez primene ZJN')], db_index=True, max_length=20, verbose_name='Tip plana')),
                ('diff_status', models.CharField(choices=[('added', 'Dodato'), ('changed', 'Izmenjeno'), ('unchanged', 'Bez izmene'), ('removed', 'Uklonjeno')], db_index=True, max_length=20, verbose_name='Status razlike')),
                ('stable_key', models.CharField(db_index=True, max_length=120, verbose_name='Kljuc stavke')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash sadrzaja')),
                ('source_sheet', models.CharField(max_length=120, verbose_name='Sheet')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Excel red')),
                ('item_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Redni broj')),
                ('subject_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vrsta predmeta')),
                ('title', models.TextField(verbose_name='Predmet nabavke')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Procenjena vrednost')),
                ('procurement_category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Predmet')),
                ('procedure_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vrsta postupka')),
                ('quarter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Okvirno vreme / kvartal')),
                ('cpv', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPV')),
                ('nuts', models.CharField(blank=True, max_length=255, null=True, verbose_name='NSTJ')),
                ('technique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tehnika / organizacioni deo')),
                ('conducted_by_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sprovodi drugi narucilac')),
                ('exemption_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Osnov izuzeca')),
                ('valuation_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacin procene vrednosti')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Izvorni podaci')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('previous_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version_items', to='nabavka.publicprocurementplanitem', verbose_name='Prethodna stavka')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nabavka.publicprocurementplanversion', verbose_name='Verzija')),
            ],
            options={
                'verbose_name': 'Stavka plana javnih nabavki',
                'verbose_name_plural': 'Stavke plana javnih nabavki',
                'db_table': 'nabavka_public_procurement_plan_item',
                'ordering': ['plan_type', 'source_sheet', 'item_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='publicprocurementplanversion',
            constraint=models.UniqueConstraint(fields=('year', 'version_number'), name='uniq_nabavka_public_procurement_plan_version_year_number'),
        ),
        migrations.AddIndex(
            model_name='publicprocurementplanitem',
            index=models.Index(fields=['plan_type', 'diff_status'], name='nabavka_pub_plan_ty_1d8260_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicprocurementplanitem',
            constraint=models.UniqueConstraint(fields=('version', 'stable_key'), name='uniq_nabavka_public_procurement_plan_item_version_key'),
        ),
    ]
