# Generated by Django 5.0.9 on 2026-06-11 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0060_putninalog_virman_generated_and_more'),
        ('nabavka', '0012_publicprocurementplanversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementInvoiceJobCodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_invoice_job_code_links', to=settings.AUTH_USER_MODEL, verbose_name='Povezao')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_code_links', to='nabavka.procurementinvoice', verbose_name='Faktura')),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nabavka_invoice_job_code_links', to='fleet.organizationalunit', verbose_name='OJ / sifra posla')),
            ],
            options={
                'verbose_name': 'Veza fakture i sifre posla',
                'verbose_name_plural': 'Veze faktura i sifara posla',
                'db_table': 'nabavka_invoice_job_code_link',
                'ordering': ['job_code__code', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='procurementinvoicejobcodelink',
            constraint=models.UniqueConstraint(fields=('invoice', 'job_code'), name='uniq_nabavka_invoice_job_code'),
        ),
    ]
