# Generated by Django 5.0.9 on 2026-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0013_procurementinvoicejobcodelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementinvoice',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Vraceno'),
        ),
    ]
