# Generated by Django 5.0.9 on 2026-06-11 06:55

import django.db.models.deletion
from decimal import Decimal
from hashlib import sha256
from django.db import migrations, models
from django.utils import timezone


def _clean(value):
    if value is None:
        return ""
    return str(value).strip()


def _source_key(*values):
    raw = "|".join(_clean(value) for value in values)
    return sha256(raw.encode("utf-8")).hexdigest()


def _group_key(item):
    invoice_number = _clean(item.invoice_number)
    partner_key = _clean(item.partner_pib) or _clean(item.partner_mb) or _clean(item.partner_name)
    fallback = _clean(item.purchase_invoice_id) or _clean(item.source_key)
    return _source_key(invoice_number or fallback, partner_key)


def _pick_latest_date(values):
    dates = [value for value in values if value]
    return max(dates) if dates else None


def _pick_first_text(values):
    for value in values:
        text = _clean(value)
        if text:
            return text
    return ""


def _pick_first_decimal(values):
    for value in values:
        if value is not None:
            return value
    return None


def build_uf_invoices(apps, schema_editor):
    EufItemSnapshot = apps.get_model("nabavka", "EufItemSnapshot")
    ProcurementItem = apps.get_model("nabavka", "ProcurementItem")
    UfInvoiceSnapshot = apps.get_model("nabavka", "UfInvoiceSnapshot")

    groups = {}
    for item in EufItemSnapshot.objects.all().order_by("invoice_number", "partner_name", "id"):
        groups.setdefault(_group_key(item), []).append(item)

    synced_at = timezone.now()
    for source_key, items in groups.items():
        invoice = UfInvoiceSnapshot.objects.create(
            source_key=source_key,
            purchase_invoice_id=_pick_first_text(item.purchase_invoice_id for item in items),
            invoice_number=_pick_first_text(item.invoice_number for item in items),
            partner_pib=_pick_first_text(item.partner_pib for item in items),
            partner_mb=_pick_first_text(item.partner_mb for item in items),
            partner_name=_pick_first_text(item.partner_name for item in items),
            document_date=_pick_latest_date(item.document_date for item in items),
            creation_date=_pick_latest_date(item.creation_date for item in items),
            due_date=_pick_latest_date(item.due_date for item in items),
            total=_pick_first_decimal(item.total for item in items),
            base_amount=_pick_first_decimal(item.base_amount for item in items),
            payment_amount=_pick_first_decimal(item.payment_amount for item in items),
            item_value_total=sum((item.value or Decimal("0.00")) for item in items),
            item_count=len(items),
            accounts=", ".join(sorted({account for account in (_clean(item.account) for item in items) if account})),
            synced_at=synced_at,
        )
        item_ids = [item.pk for item in items]
        EufItemSnapshot.objects.filter(pk__in=item_ids).update(uf_invoice=invoice)
        ProcurementItem.objects.filter(uf_item_id__in=item_ids, uf_invoice__isnull=True).update(uf_invoice=invoice)


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0014_procurementinvoice_is_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='UfInvoiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64, unique=True, verbose_name='Kljuc izvora')),
                ('purchase_invoice_id', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='UF ID')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='Broj fakture')),
                ('partner_pib', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='PIB partnera')),
                ('partner_mb', models.CharField(blank=True, max_length=20, null=True, verbose_name='MB partnera')),
                ('partner_name', models.CharField(blank=True, db_index=True, max_length=400, null=True, verbose_name='Partner')),
                ('document_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum dokumenta')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Datum kreiranja')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Datum dospeca')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ukupno')),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Osnovica')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Placanje')),
                ('item_value_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Vrednost stavki')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='Broj stavki')),
                ('accounts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konta')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinhronizovano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'UF faktura',
                'verbose_name_plural': 'UF fakture',
                'db_table': 'nabavka_uf_invoice_snapshot',
                'ordering': ['-document_date', '-id'],
                'indexes': [models.Index(fields=['invoice_number', 'partner_name'], name='nabavka_uf__invoice_edb79f_idx')],
            },
        ),
        migrations.AddField(
            model_name='eufitemsnapshot',
            name='uf_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='nabavka.ufinvoicesnapshot', verbose_name='UF faktura'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='uf_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_items', to='nabavka.ufinvoicesnapshot', verbose_name='UF faktura'),
        ),
        migrations.RunPython(build_uf_invoices, migrations.RunPython.noop),
    ]
