# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabavka", "0015_ufinvoicesnapshot_eufitemsnapshot_uf_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementinvoice",
            name="job_code_source",
            field=models.CharField(
                blank=True,
                choices=[("vehicle_snapshot", "Sifra posla automobila - snapshot")],
                default="",
                max_length=30,
                verbose_name="Izvor sifre posla",
            ),
        ),
        migrations.AddField(
            model_name="procurementinvoice",
            name="vehicle_job_code_assigned_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Datum dodele sifre posla vozilu",
            ),
        ),
    ]
