# Generated by Codex on 2026-06-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_primary_job_code_links(apps, schema_editor):
    ProcurementInvoice = apps.get_model("nabavka", "ProcurementInvoice")
    ProcurementInvoiceJobCodeLink = apps.get_model("nabavka", "ProcurementInvoiceJobCodeLink")
    links = []
    existing = set(
        ProcurementInvoiceJobCodeLink.objects.filter(
            invoice__job_code_id=models.F("job_code_id")
        ).values_list("invoice_id", "job_code_id")
    )
    for invoice in ProcurementInvoice.objects.exclude(job_code_id__isnull=True).only("id", "job_code_id"):
        key = (invoice.pk, invoice.job_code_id)
        if key in existing:
            ProcurementInvoiceJobCodeLink.objects.filter(
                invoice_id=invoice.pk,
                job_code_id=invoice.job_code_id,
            ).update(kind="primary")
            continue
        links.append(
            ProcurementInvoiceJobCodeLink(
                invoice_id=invoice.pk,
                job_code_id=invoice.job_code_id,
                kind="primary",
            )
        )
    ProcurementInvoiceJobCodeLink.objects.bulk_create(links)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nabavka", "0016_procurementinvoice_job_code_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementinvoicejobcodelink",
            name="kind",
            field=models.CharField(
                choices=[("primary", "Osnovna"), ("additional", "Dodatna")],
                db_index=True,
                default="additional",
                max_length=20,
                verbose_name="Tip veze",
            ),
        ),
        migrations.AddField(
            model_name="procurementinvoicejobcodelink",
            name="is_returned",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Vraceno"),
        ),
        migrations.AddField(
            model_name="procurementinvoicejobcodelink",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Vraceno u"),
        ),
        migrations.AddField(
            model_name="procurementinvoicejobcodelink",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nabavka_returned_invoice_job_code_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oznacio kao vraceno",
            ),
        ),
        migrations.RunPython(backfill_primary_job_code_links, migrations.RunPython.noop),
    ]
