# Generated by Codex on 2026-06-22

from django.db import migrations
from django.utils import timezone


def backfill_returned_job_code_links(apps, schema_editor):
    ProcurementInvoice = apps.get_model("nabavka", "ProcurementInvoice")
    ProcurementInvoiceJobCodeLink = apps.get_model("nabavka", "ProcurementInvoiceJobCodeLink")
    now = timezone.now()

    returned_invoices = ProcurementInvoice.objects.filter(is_returned=True).only("id", "job_code_id")
    existing = set(
        ProcurementInvoiceJobCodeLink.objects.values_list("invoice_id", "job_code_id")
    )
    links_to_create = []
    for invoice in returned_invoices:
        if not invoice.job_code_id:
            continue
        key = (invoice.pk, invoice.job_code_id)
        if key in existing:
            continue
        links_to_create.append(
            ProcurementInvoiceJobCodeLink(
                invoice_id=invoice.pk,
                job_code_id=invoice.job_code_id,
                kind="primary",
            )
        )
        existing.add(key)
    if links_to_create:
        ProcurementInvoiceJobCodeLink.objects.bulk_create(links_to_create)

    ProcurementInvoiceJobCodeLink.objects.filter(
        invoice__is_returned=True,
        is_returned=False,
    ).update(
        is_returned=True,
        returned_at=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("nabavka", "0017_invoice_job_code_returned_status"),
    ]

    operations = [
        migrations.RunPython(backfill_returned_job_code_links, migrations.RunPython.noop),
    ]
