# Generated by Django 5.0.9 on 2026-09-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0075_vehicle_photo'),
        ('nabavka', '0018_backfill_returned_job_code_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcase',
            name='garage_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_cases', to='fleet.kvar', verbose_name='Nalog garaže'),
        ),
        migrations.AddField(
            model_name='procurementcase',
            name='work_type',
            field=models.CharField(blank=True, choices=[('mali_servis', 'Mali servis'), ('veliki_servis', 'Veliki servis'), ('popravka', 'Popravka')], default='', max_length=20, verbose_name='Vrsta intervencije'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='work_type',
            field=models.CharField(blank=True, choices=[('mali_servis', 'Mali servis'), ('veliki_servis', 'Veliki servis'), ('popravka', 'Popravka')], default='', max_length=20, verbose_name='Vrsta intervencije'),
        ),
    ]
