# Generated by Django 5.0.9 on 2026-09-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0019_vehicle_service_tracking'),
        ('organizacija', '0006_nauka_deo_bloka_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcase',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nabavka_predmeti', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nabavka_fakture', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
        migrations.AddField(
            model_name='procurementinvoicejobcodelink',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nabavka_veze_faktura', to='organizacija.orgnode', verbose_name='Čvor registra'),
        ),
    ]
