# Generated by Django 5.0.9 on 2026-09-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0087_zaposleni_u_registru'),
        ('nabavka', '0020_veza_sa_registrom_organizacije'),
        ('organizacija', '0009_dodela_daje_ulogu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiskalniRacun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Link sa QR koda')),
                ('broj_racuna', models.CharField(max_length=60, unique=True, verbose_name='PFR broj računa')),
                ('zatrazio', models.CharField(blank=True, max_length=20, verbose_name='Zatražio (ESIR)')),
                ('potpisao', models.CharField(blank=True, max_length=20, verbose_name='Potpisao (PFR)')),
                ('brojac_ukupno', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ukupan brojač')),
                ('brojac_vrste', models.PositiveIntegerField(blank=True, null=True, verbose_name='Brojač vrste')),
                ('oznaka_brojaca', models.CharField(blank=True, max_length=10, verbose_name='Oznaka brojača')),
                ('vrsta_racuna', models.PositiveSmallIntegerField(default=0, verbose_name='Vrsta računa')),
                ('vrsta_transakcije', models.PositiveSmallIntegerField(default=0, verbose_name='Vrsta transakcije')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Ukupan iznos')),
                ('pdv_ukupno', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Ukupan PDV')),
                ('pfr_vreme', models.DateTimeField(db_index=True, verbose_name='PFR vreme')),
                ('id_kupca', models.CharField(blank=True, max_length=60, verbose_name='ID kupca')),
                ('pib_kupca', models.CharField(blank=True, max_length=20, verbose_name='PIB kupca')),
                ('na_ims', models.BooleanField(default=False, verbose_name='Izdat na IMS')),
                ('pib_prodavca', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='PIB prodavca')),
                ('naziv_prodavca', models.CharField(blank=True, max_length=255, verbose_name='Prodavac')),
                ('prodajno_mesto', models.CharField(blank=True, max_length=255, verbose_name='Prodajno mesto')),
                ('adresa', models.CharField(blank=True, max_length=255, verbose_name='Adresa')),
                ('grad', models.CharField(blank=True, max_length=120, verbose_name='Grad')),
                ('opstina', models.CharField(blank=True, max_length=120, verbose_name='Opština')),
                ('kasir', models.CharField(blank=True, max_length=120, verbose_name='Kasir')),
                ('esir_broj', models.CharField(blank=True, max_length=60, verbose_name='ESIR broj')),
                ('nacin_placanja', models.CharField(blank=True, max_length=255, verbose_name='Način plaćanja')),
                ('zurnal', models.TextField(blank=True, verbose_name='Tekst računa')),
                ('status', models.CharField(choices=[('potvrdjen', 'Potvrđen'), ('ceka', 'Čeka proveru')], default='ceka', max_length=12, verbose_name='Status')),
                ('greska', models.CharField(blank=True, max_length=500, verbose_name='Poslednja greška preuzimanja')),
                ('preuzeto', models.DateTimeField(blank=True, null=True, verbose_name='Preuzeto sa stranice za proveru')),
                ('napomena', models.CharField(blank=True, max_length=500, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Učitano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_fiskalni_racuni', to=settings.AUTH_USER_MODEL, verbose_name='Učitao')),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiskalni_racuni', to='fleet.organizationalunit', verbose_name='Šifra posla')),
                ('org_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiskalni_racuni', to='organizacija.orgnode')),
            ],
            options={
                'verbose_name': 'Fiskalni račun',
                'verbose_name_plural': 'Fiskalni računi',
                'ordering': ['-pfr_vreme', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiskalniRacunStavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveIntegerField(verbose_name='R. br.')),
                ('gtin', models.CharField(blank=True, max_length=40, verbose_name='GTIN / bar kod')),
                ('naziv', models.CharField(max_length=500, verbose_name='Naziv')),
                ('kolicina', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Količina')),
                ('jedinicna_cena', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Jed. cena sa PDV')),
                ('ukupno', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Ukupno')),
                ('oznaka_pdv', models.CharField(blank=True, max_length=5, verbose_name='Oznaka PDV')),
                ('stopa_pdv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stopa PDV %')),
                ('osnovica', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Osnovica')),
                ('pdv', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='PDV')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='nabavka.fiskalniracun')),
            ],
            options={
                'verbose_name': 'Stavka fiskalnog računa',
                'verbose_name_plural': 'Stavke fiskalnog računa',
                'ordering': ['racun', 'redni_broj'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiskalniracunstavka',
            constraint=models.UniqueConstraint(fields=('racun', 'redni_broj'), name='nabavka_fiskalni_stavka_rb'),
        ),
    ]
