# Generated by Django 5.0.9 on 2026-09-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0021_fiskalni_racuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementinvoice',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naziv dokumenta'),
        ),
        migrations.AddField(
            model_name='procurementinvoice',
            name='partner_pib',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='PIB partnera'),
        ),
    ]
