# Generated by Django 5.0.9 on 2026-09-28 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0087_zaposleni_u_registru'),
        ('nabavka', '0022_euf_naziv_i_pib'),
        ('organizacija', '0009_dodela_daje_ulogu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskalniracun',
            name='goes_to_warehouse',
            field=models.BooleanField(default=False, verbose_name='Ide u magacin'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='is_garage',
            field=models.BooleanField(default=False, verbose_name='Garaža'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Vraćeno'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nabavka_fiskalni_racuni', to='fleet.vehicle', verbose_name='Vozilo'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='work_type',
            field=models.CharField(blank=True, choices=[('mali_servis', 'Mali servis'), ('veliki_servis', 'Veliki servis'), ('popravka', 'Popravka')], default='', max_length=20, verbose_name='Vrsta intervencije'),
        ),
        migrations.CreateModel(
            name='FiskalniRacunSifra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('osnovna', 'Osnovna'), ('dodatna', 'Dodatna')], default='dodatna', max_length=10)),
                ('is_returned', models.BooleanField(default=False, verbose_name='Vraćeno')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Vraćeno u')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiskalni_racuni_sifre', to='fleet.organizationalunit', verbose_name='Šifra posla')),
                ('org_node', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiskalni_racuni_sifre', to='organizacija.orgnode')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sifre', to='nabavka.fiskalniracun')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Označio kao vraćeno')),
            ],
            options={
                'verbose_name': 'Šifra posla fiskalnog računa',
                'verbose_name_plural': 'Šifre posla fiskalnih računa',
                'ordering': ['racun', '-vrsta', 'job_code__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiskalniracunsifra',
            constraint=models.UniqueConstraint(fields=('racun', 'job_code'), name='nabavka_fiskalni_sifra_jedinstvena'),
        ),
    ]
