# Generated by Django 5.0.9 on 2026-10-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0089_opomene_goriva'),
        ('nabavka', '0023_fiskalni_obrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskalniracun',
            name='proknjizeno',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Proknjiženo'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='proknjizeno_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proknjiženo dana'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='proknjizio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proknjižio'),
        ),
        migrations.AddField(
            model_name='fiskalniracun',
            name='putni_nalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiskalni_racuni', to='fleet.putninalog', verbose_name='Putni nalog'),
        ),
    ]
