# Generated by Django 5.0.9 on 2026-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabavka', '0024_fiskalni_putni_nalog_proknjizeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiskalniracun',
            name='evidencija',
            field=models.CharField(choices=[('nabavka', 'Nabavka'), ('gotovina', 'Ostali fiskalni računi (gotovinski obračun)')], db_default='nabavka', db_index=True, default='nabavka', max_length=10, verbose_name='Evidencija'),
        ),
    ]
