# Generated by Django 5.0.9 on 2026-10-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0094_zaposleni_radna_mesta'),
        ('nabavka', '0025_fiskalni_evidencija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiskalniracun',
            name='job_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiskalni_racuni', to='fleet.organizationalunit', verbose_name='Šifra posla'),
        ),
    ]
