# Generated by Django 5.0.9 on 2026-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('center', models.CharField(blank=True, db_index=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('profit_type', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('journal_type', models.CharField(max_length=3)),
                ('journal_number', models.IntegerField()),
                ('line_number', models.IntegerField()),
                ('organizational_unit', models.IntegerField()),
                ('organizational_unit_name', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(max_length=6)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('partner_group', models.IntegerField(null=True)),
                ('partner_code', models.IntegerField(null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('document_date', models.DateField()),
                ('document_reference', models.CharField(blank=True, max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('foreign_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('linked_line', models.IntegerField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('change_status', models.CharField(blank=True, max_length=1)),
                ('job_code', models.CharField(blank=True, max_length=10)),
                ('job_name', models.CharField(blank=True, max_length=100)),
                ('center', models.CharField(blank=True, max_length=10)),
                ('booking_date', models.DateField()),
                ('debit_credit_flag', models.CharField(blank=True, max_length=1)),
                ('source_paid_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('changed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('running', 'U toku'), ('success', 'Uspešno'), ('failed', 'Neuspešno')], default='running', max_length=10)),
                ('company', models.PositiveIntegerField()),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField()),
                ('source_rows', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('removed', models.PositiveIntegerField(default=0)),
                ('source_totals', models.JSONField(default=dict)),
                ('latest_booking_date', models.DateField(null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='financejob',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='fin_job_company_code'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'active', 'booking_date'], name='fin_ledger_period'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'center', 'booking_date'], name='fin_ledger_center'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'job_code', 'booking_date'], name='fin_ledger_job'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'account', 'booking_date'], name='fin_ledger_account'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'partner_code', 'document_reference'], name='fin_ledger_document'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'journal_type', 'journal_number', 'line_number'), name='fin_ledger_source_key'),
        ),
    ]
