# Generated by Django 5.0.9 on 2026-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NalogZRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('running', 'U toku'), ('success', 'Uspešno'), ('failed', 'Neuspešno'), ('skipped', 'Preskočeno'), ('unknown', 'Ishod nepoznat')], default='running', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Ručno'), ('celery', 'Celery')], max_length=10)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('year_from', models.PositiveSmallIntegerField(null=True)),
                ('year_to', models.PositiveSmallIntegerField(null=True)),
                ('updated_rows', models.PositiveBigIntegerField(null=True)),
                ('inserted_rows', models.PositiveBigIntegerField(null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-pk'],
            },
        ),
    ]
