# Generated by Django 5.0.9 on 2026-09-21 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0002_nalogzrefreshrun'),
        ('menice', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField(default=1)),
                ('account', models.CharField(max_length=6, verbose_name='Konto')),
                ('bank_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Banka')),
                ('segment', models.CharField(choices=[('dinar', 'Dinarski račun'), ('foreign', 'Devizni račun'), ('deposit', 'Oročena sredstva'), ('guarantee', 'Depozit za garanciju'), ('other', 'Ostalo poslovanje'), ('excluded', 'Nije račun banke')], max_length=12, verbose_name='Vrsta posla')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Napomena')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='BankBillPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField(default=1)),
                ('bank_code', models.PositiveIntegerField()),
                ('delivered_on', models.DateField(verbose_name='Datum predaje')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='Datum vraćanja')),
                ('note', models.TextField(blank=True, verbose_name='Namena / napomena')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menice.menica')),
                ('incoming_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menice.ulaznamenica')),
            ],
            options={
                'ordering': ['-delivered_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BankContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.PositiveIntegerField(default=1)),
                ('bank_code', models.PositiveIntegerField()),
                ('segment', models.CharField(max_length=120, verbose_name='Vrsta posla')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Kontakt osoba')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Funkcija')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email osobe')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('shared_emails', models.TextField(blank=True, verbose_name='Zajednički emailovi segmenta')),
                ('note', models.TextField(blank=True, verbose_name='Napomena')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['segment', 'name', 'pk'],
                'indexes': [models.Index(fields=['company', 'bank_code'], name='fin_bank_contact')],
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccountrule',
            constraint=models.UniqueConstraint(fields=('company', 'account'), name='fin_bank_account_rule'),
        ),
        migrations.AddConstraint(
            model_name='bankbillplacement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bill__isnull', False), ('incoming_bill__isnull', True)), models.Q(('bill__isnull', True), ('incoming_bill__isnull', False)), _connector='OR'), name='fin_bank_bill_one_source'),
        ),
        migrations.AddConstraint(
            model_name='bankbillplacement',
            constraint=models.CheckConstraint(check=models.Q(('returned_on__isnull', True), ('returned_on__gte', models.F('delivered_on')), _connector='OR'), name='fin_bank_bill_dates'),
        ),
        migrations.AddConstraint(
            model_name='bankbillplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('bill__isnull', False), ('returned_on__isnull', True)), fields=('company', 'bill'), name='fin_bank_bill_held'),
        ),
        migrations.AddConstraint(
            model_name='bankbillplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('incoming_bill__isnull', False), ('returned_on__isnull', True)), fields=('company', 'incoming_bill'), name='fin_bank_incoming_held'),
        ),
    ]
