# Generated by Django 5.0.9 on 2026-09-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0003_bankaccountrule_bankbillplacement_bankcontact_and_more'),
        ('organizacija', '0006_nauka_deo_bloka_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='org_node',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finansije_knjizenja', to='organizacija.orgnode'),
        ),
    ]
