# Generated by Django 5.0.9 on 2026-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0004_veza_sa_registrom_organizacije'),
        ('organizacija', '0008_dodele_odobravanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='org_centar',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'org_centar', 'booking_date'], name='fin_ledger_org_centar'),
        ),
    ]
