# Generated by Django 5.0.9 on 2026-09-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0005_centar_iz_registra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SefFaktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smer', models.CharField(choices=[('ulazna', 'Ulazna'), ('izlazna', 'Izlazna')], db_index=True, max_length=10)),
                ('sef_id', models.BigIntegerField(verbose_name='ID na SEF-u')),
                ('glob_uniq_id', models.CharField(blank=True, default='', max_length=64)),
                ('broj', models.CharField(blank=True, default='', max_length=100, verbose_name='Broj dokumenta')),
                ('broj_kljuc', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=100)),
                ('vrsta', models.CharField(blank=True, default='', max_length=30, verbose_name='Vrsta dokumenta')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('cir_id', models.CharField(blank=True, default='', max_length=40, verbose_name='CRF identifikator')),
                ('partner_naziv', models.CharField(blank=True, default='', max_length=255, verbose_name='Partner')),
                ('partner_pib', models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='PIB partnera')),
                ('partner_mb', models.CharField(blank=True, default='', max_length=20, verbose_name='Matični broj partnera')),
                ('iznos', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('osnovica', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pdv', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valuta', models.CharField(blank=True, default='', max_length=3)),
                ('datum_izdavanja', models.DateField(blank=True, null=True)),
                ('datum_prometa', models.DateField(blank=True, null=True)),
                ('datum_dospeca', models.DateField(blank=True, null=True)),
                ('datum_slanja', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('izmenjeno_na_sefu', models.DateTimeField(blank=True, null=True)),
                ('sinhronizovano', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'SEF faktura',
                'verbose_name_plural': 'SEF fakture',
                'db_table': 'finansije_sef_faktura',
                'ordering': ['-datum_slanja', '-sef_id'],
            },
        ),
        migrations.CreateModel(
            name='SefPromena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smer', models.CharField(choices=[('ulazna', 'Ulazna'), ('izlazna', 'Izlazna')], max_length=10)),
                ('event_id', models.BigIntegerField()),
                ('sef_id', models.BigIntegerField(db_index=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('komentar', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'finansije_sef_promena',
                'ordering': ['-datum', '-event_id'],
            },
        ),
        migrations.CreateModel(
            name='SefSinhronizacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'U toku'), ('success', 'Uspešno'), ('error', 'Greška')], default='running', max_length=10)),
                ('od', models.DateField()),
                ('do', models.DateField()),
                ('counts', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'finansije_sef_sinhronizacija',
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='seffaktura',
            constraint=models.UniqueConstraint(fields=('smer', 'sef_id'), name='fin_sef_faktura_kljuc'),
        ),
        migrations.AddConstraint(
            model_name='sefpromena',
            constraint=models.UniqueConstraint(fields=('smer', 'event_id'), name='fin_sef_promena_kljuc'),
        ),
        migrations.AddField(
            model_name='sefsinhronizacija',
            name='korisnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
