# Generated by Django 5.0.9 on 2026-09-30 13:43

from django.db import migrations, models


def popuni_broj_knjizenja(apps, schema_editor):
    from finansije.sef_models import broj_u_knjizenju

    SefFaktura = apps.get_model("finansije", "SefFaktura")
    for faktura in SefFaktura.objects.exclude(broj_kljuc="").only("pk", "broj"):
        SefFaktura.objects.filter(pk=faktura.pk).update(broj_knjizenja=broj_u_knjizenju(faktura.broj))


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0006_sef_fakture'),
        ('organizacija', '0009_dodela_daje_ulogu'),
    ]

    operations = [
        migrations.AddField(
            model_name='seffaktura',
            name='broj_knjizenja',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='seffaktura',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, upload_to='finansije/sef/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='seffaktura',
            name='pdf_preuzet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['company', 'document_reference'], name='fin_ledger_doc_ref'),
        ),
        migrations.RunPython(popuni_broj_knjizenja, migrations.RunPython.noop),
    ]
