# Generated by Django 5.0.9 on 2026-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0007_sef_pdf_i_broj_knjizenja'),
    ]

    operations = [
        migrations.AddField(
            model_name='sefsinhronizacija',
            name='zaustavi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sefsinhronizacija',
            name='status',
            field=models.CharField(choices=[('running', 'U toku'), ('success', 'Uspešno'), ('error', 'Greška'), ('stopped', 'Zaustavljeno')], default='running', max_length=10),
        ),
    ]
