# Generated by Django 5.0.9 on 2026-10-07 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finansije', '0008_sef_zaustavljanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='seffaktura',
            name='prilozi_preuzeti',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SefPrilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni', models.PositiveSmallIntegerField()),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('fajl', models.FileField(max_length=255, upload_to='finansije/sef/prilozi/%Y/%m/')),
                ('velicina', models.PositiveIntegerField(default=0)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prilozi', to='finansije.seffaktura')),
            ],
            options={
                'db_table': 'finansije_sef_prilog',
                'ordering': ['faktura', 'redni'],
            },
        ),
        migrations.AddConstraint(
            model_name='sefprilog',
            constraint=models.UniqueConstraint(fields=('faktura', 'redni'), name='fin_sef_prilog_kljuc'),
        ),
    ]
