"""
Django settings for ims_erp project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# SQL Server connection defaults used by environment-specific DATABASES blocks.
MSSQL_DRIVER = os.getenv('MSSQL_DRIVER', 'ODBC Driver 17 for SQL Server')
MSSQL_CONN_MAX_AGE = int(os.getenv('MSSQL_CONN_MAX_AGE', '300'))
MSSQL_CONN_HEALTH_CHECKS = os.getenv('MSSQL_CONN_HEALTH_CHECKS', '1') == '1'
MSSQL_CONNECTION_TIMEOUT = int(os.getenv('MSSQL_CONNECTION_TIMEOUT', '10'))
MSSQL_QUERY_TIMEOUT = int(os.getenv('MSSQL_QUERY_TIMEOUT', '90'))
MSSQL_CONNECTION_RETRIES = int(os.getenv('MSSQL_CONNECTION_RETRIES', '3'))
MSSQL_CONNECTION_RETRY_BACKOFF_TIME = int(
    os.getenv('MSSQL_CONNECTION_RETRY_BACKOFF_TIME', '5')
)
MSSQL_TRUST_SERVER_CERTIFICATE = os.getenv(
    'MSSQL_TRUST_SERVER_CERTIFICATE', '1'
) == '1'


def apply_mssql_connection_defaults(databases):
    """
    Apply conservative defaults for mssql-django connections to reduce
    short-lived reconnect churn in long-running Celery processes.
    """
    for db_config in databases.values():
        if db_config.get('ENGINE') != 'mssql':
            continue

        db_config.setdefault('CONN_MAX_AGE', MSSQL_CONN_MAX_AGE)
        db_config.setdefault('CONN_HEALTH_CHECKS', MSSQL_CONN_HEALTH_CHECKS)

        options = db_config.setdefault('OPTIONS', {})
        options.setdefault('driver', MSSQL_DRIVER)
        options.setdefault('connection_timeout', MSSQL_CONNECTION_TIMEOUT)
        options.setdefault('query_timeout', MSSQL_QUERY_TIMEOUT)
        options.setdefault('connection_retries', MSSQL_CONNECTION_RETRIES)
        options.setdefault(
            'connection_retry_backoff_time',
            MSSQL_CONNECTION_RETRY_BACKOFF_TIME,
        )

        if MSSQL_TRUST_SERVER_CERTIFICATE:
            extra_params = options.get('extra_params', '')
            if 'TrustServerCertificate=' not in extra_params:
                if extra_params and not extra_params.endswith(';'):
                    extra_params = f'{extra_params};'
                options['extra_params'] = f'{extra_params}TrustServerCertificate=yes;'

    return databases


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)!_&_xkzdmy(u)og*824h$nur02--378mitdd_ib52ali7nuke'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True




# Application definition

INSTALLED_APPS = [
    "core",
    'fleet',
    'hr',
    'naplata',
    'menice',
    'ugovori',
    'nabavka',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_select2',
    'django_celery_beat',
    'widget_tweaks',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ims_erp.urls'


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Gleda prvo u PROJECT/templates (globalno), zatim u app/templates (APP_DIRS=True)
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.current_app",
            ],
        },
    },
]

DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y']

WSGI_APPLICATION = 'ims_erp.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'
TIME_ZONE = 'CET'
USE_L10N = False
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'fleet/static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MAX_CONTRACT_UPLOAD_SIZE = int(os.getenv("MAX_CONTRACT_UPLOAD_SIZE", str(50 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(60 * 1024 * 1024)))


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
AUTH_USER_MODEL = 'fleet.CustomUser' 


# Celery postavke
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE

# Windows-friendly defaulti: niska paralelizacija i ograničen prefetch.
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '2'))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv('CELERY_WORKER_PREFETCH_MULTIPLIER', '1'))
CELERY_BROKER_POOL_LIMIT = int(os.getenv('CELERY_BROKER_POOL_LIMIT', '5'))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_WORKER_MAX_TASKS_PER_CHILD', '100'))
CELERY_BEAT_MAX_LOOP_INTERVAL = int(os.getenv('CELERY_BEAT_MAX_LOOP_INTERVAL', '30'))

# Smanjuje pritisak na Redis backend (rezultati taskova nisu kritični u ovom projektu).
CELERY_TASK_IGNORE_RESULT = os.getenv('CELERY_TASK_IGNORE_RESULT', '1') == '1'
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True
CELERY_RESULT_EXPIRES = int(os.getenv('CELERY_RESULT_EXPIRES', '3600'))

# Routing po queue-ovima da teški Selenium taskovi ne blokiraju lake sync taskove.
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'fleet.tasks.run_nis_command': {'queue': 'selenium'},
    'fleet.tasks.run_omv_putnicka_command': {'queue': 'selenium'},
    'fleet.tasks.run_omv_teretna_command': {'queue': 'selenium'},
    'fleet.tasks.kerio_login_task': {'queue': 'selenium'},
    'fleet.tasks.fetch_policy_data_task': {'queue': 'sync'},
    'fleet.tasks.fetch_service_data_task': {'queue': 'sync'},
    'fleet.tasks.fetch_requisition_data_task': {'queue': 'sync'},
    'fleet.tasks.fetch_ddor_data_task': {'queue': 'sync'},
    'fleet.tasks.fetch_job_codes': {'queue': 'sync'},
    'fleet.tasks.proveri_otpis': {'queue': 'sync'},
    'fleet.tasks.sync_hr_employees_task': {'queue': 'sync'},
    'core.tasks.sync_permission_codes_task': {'queue': 'sync'},
}

CELERY_WORKER_REDIRECT_STDOUTS = False
