# Generated by Django 5.0.9 on 2026-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplata', '0002_avansklijent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avansklijent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
