# Generated by Django 5.0.9 on 2026-03-11 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplata', '0003_alter_avansklijent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postupak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('tuzeni', 'Tuženi'), ('tuzili', 'Tužili'), ('stecaj', 'Stečaj'), ('uppr', 'UPPR')], default='tuzeni', max_length=20)),
                ('sud', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sud')),
                ('sudski_broj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sudski broj')),
                ('izvrsiteljski_broj', models.CharField(blank=True, max_length=100, null=True, verbose_name='Izvršiteljski broj')),
                ('sifra_partnera', models.IntegerField(blank=True, null=True, verbose_name='Šifra partnera')),
                ('naziv_partnera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv partnera')),
                ('naziv_partnera_u_nalogu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv partnera u nalogu')),
                ('mesto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesto')),
                ('datum_pokretanja', models.DateField(blank=True, null=True, verbose_name='Datum pokretanja postupka')),
                ('predmet_spora', models.TextField(blank=True, null=True, verbose_name='Predmet spora')),
                ('osnovni_dug', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Osnovni dug (glavnica), u dinarima')),
                ('arhivirano', models.BooleanField(default=False, verbose_name='Arhivirano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postupci_kreirani', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postupak',
                'verbose_name_plural': 'Postupci',
                'db_table': 'postupak',
                'ordering': ['-datum_pokretanja', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromenaPostupka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('promena', models.TextField(verbose_name='Promena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promene_postupaka', to=settings.AUTH_USER_MODEL)),
                ('postupak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promene', to='naplata.postupak', verbose_name='Postupak')),
            ],
            options={
                'verbose_name': 'Promena postupka',
                'verbose_name_plural': 'Promene postupaka',
                'db_table': 'promena_postupka',
                'ordering': ['-datum', '-created_at'],
            },
        ),
    ]
