# Generated by Django 5.0.9 on 2026-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naplata', '0004_pravna_postupak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postupak',
            options={'ordering': ['-created_at'], 'verbose_name': 'Postupak', 'verbose_name_plural': 'Postupci'},
        ),
        migrations.RemoveField(
            model_name='postupak',
            name='mesto',
        ),
        migrations.RemoveField(
            model_name='postupak',
            name='naziv_partnera_u_nalogu',
        ),
        migrations.RemoveField(
            model_name='postupak',
            name='sudski_broj',
        ),
        migrations.AddField(
            model_name='postupak',
            name='broj_predmeta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj predmeta'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='datum_otvaranja_stecaja',
            field=models.DateField(blank=True, null=True, verbose_name='Datum otvaranja stečajnog postupka'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='datum_podnosenja_tuzbe',
            field=models.DateField(blank=True, null=True, verbose_name='Datum podnošenja tužbe'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='kamata',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kamata'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='novi_broj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Novi broj'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='pib',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIB'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='prijava_potrazivanja',
            field=models.TextField(blank=True, null=True, verbose_name='Prijava potraživanja'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='troskovi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Troškovi'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='tuzilac',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tužilac'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='ukupan_dug',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ukupan dug'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='valuta',
            field=models.CharField(choices=[('RSD', 'RSD'), ('EUR', 'EUR'), ('USD', 'USD')], default='RSD', max_length=10, verbose_name='Valuta'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='vece',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Veće'),
        ),
        migrations.AddField(
            model_name='postupak',
            name='vrednost_spora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Vrednost spora'),
        ),
        migrations.AlterField(
            model_name='postupak',
            name='osnovni_dug',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Osnovni dug (glavnica)'),
        ),
        migrations.AlterField(
            model_name='postupak',
            name='sifra_partnera',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Šifra partnera'),
        ),
        migrations.AlterField(
            model_name='postupak',
            name='tip',
            field=models.CharField(choices=[('tuzeni', 'Tuženi'), ('tuzili', 'Tužili'), ('stecaj', 'Stečaj'), ('uppr', 'UPPR')], db_index=True, default='tuzeni', max_length=20),
        ),
    ]
